kiegroup/kie-wb-distributions

kie-wb-smoke-tests/pom.xml
* before the change, "selenium" profile would overwite
the failsafe config causing execution of only the
seleinum based tests (others would be ignored). This
change adds new failsafe execution that runs the selenium
tests. It will be executed after the other smoke tests are
ran.
* by default Selenium tests are still disabled (no change here).
One needs to enable 'selenium' profile to run them.
@jhrcek please take a look. The change effectively means that using `mvn clean install -Pkie-wb,tomcat7x,selenium` will run other smoke tests (REST, etc) as well, not just the selenium ones like so far. This should simplify execution of the tests in CI and also locally. I just want to make sure I did not overlook something.
=> Do not disable other smoke tests when running Selenium tests

kie-wb/kie-wb-webapp/src/main/resources/META-INF/kie-wb-deployment-descriptor.xml
Configures the RESTWorkItemHandler with 'classLoader' argument by default, which allows to use ResultClass attribute in the WorkItem without any further changes.
=> JBPM-4906 RestWorkItemHandler fails with CNFE when using ResultSet

kie-wb-smoke-tests/kie-wb-smoke-tests-main/src/main/java/org/kie/smoke/wb/selenium/model/persps/PeoplePerspective.java, kie-wb-smoke-tests/kie-wb-smoke-tests-main/src/main/java/org/kie/smoke/wb/selenium/model/persps/ProcessAndTaskDashboardPerspective.java, kie-wb-smoke-tests/kie-wb-smoke-tests-main/src/main/java/org/kie/smoke/wb/selenium/model/persps/TasksPerspective.java, kie-wb-smoke-tests/kie-wb-smoke-tests-main/src/main/java/org/kie/smoke/wb/selenium/util/LoadingIndicator.java
Addressing recent flakiness of kie-wb selenium smoke jobs.
1) Problems with navigating to PlugIn Management / Process & Task Dashboard perspectives because the previous perspectives were not fully loaded -> Added explicit wait for those persps. to be loaded.
2) Change in locator after recent i18n commits
=> Stabilize selenium smokes

kie-drools-wb/kie-drools-wb-distribution-wars/src/main/productized/styles/product.css, kie-wb/kie-wb-distribution-wars/src/main/productized/styles/product.css
Moved menu a few pixels down to not overlap with top red bar.
From this: 
To:
=> Fix for positioning utility menu bar

kie-wb-smoke-tests/kie-wb-smoke-tests-main/src/main/java/org/kie/smoke/wb/selenium/model/persps/TasksPerspective.java
Analyzing the occasional fails in [kie-wb-smoke](https://kie-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/kie-wb-smoke-selenium-windows-6.4.x/) on windows it is most likely that navigation to Plugin management perspective fails because Task list perspective was not yet fully loaded (as seen in screenshot artifacts in any of the yellow-ball job runs).
Current implementation was already waiting for perspective loading animation to disappear. Since disappearance of that is the last observable thing that happens in the DOM during the perspective loading, there is nothing better to use for waiting for perspective to load -> I added additional 2s wait for tasklist perspective to load.
=> Prevent occasional fails in selenium smokes on Windows

kie-drools-wb/kie-drools-wb-webapp/src/main/java/org/kie/workbench/drools/client/perspectives/AdministrationPerspective.java, kie-wb/kie-wb-webapp/src/main/java/org/kie/workbench/client/perspectives/AdministrationPerspective.java
Note: The Menus and Home Page sections already restrict features access by using KieACL.
=> [6.4.x] BZ-1320502: AdministrationPerspective not loading for administrative user whose roles is not defined as admin

kie-drools-wb/kie-drools-wb-webapp/src/main/java/org/kie/workbench/drools/client/perspectives/AdministrationPerspective.java, kie-wb/kie-wb-webapp/src/main/java/org/kie/workbench/client/perspectives/AdministrationPerspective.java
Note: The Menus and Home Page sections already restrict features access by using KieACL.
=> [6.3.x] BZ-1320502: AdministrationPerspective not loading for administrative user whose roles is not defined as admin

kie-drools-wb/kie-drools-wb-webapp/src/main/java/org/kie/workbench/drools/backend/server/AppSetup.java
Bug ticket in master was Bug 1316224 - User can not create projects in any other repository than master
Ticket for this branch is here: https://bugzilla.redhat.com/show_bug.cgi?id=1316566
(cherry picked from commit 57756033f2d524d729fdc5641e397fe8fbb4430c)
https://github.com/droolsjbpm/guvnor/pull/286
https://github.com/droolsjbpm/kie-wb-common/pull/310
https://github.com/droolsjbpm/drools-wb/pull/144
https://github.com/droolsjbpm/jbpm-console-ng/pull/365
https://github.com/droolsjbpm/kie-wb-distributions/pull/229
=> [6.3.x] Bug 1316566 - User can not create projects in any other repository than master

kie-wb/kie-wb-distribution-wars/src/main/assembly/was8/README.md
@agiertli Thanks for the heads up!
@m-czernek Could you make sure the product documentation for 6.1, 6.2 and 6.3 reflects this change? Thanks!
=> - the kie.services.rest.deploy.async property is only valid in the 6.0.x

kie-drools-wb/kie-drools-wb-distribution-wars/src/main/assembly/component-kie-drools-wb-eap-6_4-common.xml, kie-wb/kie-wb-distribution-wars/src/main/assembly/component-kie-wb-eap-6_4-common.xml
This is a trivial fix to make the WARs working on EAP 6.4 until we move to WFLY10/EAP7.
=> Exclude errai-cdi-server from EAP 6.4 WARs

kie-wb-tests/.gitignore, kie-wb-tests/README.md, kie-wb-tests/kie-wb-tests-rest/pom.xml, kie-wb-tests/kie-wb-tests-rest/src/main/java/org/kie/wb/test/rest/User.java, kie-wb-tests/kie-wb-tests-rest/src/main/java/org/kie/wb/test/rest/client/NotSuccessException.java, kie-wb-tests/kie-wb-tests-rest/src/main/java/org/kie/wb/test/rest/client/RestWorkbenchClient.java, kie-wb-tests/kie-wb-tests-rest/src/main/java/org/kie/wb/test/rest/client/WorkbenchClient.java, kie-wb-tests/kie-wb-tests-rest/src/main/java/org/kie/wb/test/rest/exception/BadRequestException.java, kie-wb-tests/kie-wb-tests-rest/src/main/java/org/kie/wb/test/rest/exception/ForbiddenException.java, kie-wb-tests/kie-wb-tests-rest/src/main/java/org/kie/wb/test/rest/exception/NotFoundException.java, kie-wb-tests/kie-wb-tests-rest/src/main/java/org/kie/wb/test/rest/exception/RemoteException.java, kie-wb-tests/kie-wb-tests-rest/src/main/java/org/kie/wb/test/rest/exception/UnauthorizedException.java, kie-wb-tests/kie-wb-tests-rest/src/main/java/org/kie/wb/test/rest/util/HttpRequest.java, kie-wb-tests/kie-wb-tests-rest/src/main/java/org/kie/wb/test/rest/util/HttpRequestFactory.java, kie-wb-tests/kie-wb-tests-rest/src/test/java/org/kie/wb/test/rest/RestTestBase.java, kie-wb-tests/kie-wb-tests-rest/src/test/java/org/kie/wb/test/rest/functional/JobIntegrationTest.java, kie-wb-tests/kie-wb-tests-rest/src/test/java/org/kie/wb/test/rest/functional/OrganizationalUnitIntegrationTest.java, kie-wb-tests/kie-wb-tests-rest/src/test/java/org/kie/wb/test/rest/functional/ProjectIntegrationTest.java, kie-wb-tests/kie-wb-tests-rest/src/test/java/org/kie/wb/test/rest/functional/RepositoryIntegrationTest.java, kie-wb-tests/pom.xml, pom.xml
I have taken KIE Workbench REST tests from QE test suite and added many new test cases. Right now, the only container where they can run is Wildfly 8. I have not added support for other containers since it does not make sense for 7.x. Cargo is used to configure and start this container now but it will be replaced as we change KIE Workbench to be able to run independently.
These tests have discovered many potential problems. All of them are described in [GUVNOR-2542](https://issues.jboss.org/browse/GUVNOR-2542) where we can discuss if they really need to be fixed. The reproducers have Jira annotations so you can easily find them in the code. Just comment out this annotation to see the actual behavior since those tests are ignored unless …
=> GUVNOR-2504: Move Guvnor REST tests from QE test suite

kie-config-cli/pom.xml, kie-drools-wb/kie-drools-wb-distribution-wars/pom.xml, kie-wb-tests/kie-wb-tests-gui/pom.xml, kie-wb-tests/kie-wb-tests-rest/pom.xml, kie-wb/kie-wb-distribution-wars/pom.xml
https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/226
https://github.com/droolsjbpm/drools/pull/815
https://github.com/droolsjbpm/optaplanner/pull/200
https://github.com/droolsjbpm/jbpm/pull/487
https://github.com/droolsjbpm/droolsjbpm-integration/pull/509
https://github.com/droolsjbpm/kie-uberfire-extensions/pull/29
https://github.com/droolsjbpm/guvnor/pull/328
https://github.com/droolsjbpm/drools-wb/pull/209
https://github.com/droolsjbpm/jbpm-designer/pull/302
https://github.com/droolsjbpm/jbpm-console-ng/pull/432
https://github.com/droolsjbpm/kie-wb-distributions/pull/303
=> [DROOLS-1216] exclude commons-logging and use jcl-over-slf4j instead

kie-drools-wb/kie-drools-wb-distribution-wars/src/main/assembly/component-kie-drools-wb-tomcat-7-common.xml, kie-drools-wb/kie-drools-wb-distribution-wars/src/main/assembly/component-kie-drools-wb-weblogic-12-common.xml, kie-drools-wb/kie-drools-wb-distribution-wars/src/main/assembly/component-kie-drools-wb-websphere-as-8-common.xml, kie-wb/kie-wb-distribution-wars/src/main/assembly/component-kie-wb-tomcat-7-common.xml, kie-wb/kie-wb-distribution-wars/src/main/assembly/component-kie-wb-weblogic-12-common.xml, kie-wb/kie-wb-distribution-wars/src/main/assembly/component-kie-wb-websphere-as-8-common.xml
* as part of EAP7 WARs work, the uf-ext modules were renamed
from *-wildfly-<version> to *-wildlfy8-<version> and the
exclusion thus did not match those modules which caused issues
mainly on WebLogic
=> [6.5.x] fix uf-security-wildfly exclusions in assembly files

kie-drools-wb/kie-drools-wb-distribution-wars/pom.xml, kie-drools-wb/kie-drools-wb-distribution-wars/src/main/community/assembly-kie-drools-wb-eap-7.xml, kie-wb/kie-wb-distribution-wars/pom.xml, kie-wb/kie-wb-distribution-wars/src/main/community/assembly-kie-wb-eap-7.xml
* the WAR is identical to the WildFly10 one, but uses
different classifier to make it explicit that we support
EAP7 as well
=> Add EAP7 community WAR

kie-drools-wb/kie-drools-wb-distribution-wars/src/main/productized/webapp/logout.jsp, kie-drools-wb/kie-drools-wb-webapp/src/main/webapp/logout.jsp, kie-wb/kie-wb-distribution-wars/src/main/productized/webapp/logout.jsp, kie-wb/kie-wb-webapp/src/main/webapp/logout.jsp
as discussed with @mswiderski; the less risk operation is just add a try catch, so avoid problems on different containers.
=> GUVNOR-2647: proper error handling on logout.jsp, needed when JSM is enabled on EAP

kie-drools-wb/kie-drools-wb-distribution-wars/src/main/productized/webapp/login.jsp, kie-drools-wb/kie-drools-wb-distribution-wars/src/main/productized/webapp/logout.jsp, kie-drools-wb/kie-drools-wb-distribution-wars/src/main/productized/webapp/not_authorized.jsp, kie-drools-wb/kie-drools-wb-webapp/src/main/webapp/login.jsp, kie-drools-wb/kie-drools-wb-webapp/src/main/webapp/logout.jsp, kie-drools-wb/kie-drools-wb-webapp/src/main/webapp/not_authorized.jsp, kie-wb-tests/kie-wb-tests-gui/README.md, kie-wb-tests/kie-wb-tests-gui/src/main/java/org/kie/wb/selenium/model/persps/AbstractPerspective.java, kie-wb-theme/.gitignore, kie-wb-theme/kie-wb-theme-community/.gitignore, kie-wb-theme/kie-wb-theme-product/.gitignore, kie-wb/kie-wb-distribution-wars/src/main/productized/webapp/login.jsp, kie-wb/kie-wb-distribution-wars/src/main/productized/webapp/logout.jsp, kie-wb/kie-wb-distribution-wars/src/main/productized/webapp/not_authorized.jsp, kie-wb/kie-wb-webapp/src/main/webapp/login.jsp, kie-wb/kie-wb-webapp/src/main/webapp/logout.jsp, kie-wb/kie-wb-webapp/src/main/webapp/not_authorized.jsp
See https://issues.jboss.org/browse/RHBPMS-4145
A couple of notable changes:-
- ```login.jsp```, ```logout.jsp``` and ```not_authorized.jsp``` preserve the (Query String) "locale" parameter.
- ```logout.jsp``` correctly redirects to the login page (IIRC @karreiro found this broken too)
- ```.gitignore``` files added for ```kie-wb-theme```
=> RHBPMS-4145: Language selection is not remembered on relogin in Chrome

kie-drools-wb/kie-drools-wb-distribution-wars/src/main/assembly/tomcat7/WEB-INF/web.xml, kie-drools-wb/kie-drools-wb-distribution-wars/src/main/productized/webapp/kie-drools-wb.jsp, kie-drools-wb/kie-drools-wb-distribution-wars/src/main/productized/webapp/logout.jsp, kie-drools-wb/kie-drools-wb-distribution-wars/src/main/productized/webapp/not_authorized.jsp, kie-drools-wb/kie-drools-wb-webapp/pom.xml, kie-drools-wb/kie-drools-wb-webapp/src/main/resources/org/kie/workbench/drools/client/resources/i18n/LoginConstants.properties, kie-drools-wb/kie-drools-wb-webapp/src/main/webapp/WEB-INF/web.xml, kie-drools-wb/kie-drools-wb-webapp/src/main/webapp/kie-drools-wb.jsp, kie-drools-wb/kie-drools-wb-webapp/src/main/webapp/logout.jsp, kie-drools-wb/kie-drools-wb-webapp/src/main/webapp/not_authorized.jsp, kie-wb/kie-wb-distribution-wars/src/main/assembly/tomcat7/WEB-INF/web.xml, kie-wb/kie-wb-distribution-wars/src/main/productized/webapp/kie-wb.jsp, kie-wb/kie-wb-distribution-wars/src/main/productized/webapp/logout.jsp, kie-wb/kie-wb-distribution-wars/src/main/productized/webapp/not_authorized.jsp, kie-wb/kie-wb-webapp/pom.xml, kie-wb/kie-wb-webapp/src/main/resources/org/kie/workbench/client/resources/i18n/LoginConstants.properties, kie-wb/kie-wb-webapp/src/main/webapp/WEB-INF/web.xml, kie-wb/kie-wb-webapp/src/main/webapp/kie-wb.jsp, kie-wb/kie-wb-webapp/src/main/webapp/logout.jsp, kie-wb/kie-wb-webapp/src/main/webapp/not_authorized.jsp
This PR effectively replaces ```kie-wb.html``` and ```kie-drools-wb.html``` with a ```jsp``` equivalent that can handle the i18n of the "Loading" spinner. When merged I'll email BSIG advising that the "start page" (in IDEA) needs to be changed to the ```jsp``` equivalent. The maven configuration has been updated in the PR.
=> RHBPMS-4129: Unlocalized 'Please wait. Loading application...' spinner

kie-drools-wb/kie-drools-wb-webapp/src/main/java/org/kie/workbench/drools/backend/server/LuceneConfigProducer.java, kie-drools-wb/kie-drools-wb-webapp/src/test/java/org/kie/workbench/drools/backend/server/LuceneConfigProducerTest.java, kie-wb-smoke-tests/kie-wb-smoke-tests-main/src/main/java/org/kie/smoke/wb/selenium/model/persps/AdministrationPerspective.java, kie-wb/kie-wb-webapp/src/main/java/org/kie/workbench/backend/LuceneConfigProducer.java, kie-wb/kie-wb-webapp/src/test/java/org/kie/workbench/backend/LuceneConfigProducerTest.java
See https://issues.jboss.org/browse/RHBRMS-2598
Cherry-pick of https://github.com/droolsjbpm/kie-wb-common/pull/471 (of sorts) for 6.5.x (Code changes are similar but had to be applied manually to 6.5.x since it has a different code structure to master).
=> [6.5.x] RHBRMS-2598: Asset search is broken

kie-drools-wb/kie-drools-wb-distribution-wars/src/main/assembly/weblogic12/WEB-INF/web.xml
Fix for [RHBRMS-2580](https://issues.jboss.org/browse/RHBRMS-2580) proposed by @mswiderski. It has been tested with Business Central on WebLogic and really resolves the issue.
=> [6.5.x] RHBRMS-2580 - REST API access control does not work on WebLogic

pom.xml
doesn't replace the apostrophes
=> removed excludes that caused failures of replacer-plugin for french translations

kie-wb/kie-wb-distribution-wars/src/main/assembly/was8/README.md
Hello,
as discussed in [BXMSDOC-847](https://issues.jboss.org/browse/BXMSDOC-847), a property *org.uberfire.start.method* should be added to WAS assembly guide too. What do you think?
Marián
=> Add org.uberfire.start.method property to WAS assembly

pom.xml
Ensure LoginConstants is not processed by replacer plugin
(cherry picked from commit fcd9a08a48882da182638fc6749c062c3b83d87a)
This is the corollary of https://github.com/droolsjbpm/kie-wb-distributions/pull/389 for 6.5.x.
=> [6.5.x] RHBPMS-4129: Unlocalized 'Please wait. Loading application...' spinner

kie-drools-wb/kie-drools-wb-webapp/pom.xml, kie-drools-wb/kie-drools-wb-webapp/src/main/java/org/kie/workbench/drools/client/perspectives/DroolsAuthoringNoContextNavigationPerspective.java, kie-drools-wb/kie-drools-wb-webapp/src/main/java/org/kie/workbench/drools/client/perspectives/DroolsAuthoringPerspective.java, kie-drools-wb/kie-drools-wb-webapp/src/main/resources/org/kie/workbench/drools/KIEDroolsWebapp.gwt.xml, kie-wb/kie-wb-webapp/pom.xml, kie-wb/kie-wb-webapp/src/main/java/org/kie/workbench/client/perspectives/DroolsAuthoringNoContextNavigationPerspective.java, kie-wb/kie-wb-webapp/src/main/java/org/kie/workbench/client/perspectives/DroolsAuthoringPerspective.java, kie-wb/kie-wb-webapp/src/main/resources/org/kie/workbench/KIEWebapp.gwt.xml
Stunner's editor, screens and services Integration into both KIE and Drools workbenches.
- By default the BPMN files are using "bpmn2" as extension, which it's still being used by the jbpm-designer editor.
- The file extensions "bpmn" are now edited by the Stunnerr editor's and other dock screens.
- The title for jbpm-designer resources remains the same -> "Business Process"
- The title for Stunner resources is -> "Business Process (Preview)"
- Both using same resource icon.
- NOTE: Usually there are no ".bpmn" files in our demo repositories, so Stunner should only come into play only when creating a new "Business Process (Preview)" item by scratch.  
See https://issues.jboss.org/browse/JBPM-5387
Depends on https://github.com/droolsjbpm/kie-wb-common/pull/528
Thanks!
=> JBPM-5387: Stunner integration into KIE and Drools Workbenches.

kie-drools-wb/kie-drools-wb-webapp/pom.xml, kie-wb/kie-wb-webapp/pom.xml
Jenkins keeps running OOM when running the full profile GWT build. This started yesterday. I can't reproduce locally (using either profile) but suggest to increase memory of the full profile to match the default profile settings (for now).
@psiroky can you take a look, please?
As a side note, I noticed that we're building 14 different permutations in the full profile. I doubt that this is still necessary, but I need to investigate separately. It seems to me that we can bring the build time down significantly.
=> Increase memory for full profile GWT build

kie-drools-wb/kie-drools-wb-webapp/src/main/resources/org/kie/workbench/drools/client/resources/i18n/LoginConstants_fr.properties, kie-wb/kie-wb-webapp/src/main/resources/org/kie/workbench/client/resources/i18n/LoginConstants_fr.properties
Manual fix for 6.5.x i18n issues.
Zanata needs FR locale translated. Zanata team advised.
I have confirmed fetching i18n from Zanata does not overwrite these changes (since Zanata has no translations for these FR files and hence are skipped by the Maven plugin).
=> Remove escaping of single apostrophe as these i18n files are not used by GWT and hence do not need escaping

kie-wb/kie-wb-webapp/pom.xml
Hey @jlindop , this reverts [this merged commit](https://github.com/droolsjbpm/kie-wb-distributions/pull/412), which brokes the different distribution runtimes. See comments. Could you please verify? Thanks!
=> Stunner - fix wrong class for bpmn-project artifact. It must be provided as it's client side stuff.

kie-drools-wb/kie-drools-wb-webapp/pom.xml, kie-wb/kie-wb-webapp/pom.xml
Dashbuilder was overriding GWT validation instead of using errai-validation. That was causing issues on kie-wb when other components where trying to user Validations.
Fixing validation dependencies to avoid that issue.
Please merge after https://github.com/dashbuilder/dashbuilder/pull/253
=> DASHBUILDE-102: Upgrade dashbuilder-validations to use Errai Validation

kie-wb-tests/pom.xml
So they won't be propagated as transitive dependencies to any project using for example kie-wb-tests-rest artifact.
@jhrcek FYI should solve transitive dependencies issue with kie-wb-tests-rest
=> kie-wb-tests: move distribution wars dependencies to test scope

kie-drools-wb/kie-drools-wb-distribution-wars/src/main/assembly/component-kie-drools-wb-wildfly-10-eap-7-common.xml, kie-drools-wb/kie-drools-wb-distribution-wars/src/main/assembly/wildfly10-eap7/WEB-INF/classes/META-INF/persistence.xml, kie-drools-wb/kie-drools-wb-distribution-wars/src/main/assembly/wildfly10-eap7/WEB-INF/jboss-deployment-structure.xml, kie-wb-smoke-tests/kie-wb-smoke-tests-main/src/main/java/org/kie/smoke/wb/util/handler/AbstractResponseHandler.java, kie-wb/kie-wb-distribution-wars/src/main/assembly/component-kie-wb-wildfly-10-eap-7-common.xml, kie-wb/kie-wb-distribution-wars/src/main/assembly/wildfly10-eap7/WEB-INF/classes/META-INF/persistence.xml, kie-wb/kie-wb-distribution-wars/src/main/assembly/wildfly10-eap7/WEB-INF/jboss-deployment-structure.xml
Upgrading just core Hibernate libraries which seems safe.
Hibernate Validator was not updated as it causes compatibility
issues with javax.validation, Weld and RestEasy.
=> [6.5.x][RHBRMS-2709] use Hibernate 4 in WFLY10/EAP7 WARs

kie-drools-wb/kie-drools-wb-webapp/src/main/resources/security-module-admin.properties, kie-drools-wb/kie-drools-wb-webapp/src/main/resources/security-module-analyst.properties, kie-wb/kie-wb-webapp/src/main/resources/security-module-admin.properties, kie-wb/kie-wb-webapp/src/main/resources/security-module-analyst.properties, kie-wb/kie-wb-webapp/src/main/resources/security-module-developer.properties, kie-wb/kie-wb-webapp/src/main/resources/security-module-manager.properties, kie-wb/kie-wb-webapp/src/main/resources/security-module-user.properties
See https://issues.jboss.org/browse/GUVNOR-2858
This PR adds default permissions reflecting previous state, where only "admin" could download JARs.
=> GUVNOR-2858: Unable to download JAR by Users without admin role

kie-wb/kie-wb-distribution-wars/src/main/productized/webapp/kie-wb.jsp, kie-wb/kie-wb-webapp/src/main/webapp/kie-wb.jsp
Necessary CSS rules moved into GWT CSS resources instead.
=> Remove references for extra css files from jbpm-wb

kie-drools-wb/kie-drools-wb-distribution-wars/src/main/assembly/tomcat8/WEB-INF/web.xml, kie-wb/kie-wb-distribution-wars/src/main/assembly/tomcat8/WEB-INF/web.xml
cc @ederign it indeed seems the order of the execution somehow changed. But I am not exactly sure when that happened, since the Tomcat WARs were broken for ages even before this issue.
There is still one thing I don't understand. The UF clean-up happens basically twice - once directly via the Weld destroy() method and the second time using the DisposableShutdownService. This is something worth taking a look at I think. Ideally the clean-up should happen just once.
=> Tomcat needs specific listener order to avoid UF shutdown issues

kie-drools-wb/kie-drools-wb-webapp/pom.xml, kie-wb/kie-wb-webapp/pom.xml
Added Stunner's SVG support modules and their transitive dependencies. See this [Jira ticket](https://issues.jboss.org/browse/JBPM-5389).
Depends on https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/394
Depends on https://github.com/droolsjbpm/kie-wb-common/pull/691
=> JBPM-5389: Stunner - Added dependencies for the SVG support modules.

kie-drools-wb-parent/kie-drools-wb-webapp/src/main/java/org/kie/workbench/drools/client/perspectives/DroolsAuthoringNoContextNavigationPerspective.java, kie-drools-wb-parent/kie-drools-wb-webapp/src/main/java/org/kie/workbench/drools/client/perspectives/DroolsAuthoringPerspective.java, kie-wb-parent/kie-wb-webapp/src/main/java/org/kie/workbench/client/perspectives/DroolsAuthoringNoContextNavigationPerspective.java, kie-wb-parent/kie-wb-webapp/src/main/java/org/kie/workbench/client/perspectives/DroolsAuthoringPerspective.java
Hey @manstis @mbarkley 
This is the fix for the workbench webapps. Just remove custom docks handler for Stunner and use the shared one.
Depends on https://github.com/droolsjbpm/kie-wb-common/pull/705
Thanks!
=> JBPM-5731: Stunner - Diagram related dock screens only appear on the authoring perspective.

kie-drools-wb-parent/kie-drools-wb-webapp/src/main/webapp/WEB-INF/jboss-deployment-structure.xml, kie-wb-parent/kie-wb-webapp/src/main/webapp/WEB-INF/jboss-deployment-structure.xml
The deleted deps are either not needed or they are
automatically detected by the WildFly.
Some of the dependencies (like javax.faces)  also break deployment
with WildFly Swarm.
=> Clean-up jboss-deployment-structure.xml files

kie-wb/kie-wb-distribution-wars/src/main/assembly/weblogic12/WEB-INF/web-exec-server.xml, kie-wb/kie-wb-distribution-wars/src/main/assembly/weblogic12/WEB-INF/web-ui-server.xml
Removing this reference from WebLogic web.xml:
``` 
<resource-env-ref>		
<description>Object factory for the CDI Bean Manager</description>
<resource-env-ref-name>BeanManager</resource-env-ref-name>
<resource-env-ref-type>javax.enterprise.inject.spi.BeanManager</resource-env-ref-type>
</resource-env-ref>
```
> WLS12c is a fully featured JEE application server and bean manager exists there by default, so this mapping is not needed.
See: https://issues.jboss.org/browse/GUVNOR-2790
=> [6.5.x] GUVNOR-2790: Error happens when Execution server profile is used on Weblogic

kie-drools-wb-parent/kie-drools-wb-webapp/pom.xml, kie-wb-parent/kie-wb-webapp/pom.xml
The -webapps should only depend on what they absolutely need to. That is
usually the just -backend stuff and -client+sources stuff. This is first
wave of the clean-up, removing most of the server-side deps which are
either not needed, or are already brought in transitively.
The removed exclusions are no longer needed
as the artifacts are now excluded directly in the
respective POMs.
=> Clean-up server-side deps in -webapps

kie-wb-parent/kie-wb-home-page-product/src/main/java/org/kie/workbench/client/home/HomeProducer.java
@mbiarnes This should fix compilation for the "product" Home Page.
@dgutierr This was the simplest solution.. please check whether permission is still required.
(cherry picked from commit 65856d4c6e91b2d2a8239b7bcd37548cf0b4bcab)
=> [7.0.x] Remove Dash Boards permission for Product Home Page

kie-drools-wb-parent/kie-drools-wb-webapp/src/main/webapp/WEB-INF/jboss-deployment-structure.xml, kie-wb-parent/kie-wb-webapp/src/main/webapp/WEB-INF/jboss-deployment-structure.xml
Backport of #490. @mswiderski I believe we need this for 7.0.x as well, correct?
=> [GUVNOR-2997] jms-api required by the kie-server-client

kie-wb-parent/kie-wb-home-page-product/src/main/java/org/kie/workbench/client/home/HomeProducer.java
@mbiarnes This should fix compilation for the "product" Home Page.
@dgutierr This was the simplest solution.. please check whether permission is still required.
=> Remove Dash Boards permission for Product Home Page

kie-wb-tests/pom.xml
Forward port of #496 to make the branches in sync.
=> Disable the WB tests (by default) for the productized profile

kie-drools-wb-parent/kie-drools-wb-webapp/pom.xml, kie-wb-parent/kie-wb-webapp/pom.xml
@mbiarnes This moves Swarm's plugin execution to Community only profile.
@psiroky FYI.. there is an issue with Swarm's plugin and Maven classifiers on the WAR ("-redhat" for product)
=> Move Swarm packaging to Community profile

kie-drools-wb-parent/kie-drools-wb-webapp/pom.xml, kie-wb-parent/kie-wb-webapp/pom.xml, pom.xml
@etirelli @tarilabs here are the changes to allow DMN assets to be built and deployed from within workbench - for 7.0.x branch
=> [7.0.x] JBPM-5963 - DMN assets fails to build in workbench

kie-drools-wb/kie-drools-wb-distribution-wars/src/main/assembly/component-kie-drools-wb-tomcat-7-common.xml, kie-drools-wb/kie-drools-wb-distribution-wars/src/main/assembly/component-kie-drools-wb-weblogic-12-common.xml, kie-drools-wb/kie-drools-wb-distribution-wars/src/main/assembly/component-kie-drools-wb-websphere-as-8-common.xml, kie-drools-wb/kie-drools-wb-distribution-wars/src/main/assembly/eap6_4/WEB-INF/jboss-deployment-structure.xml, kie-drools-wb/kie-drools-wb-distribution-wars/src/main/assembly/wildfly10-eap7/WEB-INF/jboss-deployment-structure.xml, kie-drools-wb/kie-drools-wb-webapp/pom.xml, kie-drools-wb/kie-drools-wb-webapp/src/main/webapp/WEB-INF/jboss-deployment-structure.xml, kie-wb/kie-wb-distribution-wars/src/main/assembly/component-kie-wb-tomcat-7-common.xml, kie-wb/kie-wb-distribution-wars/src/main/assembly/component-kie-wb-weblogic-12-common.xml, kie-wb/kie-wb-distribution-wars/src/main/assembly/component-kie-wb-websphere-as-8-common.xml, kie-wb/kie-wb-distribution-wars/src/main/assembly/eap6_4/WEB-INF/jboss-deployment-structure.xml, kie-wb/kie-wb-distribution-wars/src/main/assembly/wildfly10-eap7/WEB-INF/jboss-deployment-structure.xml, kie-wb/kie-wb-webapp/pom.xml, kie-wb/kie-wb-webapp/src/main/webapp/WEB-INF/jboss-deployment-structure.xml
The private EAP module jcl-over-slf4j was removed in EAP 7.0.6 which
broke the deployment.
@AntStephenson could you please review?
=> [6.5.x]  Add jcl-over-slf4j directly into WEB-INF/lib

kie-wb-parent/kie-wb-webapp/pom.xml
Adds new dependency introduced by:
JBPM-5736: Update taskforms component menu on task/process change.
JBPM-5985: Forms are generated incorrectly after a removal of the process/task variable.
JBPM-5723: If you delete a data field, there is no response in the form connected to it.
JBPM-5911: DatePicker should be created from LocalDate, LocalDateTime and OffsetDateTime data types.
@manstis @jsoltes could you take a look?
Relates to:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/465
https://github.com/kiegroup/kie-wb-common/pull/946
https://github.com/kiegroup/jbpm-designer/pull/627
https://github.com/kiegroup/jbpm-wb/pull/778
https://github.com/kiegroup/jbpm-designer/pull/633
=> JBPM-5736, JBPM-5985, JBPM-5723 & JBPM-5911 Form synchronization when model changes

kie-wb-tests/kie-wb-tests-rest/src/main/java/org/kie/wb/test/rest/client/RestWorkbenchClient.java, kie-wb-tests/kie-wb-tests-rest/src/main/java/org/kie/wb/test/rest/client/WorkbenchClient.java
To simplify Workbench client usage - users don't need to create model instances.
=> Extend workbench client creation methods

kie-drools-wb-parent/kie-drools-wb-distribution-wars/src/main/assembly/tomcat8/WEB-INF/web.xml, kie-drools-wb-parent/kie-drools-wb-webapp/src/main/webapp/WEB-INF/web.xml, kie-wb-parent/kie-wb-distribution-wars/src/main/assembly/tomcat8/WEB-INF/web.xml, kie-wb-parent/kie-wb-webapp/src/main/webapp/WEB-INF/web.xml
WildFly adds the "no-cache" header to secured resources, preventing them from being cached. I have added *.cache.js files and many other static resources as public so that they can be cached.
I applied the same changes to the other application server configs for consistency. I do not know whether they suffered from the same issue.
Not sure who is best to review this. @psiroky @manstis?
=> AF-546: Make cacheable resources public to avoid non-caching headers.

kie-drools-wb-parent/kie-drools-wb-webapp/src/main/java/org/kie/workbench/drools/client/KieDroolsWorkbenchEntryPoint.java, kie-drools-wb-parent/kie-drools-wb-webapp/src/test/java/org/kie/workbench/drools/client/KieDroolsWorkbenchEntryPointTest.java, kie-wb-parent/kie-wb-webapp/src/main/java/org/kie/workbench/client/KieWorkbenchEntryPoint.java, kie-wb-parent/kie-wb-webapp/src/test/java/org/kie/workbench/client/KieWorkbenchEntryPointTest.java
Depends on: https://github.com/dashbuilder/dashbuilder/pull/362
=> [7.3.x] GUVNOR-3423: Navigation Editor should not allow root menu items and dividers

kie-drools-wb-parent/kie-drools-wb-webapp/pom.xml, kie-wb-parent/kie-wb-monitoring-webapp/pom.xml, kie-wb-parent/kie-wb-webapp/pom.xml
Move most backend dependencies to runtime scope, removing it from the GWT compiler classpath
=> JBPM-6376 - Review GWT compiler classpath

kie-drools-wb-parent/kie-drools-wb-webapp/pom.xml, kie-wb-parent/kie-wb-monitoring-webapp/pom.xml, kie-wb-parent/kie-wb-webapp/pom.xml
Move most backend dependencies to runtime scope, removing it from the GWT compiler classpath
=> [7.3.x] JBPM-6376 - Review GWT compiler classpath

kie-wb-tests/kie-wb-tests-gui/src/test/java/org/kie/wb/selenium/ui/StandalonePerspectivesIntegrationTest.java
Hello @manstis,
This is the standalone Authoring Perspective test we talked about. Could you please have a look? Let me know if there is anything more you would like to test; now the test only checks whether the perspective was loaded and based on the `header` parameter in the URL, the test checks whether the `AppNavBar` is there.
Also, on which branches do you want to have this test?
=> Add standalone Authoring Perspective test.

kie-drools-wb-parent/kie-drools-wb-webapp/src/main/java/org/kie/workbench/drools/client/KieDroolsWorkbenchEntryPoint.java, kie-drools-wb-parent/kie-drools-wb-webapp/src/test/java/org/kie/workbench/drools/client/KieDroolsWorkbenchEntryPointTest.java, kie-wb-parent/kie-wb-webapp/src/main/java/org/kie/workbench/client/KieWorkbenchEntryPoint.java, kie-wb-parent/kie-wb-webapp/src/test/java/org/kie/workbench/client/KieWorkbenchEntryPointTest.java
@ederign can you please review and merge?
These changes are required in order to fix the nav config of the Workbench tree used by the Mega menu. It is part of the changes related to the new navigation features.
=> JBPM-6432: Mega menu navigation configuration settings

kie-wb-webapp-common/src/main/webapp/META-INF/jboss-deployment-structure.xml
jboss-sasl was replaced by wildfly-elytron in WildFly 11 / EAP 7.1+.
It was also a private module, so were warned. From now on the
wildfly-elytron will be bundled directly inside the WAR (WEB-INF/lib) to
avoid the same issue again in future.
@romartin could you please approve? Same changes as in #627, but for 7.3.x builds.
Depends on https://github.com/AppFormer/uberfire/pull/855
=> [7.3.x][JBPM-6458] remove dependency on jboss-sasl module

kie-wb-webapp-common/src/main/webapp/META-INF/jboss-deployment-structure.xml
jboss-sasl was replaced by wildfly-elytron in WildFly 11 / EAP 7.1+.
It was also a private module, so were warned. From now on the
wildfly-elytron will be bundled directly inside the WAR (WEB-INF/lib) to
avoid the same issue again in future.
Depends on https://github.com/AppFormer/uberfire/pull/854
=> [JBPM-6458] remove dependency on jboss-sasl module

kie-drools-wb-parent/kie-drools-wb-webapp/pom.xml, kie-wb-parent/kie-wb-monitoring-webapp/pom.xml, kie-wb-parent/kie-wb-webapp/pom.xml
Related:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/541
https://github.com/kiegroup/droolsjbpm-knowledge/pull/263
https://github.com/kiegroup/drools/pull/1444
https://github.com/kiegroup/jbpm/pull/973
https://github.com/kiegroup/droolsjbpm-integration/pull/1163
https://github.com/kiegroup/kie-wb-common/pull/1133
https://github.com/kiegroup/drools-wb/pull/596
https://github.com/kiegroup/jbpm-designer/pull/654
https://github.com/kiegroup/jbpm-wb/pull/864
https://github.com/kiegroup/optaplanner-wb/pull/218
https://github.com/kiegroup/droolsjbpm-tools/pull/82
=> AF-593: Decouple kie-wb-common-datamodel from Drools

kie-drools-wb-parent/kie-drools-wb-webapp/src/main/java/org/kie/workbench/drools/client/KieDroolsWorkbenchEntryPoint.java, kie-drools-wb-parent/kie-drools-wb-webapp/src/main/java/org/kie/workbench/drools/client/navigation/NavTreeDefinitions.java, kie-drools-wb-parent/kie-drools-wb-webapp/src/main/java/org/kie/workbench/drools/client/resources/i18n/NavigationConstants.java, kie-drools-wb-parent/kie-drools-wb-webapp/src/main/resources/org/kie/workbench/drools/client/resources/i18n/NavigationConstants.properties, kie-drools-wb-parent/kie-drools-wb-webapp/src/test/java/org/kie/workbench/drools/client/KieDroolsWorkbenchEntryPointTest.java, kie-drools-wb-parent/kie-drools-wb-webapp/src/test/java/org/kie/workbench/drools/client/navigation/NavTreeDefinitionsTest.java, kie-wb-parent/kie-wb-monitoring-webapp/src/main/java/org/kie/workbench/client/navigation/NavTreeDefinitions.java, kie-wb-parent/kie-wb-monitoring-webapp/src/main/java/org/kie/workbench/client/resources/i18n/NavigationConstants.java, kie-wb-parent/kie-wb-monitoring-webapp/src/main/resources/org/kie/workbench/client/resources/i18n/NavigationConstants.properties, kie-wb-parent/kie-wb-monitoring-webapp/src/test/java/org/kie/workbench/client/KieWorkbenchEntryPointTest.java, kie-wb-parent/kie-wb-webapp/src/main/java/org/kie/workbench/client/KieWorkbenchEntryPoint.java, kie-wb-parent/kie-wb-webapp/src/main/java/org/kie/workbench/client/navigation/NavTreeDefinitions.java, kie-wb-parent/kie-wb-webapp/src/main/java/org/kie/workbench/client/resources/i18n/NavigationConstants.java, kie-wb-parent/kie-wb-webapp/src/main/resources/org/kie/workbench/client/resources/i18n/NavigationConstants.properties, kie-wb-parent/kie-wb-webapp/src/test/java/org/kie/workbench/client/KieWorkbenchEntryPointTest.java, kie-wb-tests/kie-wb-tests-gui/src/main/java/org/kie/wb/selenium/model/PrimaryNavbar.java
The CMS perspective design changes requires to adjust the initialization of the default navigation tree configuration. As the following screenshot shows, only a default nav tree entry is available which corresponds to the workbench's top menu bar configuration:
@ederign @kkufova Can you guys review and approve please?
Depends on https://github.com/dashbuilder/dashbuilder/pull/376
=> DASHBUILDE-252: CMS perspective UI redesign

kie-drools-wb-parent/kie-drools-wb-webapp/pom.xml, kie-wb-parent/kie-wb-monitoring-webapp/pom.xml, kie-wb-parent/kie-wb-webapp/pom.xml, pom.xml
Please see this [PR](https://github.com/kiegroup/kie-soup/pull/8) for general discussion.
=> AF-593+: Move uberfire-maven-utils to kie-soup.

kie-drools-wb-parent/kie-drools-wb-webapp/pom.xml, kie-wb-parent/kie-wb-monitoring-webapp/pom.xml, kie-wb-parent/kie-wb-webapp/pom.xml
A new Metadata index had been added. Its intention is to have an alternative to Lucene backend so you can use it, for instance in Openshift or on premise without zookeeper/helix to replicate those assets.
The idea is to maintain the same Lucene API but to transform it to Elasticsearch compatible messages. There is no need to change any Lucene Query to make it work. There is a class called **LuceneIndexEngine** that is not **public** anymore because it was very coupled to Lucene FS implementation so now it's behind a new Interface called **IndexProvider**. It tries to generate an abstraction for indexing a querying an index engine using domain objects and not lucene documents anymore.
The default indexing engine is Lucene but you can change it with a System Property:
- …
=> [AF-549-elastic]: Added new indexing backend to add elasticsearch support

pom.xml
Fixing the following warnings:
```
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.kie:kie-wb-theme:pom:7.5.0-SNAPSHOT
[WARNING] 'dependencyManagement.dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.kie.soup:kie-soup-bom:pom -> duplicate declaration of version ${version.org.kie} @ org.kie:kie-wb-distributions:[unknown-version], /home/hrk/Devel/github.com/jhrcek/kie-wb-distributions/pom.xml, line 92, column 19
[WARNING] 
[WARNING] Some problems were encountered while building the effective model for org.kie:kie-wb-distributions:pom:7.5.0-SNAPSHOT
[WARNING] 'dependencyManagement.dependencies.dependency.(groupId:artifactId:type:classifier)' must be unique: org.kie.soup:kie-soup-bom:pom -> duplicate declaration …
```
=> Remove duplicated dependencies

kie-drools-wb-parent/kie-drools-wb-webapp/pom.xml, kie-wb-parent/kie-wb-webapp/pom.xml
This dependency should not be here. If it is needed it should be
declared by the module that actually needs it (e.g. the
jbpm-designer-backed).
=> Remove bogus batik-ext dependency

kie-wb-parent/kie-wb-monitoring-webapp/pom.xml, kie-wb-parent/kie-wb-webapp/pom.xml
Before this fix gwtbootstrap3-extras jar ended up in WEB-INF/lib of both kie-wb and kie-wb-monitoring (in kie-drools-wb it's already declared as provided so that war doesn't have this problem).
@cristianonicolai can you please check and merge?
=> Prevent gwtbootstrap3-extras ending up in WARs

kie-drools-wb-parent/kie-drools-wb-webapp/pom.xml, kie-wb-parent/kie-wb-webapp/pom.xml
Hey @manstis @jomarko @hasys 
It cleans the use of the `BasicSet` artifacts from the workbenches.
This commit **depends on**
https://github.com/kiegroup/kie-wb-common/pull/1362
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/672
https://github.com/kiegroup/jbpm-wb/pull/971/
Thanks!
=> JBPM-6748: Removed Stunner's BasicSet dependencies from the webapps

kie-wb-parent/kie-wb-webapp/pom.xml, kie-wb-parent/kie-wb-webapp/src/main/resources/org/kie/workbench/FastCompiledKIEWebappWithSourcemaps.gwt.xml
I'm trying to enable source map debugging in production compiled kie-wb.war (so far I'm trying to get it directly to kie-wb. Later I'm going to split this into separate profile to be enabled on demand only).
I'm stealing inspiration from Max who enabled it in [errai demo](https://github.com/errai/errai-tutorial/commit/d79aee98fae5c3041617e2e4ba24e056a3490840). 
The first commit in the PR makes gwt compiler source maps in  `./kie-wb-parent/kie-wb-webapp/target/extra/org.kie.workbench.KIEWebapp/...`
I'm struggling with the second step: ensure those sourcemaps are copied to final kie-wb-VERSION-eap7.war @manstis @mbarkley could you please give me a hint how to achieve that? I've no idea which module should have this "copy sourcemaps to war" configuration (also not sure if this should be done …
=> Add "sourcemaps" profile to include source maps in kie-wb war

kie-wb-parent/kie-wb-webapp/pom.xml, kie-wb-parent/kie-wb-webapp/src/main/resources/org/kie/workbench/FastCompiledKIEWebappWithSourcemaps.gwt.xml
Despite 7.5.x branch being in "blockers only" mode, I'd still like to kindly as for this to be merged,  since this change :
- doesn't affect normal build at all (you need to enable `-Psourcemaps` for it to have any effect)
- would be really helpful for QE's troubleshooting of mysterious UI bugs (that this version abounds in)
=> [7.5.x] Add "sourcemap" profile to enable sourcemap debugging of kie-wb war

kie-drools-wb-parent/kie-drools-wb-webapp/pom.xml, kie-wb-parent/kie-wb-webapp/pom.xml
@porcelli could you review?
https://issues.jboss.org/browse/RHDM-349
Related to:
https://github.com/kiegroup/optaplanner-wb/pull/250
https://github.com/kiegroup/drools-wb/pull/799
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/692
https://github.com/kiegroup/kie-wb-distributions/pull/685
https://github.com/kiegroup/kie-wb-playground/pull/46
https://github.com/kiegroup/jbpm-wb/pull/980
https://github.com/kiegroup/kie-wb-common/pull/1411
=> RHDM-349: Added new drools-playground dependency

kie-drools-wb-parent/kie-drools-wb-distribution-wars/pom.xml, kie-drools-wb-parent/kie-drools-wb-distribution-wars/src/main/assembly/component-kie-drools-wb-swarm-common.xml, kie-drools-wb-parent/kie-drools-wb-distribution-wars/src/main/productized/assembly-kie-drools-wb-swarm-redhat.xml, kie-wb-parent/kie-wb-distribution-wars/kie-wb/pom.xml, kie-wb-parent/kie-wb-distribution-wars/src/main/assembly/component-kie-wb-swarm-common.xml, kie-wb-parent/kie-wb-distribution-wars/src/main/productized/assembly-kie-wb-swarm-redhat.xml
(cherry picked from commit dd1a811ee6a2e87cf6f91a3d190afd32d9c9921c)
https://issues.jboss.org/browse/RHDM-344
https://issues.jboss.org/browse/DROOLS-2314
Bundle:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/708
https://github.com/kiegroup/kie-wb-distributions/pull/689
=> [7.5.x] DROOLS-2314 : Standalone decision central is not branded

kie-wb-tests/kie-wb-tests-gui/src/main/java/org/kie/wb/selenium/model/KieSeleniumTest.java, kie-wb-tests/kie-wb-tests-gui/src/main/java/org/kie/wb/selenium/model/KieWbDistribution.java, kie-wb-tests/kie-wb-tests-gui/src/main/java/org/kie/wb/selenium/model/LoginPage.java, kie-wb-tests/kie-wb-tests-gui/src/main/java/org/kie/wb/selenium/model/PrimaryNavbar.java, kie-wb-tests/kie-wb-tests-gui/src/main/java/org/kie/wb/selenium/model/persps/ProjectLibraryPerspective.java, kie-wb-tests/kie-wb-tests-gui/src/main/java/org/kie/wb/selenium/model/persps/authoring/ImportProjectsScreen.java, kie-wb-tests/kie-wb-tests-gui/src/main/java/org/kie/wb/selenium/util/ScreenshotOnFailure.java, kie-wb-tests/kie-wb-tests-gui/src/main/java/org/kie/wb/selenium/util/Waits.java, kie-wb-tests/kie-wb-tests-gui/src/test/java/org/kie/wb/selenium/ui/LoadAllPerspectivesIntegrationTest.java, kie-wb-tests/kie-wb-tests-gui/src/test/java/org/kie/wb/selenium/ui/LoginIntegrationTest.java, kie-wb-tests/kie-wb-tests-gui/src/test/java/org/kie/wb/selenium/ui/ProjectLibraryIntegrationTest.java, kie-wb-tests/kie-wb-tests-gui/src/test/java/org/kie/wb/selenium/ui/StandalonePerspectivesIntegrationTest.java
@paulovmr ProjectLibraryIntegrationTest is failing now on master after project oriented has been merged. The root cause is the change in behaviour in Project Import screen:
- previously after selecting projects in import screen and clicking OK the app automatically moved to Project List.
- current behaviour (seems broken): after clicking OK, the app stays in the list of projects to import. Is this reported/should I report it?
Also fixed the issue with screenshot on failure showing login screen (we must not put logout into `@After` methods) and did a general code cleanup in selenium module.
@manstis @karreiro FYI this is the fix of selenium tests as promised yesterday. Let me retest this few times to confirm stability..
=> Update selenium tests after the merge of project oriented

kie-wb-tests/kie-wb-tests-gui/src/main/java/org/kie/wb/selenium/model/Persp.java, kie-wb-tests/kie-wb-tests-gui/src/test/java/org/kie/wb/selenium/ui/ProjectLibraryIntegrationTest.java
This PR is related to this one: https://github.com/kiegroup/kie-wb-playground/pull/49 (_Make example project names consistent._) These two PRs should be merged together to prevent the community Selenium tests from failing.
@jhrcek, @manstis, could you please review?
=> Stabilize community Selenium tests.

kie-wb-tests/kie-wb-tests-gui/src/main/java/org/kie/wb/selenium/model/Persp.java
This perspective has been disabled in kie-drools-wb in 7.5.x
in 663add1d1a903845b08af6d7fae21d82dae533b3
because it was not stable - so this commit removes it from UI tests as well.
@mbiarnes FYI this should fix the failing [failing UI test](https://kie-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/view/kieAllBuild-7.5.x/job/kieWbTestsMatrix-kieAllBuild-7.5.x/lastCompletedBuild/testReport/) (not the others).
=> [7.5.x] Disable Pages perspective in kie-drools-wb tests

kie-wb-tests/kie-wb-tests-gui/README.md, kie-wb-tests/kie-wb-tests-gui/src/main/java/org/kie/wb/selenium/model/Persp.java, kie-wb-tests/kie-wb-tests-gui/src/main/java/org/kie/wb/selenium/model/persps/ExecutionErrorsPerspective.java, kie-wb-tests/kie-wb-tests-gui/src/main/java/org/kie/wb/selenium/model/persps/JobsPerspective.java, kie-wb-tests/kie-wb-tests-gui/src/main/java/org/kie/wb/selenium/model/persps/ProcessDashboardPerspective.java, kie-wb-tests/kie-wb-tests-gui/src/main/java/org/kie/wb/selenium/model/persps/ProcessDefinitionsPerspective.java, kie-wb-tests/kie-wb-tests-gui/src/main/java/org/kie/wb/selenium/model/persps/ProcessInstancesPerspective.java, kie-wb-tests/kie-wb-tests-gui/src/main/java/org/kie/wb/selenium/model/persps/TaskAdminPerspective.java, kie-wb-tests/kie-wb-tests-gui/src/main/java/org/kie/wb/selenium/model/persps/TaskDashboardPerspective.java, kie-wb-tests/kie-wb-tests-gui/src/main/java/org/kie/wb/selenium/model/persps/TasksPerspective.java, kie-wb-tests/kie-wb-tests-gui/src/test/java/org/kie/wb/selenium/ui/ProjectLibraryIntegrationTest.java, kie-wb-tests/kie-wb-tests-gui/src/test/java/org/kie/wb/selenium/ui/StandalonePerspectivesIntegrationTest.java
@manstis Fixing broken selenium tests
1. Recent [jbpm-wb changes](https://github.com/kiegroup/jbpm-wb/pull/994) broke `LoadAllPerspectivesIntegrationTest` - updating locators to reflect those changes (@cristianonicolai FYI)
2. `StandalonePerspectivesIntegrationTest` now started failing because of  [RHBA-503](https://issues.jboss.org/browse/RHBA-503) - added `@Ignore` annotation until it's fixed
3. `ProjectLibraryIntegrationTest#importAndBuildProjectFromCustomRepository` is broken because of [RHBA-581](https://issues.jboss.org/browse/RHBA-581) - added `@Ignore` annotation until it's fixed
=> Fix selenium tests

kie-drools-wb-parent/kie-drools-wb-webapp/pom.xml, kie-wb-parent/kie-wb-webapp/pom.xml
Hey @hasys @jomarko 
This removes the use on the workbench of some unused services from Stunner.
It **depends on**
https://github.com/kiegroup/kie-wb-common/pull/1509
https://github.com/kiegroup/jbpm-wb/pull/996
Thanks!
=> JBPM-5649: Removed dependency to Stunner's default backend services.

kie-wb-tests/kie-wb-tests-gui/src/test/java/org/kie/wb/selenium/ui/ProjectLibraryIntegrationTest.java
@manstis could you please merge if the tests pass?
Helping @mbiarnes  with selenium failures troubleshooting on 7.5.x on tomcat8.
It's necessary not to use `@After` in selenium tests, because `ScreenshotOnFailure` `TestWatcher` just captures useless screenshot of the login screen when test fails. Also logout after test is unnecessary (that logout works is already tested in `LoginIntegrationTest`).
The added `@Page` annotation ensures that `home` field is initialized in cases when some previous test already logged into the app.
=> Remove @After in UI test to make screenshots useful

kie-wb-tests/kie-wb-tests-rest/src/main/java/org/kie/wb/test/rest/client/RestWorkbenchClient.java
Add sleep for a while to avoid random failing tests.
=> Add sleepForSecond to the waitUntilJobFinished because of RHPAM-863

kie-wb-tests/kie-wb-tests-rest/src/main/java/org/kie/wb/test/rest/client/RestWorkbenchClient.java
Add sleep for a while to avoid random failing tests.
=> [7.7.x] Add sleepForSecond to the waitUntilJobFinished because of RHPAM-863

kie-drools-wb-parent/kie-drools-wb-webapp/pom.xml, kie-wb-parent/kie-wb-monitoring-webapp/pom.xml, kie-wb-parent/kie-wb-webapp/pom.xml
The interceptor API is needed during GWT compilation. It used to be
transitively provided by uberfire-security-api. Relying on transitive
dependencies is a bad practice though.
Please merge ASAP because the interceptor API is no longer provided (as a result of dependency cleanup in AppFormer kiegroup/appformer/pull/378) which causes a build failure.
=> Declare dependency on javax.interceptor

pom.xml
This is for fixing the productizedProfile build error. the org.kie.kie-wb wildfly11 war doesn't exist for productized Profile.
=> Make jBPM server Distribution for community only

kie-drools-wb-parent/kie-drools-wb-webapp/src/main/java/org/kie/workbench/drools/client/KieDroolsWorkbenchEntryPoint.java, kie-drools-wb-parent/kie-drools-wb-webapp/src/test/java/org/kie/workbench/drools/client/KieDroolsWorkbenchEntryPointTest.java, kie-wb-parent/kie-wb-monitoring-webapp/src/main/java/org/kie/workbench/client/KieWorkbenchEntryPoint.java, kie-wb-parent/kie-wb-monitoring-webapp/src/test/java/org/kie/workbench/client/KieWorkbenchEntryPointTest.java, kie-wb-parent/kie-wb-webapp/src/main/java/org/kie/workbench/client/KieWorkbenchEntryPoint.java, kie-wb-parent/kie-wb-webapp/src/test/java/org/kie/workbench/client/KieWorkbenchEntryPointTest.java
This is already merged in 7.7.x. Cherry-picking to master.
Related:
https://github.com/errai/errai/pull/352
https://github.com/kiegroup/appformer/pull/412
https://github.com/kiegroup/kie-wb-common/pull/1951
https://github.com/kiegroup/drools-wb/pull/883
https://github.com/kiegroup/jbpm-wb/pull/1169
https://github.com/kiegroup/optaplanner-wb/pull/290
https://github.com/kiegroup/kie-wb-distributions/pull/776
=> [master] AF-1226: Improve error handling displaying additional info to the GenericErrorPopup

kie-drools-wb-parent/kie-drools-wb-webapp/pom.xml
fullProfile has too few memory and throws  OutOfMemoryError from times to times.
After this change it will use "default" profile with 6g instead of 4g.
See an example of failed build there: https://kie-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/kie-wb-common-downstream-pullrequests/1337/console
=> Memory allocation to avoid OutOfMemoryError

kie-wb-tests/kie-wb-tests-rest/src/main/java/org/kie/wb/test/rest/client/ClientRequestTimedOutException.java, kie-wb-tests/kie-wb-tests-rest/src/main/java/org/kie/wb/test/rest/client/RestWorkbenchClient.java, kie-wb-tests/kie-wb-tests-rest/src/test/java/org/kie/wb/test/rest/RestTestBase.java, kie-wb-tests/kie-wb-tests-rest/src/test/java/org/kie/wb/test/rest/functional/JobIntegrationTest.java, kie-wb-tests/kie-wb-tests-rest/src/test/java/org/kie/wb/test/rest/functional/ProjectIntegrationTest.java, kie-wb-tests/kie-wb-tests-rest/src/test/java/org/kie/wb/test/rest/functional/SpaceIntegrationTest.java, kie-wb-tests/kie-wb-tests-rest/src/test/java/org/kie/wb/test/rest/functional/TroubleshootRestSetupIssueIntegrationTest.java, kie-wb-tests/kie-wb-tests-rest/src/test/java/org/kie/wb/test/rest/security/ProjectAccessIntegrationTest.java, kie-wb-tests/kie-wb-tests-rest/src/test/resources/logback-test.xml
Hello @Rikkola,
please check this. Troubleshooting instabilities in REST tests as discussed in email. The `@AfterClass` has been failing very often recently with similar errors:
```
org.kie.wb.test.rest.client.NotSuccessException: APPROVED: null
at org.kie.wb.test.rest.client.RestWorkbenchClient.waitUntilJobFinished(RestWorkbenchClient.java:333)
at org.kie.wb.test.rest.client.RestWorkbenchClient.waitUntilJobFinished(RestWorkbenchClient.java:303)
at org.kie.wb.test.rest.client.RestWorkbenchClient.deleteSpace(RestWorkbenchClient.java:255)
at org.kie.wb.test.rest.RestTestBase.deleteAllProject(RestTestBase.java:120)
at org.kie.wb.test.rest.RestTestBase.cleanUp(RestTestBase.java:73)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at …
```
=> Troubleshoot flaky cleanup in workbench rest tests

kie-wb-tests/pom.xml
Based on discussion on bsig-all I'm disabling workbench integration tests with tomcat (they'll still run with eap7 and wildfly11 without change). At the moment these tests are pretty much [broken with tomcat](https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/dailyBuild/job/kieWbTestsMatrix-kieAllBuild-master/). QE is literally ignoring workbench testing with tomcat (as it's not supported in the product). @mbiarnes already created [related PR](https://github.com/kiegroup/kie-jenkins-scripts/pull/311) removing tomcat from container matrix.
Please let me know if you find this change acceptable: @krisv @Rikkola @porcelli
=> Don't test kie-(drools-)wb on tomcat

kie-wb-tests/kie-wb-tests-gui/src/main/java/org/kie/wb/selenium/model/persps/ExecutionErrorsPerspective.java, kie-wb-tests/kie-wb-tests-gui/src/main/java/org/kie/wb/selenium/model/persps/JobsPerspective.java, kie-wb-tests/kie-wb-tests-gui/src/main/java/org/kie/wb/selenium/model/persps/ProcessDashboardPerspective.java, kie-wb-tests/kie-wb-tests-gui/src/main/java/org/kie/wb/selenium/model/persps/ProcessDefinitionsPerspective.java, kie-wb-tests/kie-wb-tests-gui/src/main/java/org/kie/wb/selenium/model/persps/ProcessInstancesPerspective.java, kie-wb-tests/kie-wb-tests-gui/src/main/java/org/kie/wb/selenium/model/persps/TaskAdminPerspective.java, kie-wb-tests/kie-wb-tests-gui/src/main/java/org/kie/wb/selenium/model/persps/TaskDashboardPerspective.java, kie-wb-tests/kie-wb-tests-gui/src/main/java/org/kie/wb/selenium/model/persps/TasksPerspective.java
`LoadAllPerspectivesIntegrationTest` started to [fail on master](https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/deployedRep/job/kie-wb-distributions/) with `Perspective Process Definitions should be loaded`. The root cause: jquery locator used to detect that the perspective was loaded was no longer valid - css class name was changed in https://github.com/kiegroup/appformer/pull/437 (CC @paulovmr). This PR fixes the test by updating the locator. 
Thanks to @domhanak for pointing this failure out to me
=> Update breadcrumb locator in selenium tests

kie-drools-wb-parent/kie-drools-wb-webapp/pom.xml, kie-wb-parent/kie-wb-webapp/pom.xml
https://issues.jboss.org/browse/DROOLS-2846
https://issues.jboss.org/browse/DROOLS-2847
Pretty much just moving code for the 99% of the changes and then 1% of refactorings to make the move easier.
Bundle:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/800
https://github.com/kiegroup/drools/pull/2021
https://github.com/kiegroup/kie-wb-common/pull/2054
https://github.com/kiegroup/drools-wb/pull/916
https://github.com/kiegroup/optaplanner-wb/pull/301
https://github.com/kiegroup/kie-wb-distributions/pull/795
=> DROOLS-2846 : Move Verifier core from drools-wb to drools

kie-wb-tests/pom.xml
Now that Paulo fixed the problem with overriding system properties in https://github.com/kiegroup/appformer/pull/467 I'm disabling incremental build using system property given in cargo container configuration used by workbench rest tests as well as by selenium tests.
=> Disable incremental build in workbench rest / selenium tests

kie-drools-wb-parent/kie-drools-wb-webapp/pom.xml, kie-drools-wb-parent/kie-drools-wb-webapp/src/main/webapp/WEB-INF/web.xml, kie-wb-parent/kie-wb-webapp/pom.xml, kie-wb-parent/kie-wb-webapp/src/main/webapp/WEB-INF/web.xml
Follow up for: https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/800
https://issues.jboss.org/browse/DROOLS-2848
https://issues.jboss.org/browse/DROOLS-2849
Bundle:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/809
https://github.com/kiegroup/kie-wb-common/pull/2073
https://github.com/kiegroup/drools-wb/pull/919
https://github.com/kiegroup/optaplanner-wb/pull/302
https://github.com/kiegroup/kie-wb-distributions/pull/802
=> DROOLS-2848 : Make the Verifier Web Worker connector reusable for different V&V types

kie-wb-tests/kie-wb-tests-gui/README.md, kie-wb-tests/kie-wb-tests-gui/pom.xml, kie-wb-tests/kie-wb-tests-gui/src/main/java/org/kie/wb/selenium/model/persps/HomePerspective.java
The root cause of these timeouts is the time it takes to download and execute the 23MB main workbench javascript file (compiled from GWT).
Even on my overpowered laptop the initial load of the home page takes ~13 seconds, so the default 15s home page loading timeout is unreasonably small.
Bumping the default to 30 seconds and adding log message so we can check later how slow the loading was.
=> Prevent home page loading timeouts in selenium tests

kie-wb-tests/pom.xml
@toni @ederign @cristianonicolai this fixes the [integration test failure](https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/7.11.x/job/dailyBuild/job/kieWbTestsMatrix-kieAllBuild-7.11.x/lastCompletedBuild/browser=firefox,container=eap7,jdk=kie-jdk1.8,label_exp=kie-linux&&kie-mem8g&&gui-testing,war=kie-wb/testReport/org.kie.wb.test.rest.functional/RepositoryIntegrationTest/testCloneRepositoryInternal/) that @mbiarnes emailed us about.
The root cause was that the tests initialized [org.uberfire.nio.git.daemon.port to null](https://github.com/kiegroup/kie-wb-distributions/blob/master/kie-wb-tests/kie-wb-tests-rest/src/test/java/org/kie/wb/test/rest/RestTestBase.java#L48) because eap7 container profile in the pom wasn't setting `cargo.git.port` property (fixed in this PR) …
=> Fix RepositoryIntegrationTest when running tests with eap7 container profile

kie-server-distributions/pom.xml
kie-server-distributions overrides 'version.org.wildfly' defined in kie-parent from '14.0.1.Final' to the same version '14.0.1.Final'
This override is unnecessary and will require changes in more places when we update wildfly in the future (or will be forgotten and will cause inconsistencies).
@cristianonicolai please check and consider merging
=> Remove useless property override

business-central-tests/business-central-tests-gui/src/main/java/org/kie/wb/selenium/model/persps/ProcessDashboardPerspective.java, business-central-tests/business-central-tests-gui/src/main/java/org/kie/wb/selenium/model/persps/ProcessInstancesPerspective.java, business-central-tests/business-central-tests-gui/src/main/java/org/kie/wb/selenium/model/persps/TaskDashboardPerspective.java, business-central-tests/business-central-tests-gui/src/main/java/org/kie/wb/selenium/model/persps/TasksPerspective.java, business-central-tests/business-central-tests-gui/src/main/java/org/kie/wb/selenium/model/persps/authoring/ImportProjectsScreen.java, business-central-tests/business-central-tests-gui/src/main/java/org/kie/wb/selenium/model/widgets/ModalDialog.java, business-central-tests/business-central-tests-gui/src/test/java/org/kie/wb/selenium/ui/ProjectLibraryIntegrationTest.java
@Rikkola please check
Main change: unignore test which was ignored because of [RHPAM-581](https://issues.jboss.org/browse/RHPAM-581) which was fixed some time ago.
The rest are just fixes to IntelliJ warnings in the selenium test module.
=> Unignore test after RHPAM-581 fixed

business-central-parent/business-central-webapp/pom.xml, business-central-parent/business-monitoring-webapp/pom.xml
Fixing packaging issue by excluding stax-api from kie-wb-common-server-ui-backend module
=> JBPM-7834: Provide OpenShiftStartupStrategy - WB Integration

business-central-parent/business-central-webapp/src/main/webapp/WEB-INF/web.xml, business-central-parent/business-monitoring-webapp/src/main/webapp/WEB-INF/web.xml
This PR configures the Gzip filter introduced on the related PR in kiegroup/appformer.
This filter intercepts requests for the configured `url-pattern` matching resources and checks for the "gzip" `Accept-Encoding` HTTP header. If it's present, the filter compresses the requested asset in Gzip format, reducing its size and therefore optimizing its download.
This is particularly important for the GWT JavaScript bundles, which originally have around 30MB. **After gzip compression, the bundles are only around 6MB.**
Related PRs:
https://github.com/kiegroup/appformer/pull/631
https://github.com/kiegroup/kie-wb-distributions/pull/877
https://github.com/kiegroup/kie-docs/pull/1395
=> AF-1817: Gzip filter

business-central-parent/business-central-webapp/src/main/webapp/WEB-INF/web.xml, business-central-parent/business-monitoring-webapp/src/main/webapp/WEB-INF/web.xml
This PR configures the excludedPaths parameter on `BasicAuthSecurityFilter` for rest services to exclude `/rest/healthy` and `/rest/ready` URIs from authentication.
Related PRs:
https://github.com/kiegroup/appformer/pull/645
https://github.com/kiegroup/kie-wb-common/pull/2492
https://github.com/kiegroup/kie-wb-distributions/pull/881
=> AF-1821: Readiness and Liveness endpoints

business-central-parent/business-monitoring-webapp/pom.xml
Adding missing dependencies to avoid CDI errors.
@tomasdavidorg @cristianonicolai could you please take a look?
https://github.com/kiegroup/drools/pull/2277
https://github.com/kiegroup/kie-wb-common/pull/2525
https://github.com/kiegroup/jbpm-wb/pull/1316
https://github.com/kiegroup/jbpm-designer/pull/842
https://github.com/kiegroup/kie-wb-distributions/pull/898
=> JBPM-6848: Form Generation fails generating forms for classes on external dependencies

business-central-parent/business-central-webapp/pom.xml, business-central-parent/business-central-webapp/src/main/resources/org/kie/bc/KIEWebapp.gwt.xml
See https://issues.jboss.org/browse/DROOLS-4049
Further to [this](https://github.com/kiegroup/drools-wb/pull/1144) adding PMML to Business Central.
IDK why dependencies are scattered around the `pom` (i.e. `-api` are not grouped with `-client`/`-backend`) I just followed positioning of the existing artifacts when adding the new PMML ones.
=> DROOLS-4049: PMML files are not listed in Library only in Project Explorer

business-central-parent/business-central-webapp/src/main/resources/org/kie/bc/KIEWebapp.gwt.xml, business-central-parent/business-monitoring-webapp/pom.xml, business-central-parent/business-monitoring-webapp/src/main/resources/org/kie/bc/KIEWebapp.gwt.xml
Adding missing config for forms engine on monitoring webapp. Additionaly removed duplicated gwt module on BC.
@tomasdavidorg @cristianonicolai @sutaakar could you please take a look?
=> RHPAM-2101: BC Monitoring fails to start a new process in an unmanaged immutable kieserver

business-central-tests/business-central-tests-rest/src/test/java/org/kie/wb/test/rest/AccessRestTestBase.java, business-central-tests/business-central-tests-rest/src/test/java/org/kie/wb/test/rest/RestTestBase.java, business-central-tests/business-central-tests-rest/src/test/java/org/kie/wb/test/rest/functional/SpacesScreenServiceIntegrationTest.java, business-central-tests/business-central-tests-rest/src/test/java/org/kie/wb/test/rest/security/JobAccessIntegrationTest.java
Several things happen in this PR that can't be split in several commits:
All the information about spaces and repositories used to live in system.git project. That project makes that every change that was need to be done locks repository for all users. 
Now, all the information about each space is stored inside config.git in every space. So lock will happen only for that space and not for the whole file system. Also migration tool was modified to include previous changes.
When you delete a Space or Repository, they are marked to be deleted. User will continue working as it was used to. Nothing from user perspectiva but they way that deleted spaces are shown. 
* A deleted Repository disappear from Library View and is marked to be deleted with a flag in config.git
* A deleted Space doesn't …
=> [AF-1792]  Migration of space information from system.git to config.git + HA improvements

business-central-tests/business-central-tests-rest/src/test/java/org/kie/wb/test/rest/security/ProjectAccessIntegrationTest.java
This PR simplify the ProjectAccessIntegrationTest class by
- Resuing method for project creation from parent class
- Reusing one project for multiple tests where the test has read only effect
=> BAQE-993: Clean up ProjectAccessIntegrationTest

business-central-parent/business-central-webapp/pom.xml, business-central-parent/business-monitoring-webapp/pom.xml
Adding uberfire-preference-client-backend dependency, which is introduced by: kiegroup/appformer#724
MERGE WITH kiegroup/appformer#724
=> AF-1987: Adding uberfire-preference-client-backend dep

business-central-parent/business-central-webapp/pom.xml
brings back security to business-central by adding uberfire-security-client-backend dependency.
=> AF-2118: Adding uberfire-security-client-backend

business-central-tests/business-central-tests-gui/src/test/filtered-resources/arquillian.xml
An attempt to stabilize failing community selenium tests.
=> BAQE-982: Upgrade Gecko Driver Version

business-central-parent/add-ons-distribution/pom.xml
(cherry picked from commit 2cb2fd39c3c65b47cf9c2b77bf0b05ea3c2f452d)
Forward-port of #967.
=> Add sources classifier to employee-rostering-distribution

business-central-tests/business-central-tests-gui/pom.xml, business-central-tests/pom.xml
@tomasdavidorg @jomarko Adding it here as I see the selenium tests failing in common fashion, this is a test to see if it helps.
=> Use rerunFailingTestsCount for BC integration test

business-central-parent/business-central-webapp/pom.xml
=> RHPAM-2529: org.jboss.errai:errai-bus dependency removed from business-central-webapp project

business-central-tests/business-central-tests-rest/src/main/java/org/kie/wb/test/rest/client/RestWorkbenchClient.java, business-central-tests/business-central-tests-rest/src/main/java/org/kie/wb/test/rest/client/WorkbenchClient.java, business-central-tests/business-central-tests-rest/src/test/java/org/kie/wb/test/rest/functional/ProjectIntegrationTest.java
Adding tests cases for [AF-2332] Add Branch support to Business Central REST API
See https://github.com/kiegroup/appformer/pull/841
Limitations:
* Could not test `null` branch since RESTEasy does not allow null parameters
* Could not test additional branches since there are not REST endpoints to create branches
=> [AF-2332] Add Branch support to Business Central REST API

business-central-parent/business-central-distribution-wars/business-monitoring/pom.xml, business-central-parent/business-central-webapp/pom.xml, business-central-parent/business-monitoring-webapp/pom.xml
BXMSPROD-621
io.netty:netty exclusion added to org.uberfire:uberfire-metadata-backend-elasticsearch
=> BXMSPROD-621 uberfire-metadata-backend-elasticsearch dependency removed from business-monitoring. Branch master

business-central-parent/business-monitoring-webapp/src/main/resources/META-INF/services/org.uberfire.java.nio.file.spi.FileSystemProvider
Can only re-enable nio2.k8s file system implementation along with or after PRs related to AF-2253 being merged.
Related JIRAs
https://issues.redhat.com/projects/AF/issues/AF-2253
Signed-off-by: Evan Zhang <evan.zhang@redhat.com>
=> [KIECLOUD-256] Revert and disable nio2.k8s impl due to readiness of the blocking issue [AF-2253]

business-central-tests/pom.xml
Wildfly container was recently upgraded to version 18 across kiegroup codebase. We need to upgrade also version for tests.
For more details see:
- https://issues.redhat.com/browse/AF-2524
- https://issues.redhat.com/browse/JBPM-9044
=> AF-2524: Upgrade business central tests to use wildfly18

business-central-tests/pom.xml
BaseWildflyCLIManager by default uses port 9990. However when we run tests on wildfly via cargo the port may be different.
For more details see: https://issues.redhat.com/browse/AF-2523
=> AF-2523: Configure port for BaseWildflyCLIManager

business-central-parent/business-central-webapp/pom.xml, business-central-parent/business-monitoring-webapp/pom.xml
https://issues.redhat.com/browse/BXMSPROD-598
filterWebInfLib property added with the value 'uberjar-only' to thorntail maven plugin to the business-monitoring-webapp and business-central-webapp
=> BXMSPROD-598 filterWebInfLib property added to thorntail maven plugin

business-central-parent/business-central-distribution-wars/business-central/pom.xml
(cherry picked from commit ed472e3679c2df4bc2784598554ca930113eeecf)
=> excluded org.jboss.modules because of duplicated classes

business-central-parent/business-central-distribution-wars/business-central/pom.xml, business-central-parent/business-central-distribution-wars/business-monitoring/pom.xml, business-central-parent/business-central-webapp-common/src/main/webapp/META-INF/jboss-deployment-structure.xml, business-central-parent/business-central-webapp/pom.xml, business-central-parent/business-monitoring-webapp/pom.xml
- Removed platform specific dependencies from jboss-deployment-structure.xml and added them to container.
- These dependencies were conflicting  in wildfly 18 and wildfly 14.
Related or Merge with : https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1362
=> RHPAM-2985 : Removed Jboss EAP plateform specific dependancies and added to container

business-central-parent/pom.xml
This is a change for having always directory for Errai Wildfly unpacked distribution to be on the same name as original wildfly distribution as Errai just repackaged it so naming directory to that version is not confusing
=> fixed real directory for Errai Wildfly distribution

business-central-parent/business-central-webapp/.gitignore, business-central-parent/business-central-webapp/pom.xml, business-central-parent/business-central-webapp/src/main/resources/org/kie/bc/KIEWebapp.gwt.xml, business-central-parent/business-central-webapp/src/main/webapp/kie-wb.jsp
**JIRA**: [KOGITO-2664](https://issues.redhat.com/browse/KOGITO-2664): [DMN Designer] Multiple DRDs support
**Part of an ensemble**:
- https://github.com/kiegroup/kie-wb-common/pull/3379
- https://github.com/kiegroup/drools-wb/pull/1416
- https://github.com/kiegroup/kie-wb-distributions/pull/1054
- **Business Central**: [WAR file v6](https://www.dropbox.com/s/6lovcz78ixv7a55/business-central-v6.war?dl=0)
- **VS Code**: [plugin v6](https://www.dropbox.com/s/ukfin8xsp5rl5sj/plugin-v6.vsix?dl=0)
This PR covers the following JIRAs:
- [KOGITO-2665](https://issues.redhat.com/browse/KOGITO-2665): Marshaller - Adopt the first DMNDiagram as the DRG (author: @karreiro)
- [KOGITO-2965](https://issues.redhat.com/browse/KOGITO-2965): Graph - Palette changes (author: @danielzhe)
- …
=> KOGITO-2664: [DMN Designer] Multiple DRDs support

business-central-parent/business-central-distribution-wars/business-central/src/main/productized/resources/security-policy.properties, business-central-parent/business-central-webapp/src/main/resources/security-policy.properties
**AF-2692**: https://issues.redhat.com/browse/AF-2692
https://github.com/kiegroup/appformer/pull/1081
https://github.com/kiegroup/kie-wb-common/pull/3510
- Added default permissions for these settings
<details>
<summary>
</summary>
* <b>an upstream build</b> please add comment: …
=> AF-2692 : Add a security permission to show project toolbar, Metrics tab and change request tab

business-central-tests/business-central-tests-rest/src/test/java/org/kie/wb/test/rest/RestTestBase.java, business-central-tests/business-central-tests-rest/src/test/java/org/kie/wb/test/rest/functional/ProjectIntegrationTest.java, business-central-tests/business-central-tests-rest/src/test/java/org/kie/wb/test/rest/functional/RepositoryIntegrationTest.java, business-central-tests/business-central-tests-rest/src/test/java/org/kie/wb/test/rest/functional/SpaceIntegrationTest.java, business-central-tests/pom.xml
Due to recent jira authentication changes we decided to stop using issue-keeper tool for preventing test method run. It was replaced by simple '@Ignore' junit annotations.
For more details see:
- https://issues.redhat.com/browse/JBPM-9542
- https://github.com/ibek/issue-keeper
**JIRA**: https://issues.redhat.com/browse/JBPM-9542
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1563
* https://github.com/kiegroup/jbpm/pull/1828
=> JBPM-9542: Remove issue-keeper tool

business-central-tests/business-central-tests-rest/src/test/java/org/kie/wb/test/rest/RestTestBase.java, business-central-tests/business-central-tests-rest/src/test/java/org/kie/wb/test/rest/functional/ProjectIntegrationTest.java, business-central-tests/business-central-tests-rest/src/test/java/org/kie/wb/test/rest/functional/RepositoryIntegrationTest.java, business-central-tests/business-central-tests-rest/src/test/java/org/kie/wb/test/rest/functional/SpaceIntegrationTest.java, business-central-tests/pom.xml
#1080 cherry-pick
Due to recent jira authentication changes we decided to stop using issue-keeper tool for preventing test method run. It was replaced by simple '@Ignore' junit annotations.
For more details see:
- https://issues.redhat.com/browse/JBPM-9542
- https://github.com/ibek/issue-keeper
[link](https://www.example.com)
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1564
* https://github.com/kiegroup/jbpm/pull/1831
<details>
<summary>
</summary>
* <b>a …
=> [7.48.x] JBPM-9542: Remove issue-keeper tool (#1080)

business-central-parent/business-central-webapp/pom.xml, business-central-parent/business-central-webapp/src/main/resources/modules/org/eclipse/jgit/main/module.xml
**RHPAM-3632**: _https://issues.redhat.com/browse/RHPAM-3632_ 
- It is needed since wildfly dependency coming from thorntail were adding older jgit version in project classpath that were causing conflict while running business central in standalone mode.
- Add changes that forces EAP to use the jgit dependency version that is supported by business central (5.8.0.202006091008-r).
- This will override the jgit module.xml inside EAP.
<details>
<summary>
</summary>
* <b>a …
=> RHPAM-3632 :Project cannot be cloned from Business Central Standalone

business-central-parent/business-central-webapp/pom.xml
Hi @mareknovotny, @mbiarnes, @romartin, @jomarko it is cherry-pick of https://github.com/kiegroup/kie-wb-distributions/pull/1127
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1771
* https://github.com/kiegroup/kie-wb-distributions/pull/1129
* https://github.com/kiegroup/jbpm-wb/pull/1515
* https://github.com/kiegroup/kie-wb-common/pull/3685
<details>
<summary>
</summary>
* …
=> [7.59.x] JBPM-9896 - Fix dependency for compilation Stunner on JDK 11 to JRE 8

business-central-tests/pom.xml
Signed-off-by: Karel Suta <ksuta@redhat.com>
<details>
<summary>
</summary>
* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>
=> Extend Business central deployment timeout for tests to 4 minutes

business-central-parent/business-central-distribution-wars/business-central/pom.xml, business-central-parent/pom.xml, pom.xml
**JIRA**: https://issues.redhat.com/browse/RHPAM-4163
I'm submitting this PR first to 7.59.x branch (because https://github.com/kiegroup/kie-wb-distributions/pull/1144 is missing for now in main branch) and as soon it gets merged, I will submit it to main branch.
<details>
<summary>
</summary>
* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>
=> [7.59.x] [RHPAM-4163] parametrize the bootable jar GAV used by wildfly-jar-maven-plugin

business-central-parent/business-central-webapp/pom.xml
Ticket: https://issues.redhat.com/browse/RHPAM-4455
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2027
- https://github.com/kiegroup/droolsjbpm-integration/pull/2836
- https://github.com/kiegroup/kie-wb-common/pull/3760
- https://github.com/kiegroup/kie-wb-distributions/pull/1178
Backporting:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2023
=> [7.67.x] RHPAM-4455 org.w3c.dom.* ignored from ban-duplicated-classes

pom.xml
This prod version is EAP XP on top of EAP 7.4.8
**JIRA**:  https://issues.redhat.com/browse/RHPAM-4618
- https://github.com/kiegroup/kie-wb-distributions/pull/1208
- https://github.com/kiegroup/kie-wb-distributions/pull/1206
- https://github.com/kiegroup/kie-wb-distributions/pull/1207
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of …
=> [RHPAM-4618] update EAP XP to version 4.0.0.GA-redhat-00011
