kiegroup/kie-wb-distributions

kie-docs/jbpm-docs/src/main/docbook/en-US/Persistence/Transactions.xml
Let me know if this change is ok and if possible merge the PR. There are more places where StatefulKnowledgeSession is used in jbpm-docs, is this ok? Because I think that StatefulKnowledgeSession has been deprecated in favor of KieSession.
=> jbpm persistence and transactions example update

kie-drools-wb/kie-drools-wb-distribution-wars-cdi1.0/pom.xml, kie-drools-wb/kie-drools-wb-distribution-wars-cdi1.0/src/main/assembly/weblogic12/WEB-INF/weblogic.xml, kie-drools-wb/kie-drools-wb-distribution-wars-cdi1.0/src/main/community/assembly-kie-drools-wb-weblogic-12.xml, kie-drools-wb/kie-drools-wb-distribution-wars-cdi1.0/src/main/community/assembly-kie-drools-wb-websphere-as-8.xml, kie-drools-wb/kie-drools-wb-distribution-wars-cdi1.0/src/main/productized/assembly-kie-drools-wb-weblogic-12-redhat.xml, kie-drools-wb/kie-drools-wb-distribution-wars-cdi1.0/src/main/productized/assembly-kie-drools-wb-websphere-as-8-redhat.xml, kie-drools-wb/kie-drools-wb-webapp/pom.xml, kie-wb/kie-wb-distribution-wars-cdi1.0/pom.xml, kie-wb/kie-wb-distribution-wars-cdi1.0/src/main/assembly/weblogic12/WEB-INF/weblogic.xml, kie-wb/kie-wb-distribution-wars-cdi1.0/src/main/community/assembly-kie-wb-weblogic-12.xml, kie-wb/kie-wb-distribution-wars-cdi1.0/src/main/community/assembly-kie-wb-websphere-as-8.xml, kie-wb/kie-wb-distribution-wars-cdi1.0/src/main/productized/assembly-kie-wb-weblogic-12-redhat.xml, kie-wb/kie-wb-distribution-wars-cdi1.0/src/main/productized/assembly-kie-wb-websphere-as-8-redhat.xml, kie-wb/kie-wb-webapp/pom.xml
@porcelli @manstis @dgutierr 
please have a look at the changes as these were required to successfully deploy and run on WLS and WAS.
See email for still remaining issues
=> GWT upgrade - improvements for Weblogic and WebSphere assemblies

kie-drools-wb/kie-drools-wb-webapp/pom.xml, kie-drools-wb/kie-drools-wb-webapp/src/main/java/org/kie/workbench/drools/client/KieDroolsWorkbenchEntryPoint.java, kie-wb/kie-wb-webapp/pom.xml, kie-wb/kie-wb-webapp/src/main/java/org/kie/workbench/client/KieWorkbenchEntryPoint.java
=>  JBPM-4625 Generation of JPA enabled models

kie-config-cli/src/main/java/org/kie/config/cli/command/impl/AddGroupToProjectCliCommand.java, kie-config-cli/src/main/java/org/kie/config/cli/command/impl/ListProjectDetailsCliCommand.java, kie-config-cli/src/main/java/org/kie/config/cli/command/impl/RemoveGroupFromProjectCliCommand.java
This depends on pull requests on guvnor and kie-wb-common.
=> Bug 1254907 - Items of project explorer are not refreshed automatically

kie-drools-wb/kie-drools-wb-webapp/src/main/java/org/kie/workbench/drools/client/docks/AuthoringWorkbenchDocks.java, kie-wb/kie-wb-webapp/src/main/java/org/kie/workbench/client/docks/AuthoringWorkbenchDocks.java
- Fix for avoiding the undesired collapse of the Tool Windows in certain scenarios, e.g: when selected field changes, etc.
=> JBPM-4625 Generation of JPA enabled models

kie-config-cli/src/main/java/org/kie/config/cli/command/impl/CreateRepositoryCliCommand.java, kie-config-cli/src/main/java/org/kie/config/cli/support/GitRepositoryHelper.java
- addtional commit to the BZ fixing to ensure just created reposiories are unmanaged
=> BZ1263454: Unable to create Project in cloned Git Repository

kie-drools-wb/kie-drools-wb-distribution-wars/src/main/assembly/tomcat7/WEB-INF/web.xml, kie-wb/kie-wb-distribution-wars/src/main/assembly/tomcat7/WEB-INF/web.xml
- Simple change to web.xml to upgrade to Servlet 3. This is in line with all other assemblies.
=> Upgrade Tomcat 7 assembly to use Servlet 3

kie-drools-wb/kie-drools-wb-webapp/pom.xml, kie-wb/kie-wb-webapp/pom.xml
=> Do not include empty dirs inside WEB-INF/classes

kie-drools-wb/kie-drools-wb-webapp/src/main/java/org/kie/workbench/drools/client/KieDroolsWorkbenchEntryPoint.java
New perspective does not allow new tasks to be created
=> [6.4.x] BZ1263753 - Update task perspective

kie-drools-wb/kie-drools-wb-webapp/src/main/java/org/kie/workbench/drools/client/KieDroolsWorkbenchEntryPoint.java
New perspective does not allow new tasks to be created
=> BZ1263753 - Update task perspective

kie-drools-wb/kie-drools-wb-webapp/src/main/java/org/kie/workbench/drools/backend/server/LuceneConfigProducer.java, kie-wb/kie-wb-webapp/src/main/java/org/kie/workbench/backend/LuceneConfigProducer.java
See also: 
- https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/169
- https://github.com/uberfire/uberfire/pull/337
- https://github.com/uberfire/uberfire-extensions/pull/258
- https://github.com/droolsjbpm/kie-wb-common/pull/337
- https://github.com/droolsjbpm/jbpm-designer/pull/220
- https://github.com/droolsjbpm/jbpm-form-modeler/pull/46
- https://github.com/droolsjbpm/jbpm-console-ng/pull/395
- https://github.com/droolsjbpm/drools-wb/pull/156
- https://github.com/droolsjbpm/optaplanner-wb/pull/56
- https://github.com/droolsjbpm/kie-wb-distributions/pull/261
=> UF-295 - Upgrading lucene to 5.3.1

droolsjbpm-uber-distribution/.gitignore, droolsjbpm-uber-distribution/pom.xml, droolsjbpm-uber-distribution/src/main/assembly/assembly-droolsjbpm-uber.xml, droolsjbpm-uber-distribution/src/main/assembly/filtered-resources/documentation_table.txt, droolsjbpm-uber-distribution/src/main/assembly/filtered-resources/download_jboss_org/latest/compositeArtifacts.xml, droolsjbpm-uber-distribution/src/main/assembly/filtered-resources/download_jboss_org/latest/compositeContent.xml, pom.xml
See also https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/196
=> [DROOLS-1136] move droolsjbpm-uber-distribution

kie-wb-smoke-tests/kie-wb-smoke-tests-main/pom.xml, kie-wb/kie-wb-distribution-wars/pom.xml
Depends on https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/201
=> Fixes after upgrade to IP BOM 7.0.0.CR3

kie-drools-wb/kie-drools-wb-webapp/pom.xml, kie-wb/kie-wb-webapp/pom.xml
See https://issues.jboss.org/browse/GUVNOR-2181 and referenced BPSMPL.
This is Phase 1, replacing the existing Grid Widget.
=> GUVNOR-2181: Guided Decision Table Editor: Add support for linked tables

kie-wb-tests/kie-wb-tests-gui/pom.xml, kie-wb-tests/pom.xml
@mrietveld, @livthomas could you please take a look?
=> Enable REST tests by default

kie-drools-wb/kie-drools-wb-webapp/src/main/resources/security-module-admin.properties, kie-drools-wb/kie-drools-wb-webapp/src/main/resources/security-module-analyst.properties, kie-drools-wb/kie-drools-wb-webapp/src/main/resources/security-module-kiemgmt.properties, kie-drools-wb/kie-drools-wb-webapp/src/main/resources/security-module-plannermgmt.properties, kie-drools-wb/kie-drools-wb-webapp/src/main/resources/security-policy.properties, kie-drools-wb/kie-drools-wb-webapp/src/test/java/org/kie/workbench/drools/security/WorkbenchACLTest.java, kie-wb/kie-wb-webapp/src/main/resources/security-module-admin.properties, kie-wb/kie-wb-webapp/src/main/resources/security-module-analyst.properties, kie-wb/kie-wb-webapp/src/main/resources/security-module-developer.properties, kie-wb/kie-wb-webapp/src/main/resources/security-module-kiemgmt.properties, kie-wb/kie-wb-webapp/src/main/resources/security-module-manager.properties, kie-wb/kie-wb-webapp/src/main/resources/security-module-plannermgmt.properties, kie-wb/kie-wb-webapp/src/main/resources/security-module-user.properties, kie-wb/kie-wb-webapp/src/main/resources/security-policy.properties, kie-wb/kie-wb-webapp/src/test/java/org/kie/workbench/security/WorkbenchACLTest.java
Fix + tests
@manstis Can you verify please?
NOTE: This PR depends on uberfire/uberfire#439
=> UF-343: User without assigned role has all the permissions allowed

kie-wb-tests/kie-wb-tests-rest/src/main/java/org/kie/wb/test/rest/client/RestWorkbenchClient.java
We've has migrated our selenium tests to use this RestWorkbenchClient to perform some basic setup for tests (deleting/cloning testing repo etc.) but it seems that the default 10/60s timeouts for deleting/cloning repo are often not enough for tests running on jenkins.
This PR makes the timeouts configurable while keeping backward api compatibility + adds some logging.
@livthomas please review
=> Make timeouts for testing rest client configurable

kie-config-cli/src/main/java/org/kie/config/cli/EnvironmentProvider.java
@psiroky can you take a look / merge? Thanks!
=> GUVNOR-2173: fix build after RefactoringQueryService changes

pom.xml
=> Exclude incorrect version of javassist (not compatible with Java8)

pom.xml
=> Add missing resteasy version

kie-drools-wb/kie-drools-wb-home-page-product/src/main/resources/org/kie/workbench/drools/public/css/home.css, kie-wb-distribution-home/kie-wb-distribution-home-client/src/main/java/org/kie/workbench/common/screens/home/client/widgets/home/HomeViewImpl.java, kie-wb-distribution-home/kie-wb-distribution-home-client/src/main/resources/org/kie/workbench/common/screens/home/client/resources/css/home.css, kie-wb/kie-wb-home-page-product/src/main/resources/org/kie/workbench/public/css/home.css
RHBPMS-1573: [de, ru, ja] The text alignment needs to be adjusted on the home page.
RHBPMS-1697: [de_DE] Home -> Home Page: "Manage Tasks" Tab in germen "Aufgabenverwaltung" is truncated
=> Alignment fixes (RHBPMS-1573, RHBPMS-1697)

kie-drools-wb/kie-drools-wb-webapp/src/main/java/org/kie/workbench/drools/client/KieDroolsWorkbenchEntryPoint.java, kie-drools-wb/kie-drools-wb-webapp/src/test/java/org/kie/workbench/drools/client/KieDroolsWorkbenchEntryPointTest.java, kie-wb/kie-wb-webapp/src/main/java/org/kie/workbench/client/KieWorkbenchEntryPoint.java, kie-wb/kie-wb-webapp/src/test/java/org/kie/workbench/client/KieWorkbenchEntryPointTest.java
See https://issues.jboss.org/browse/GUVNOR-2670
=> [6.5.x] GUVNOR-2670: Screens on 'Authoring->Project Authoring' of business-central are opened by default

kie-drools-wb/kie-drools-wb-distribution-wars/src/main/productized/webapp/login.jsp, kie-drools-wb/kie-drools-wb-distribution-wars/src/main/productized/webapp/logout.jsp, kie-drools-wb/kie-drools-wb-distribution-wars/src/main/productized/webapp/not_authorized.jsp, kie-drools-wb/kie-drools-wb-webapp/src/main/java/org/kie/workbench/drools/client/KieDroolsWorkbenchEntryPoint.java, kie-drools-wb/kie-drools-wb-webapp/src/main/webapp/login.jsp, kie-drools-wb/kie-drools-wb-webapp/src/main/webapp/logout.jsp, kie-drools-wb/kie-drools-wb-webapp/src/main/webapp/not_authorized.jsp, kie-drools-wb/kie-drools-wb-webapp/src/test/java/org/kie/workbench/drools/client/KieDroolsWorkbenchEntryPointTest.java, kie-wb-smoke-tests/kie-wb-smoke-tests-main/src/main/java/org/kie/smoke/wb/selenium/model/persps/AbstractPerspective.java, kie-wb/kie-wb-distribution-wars/src/main/productized/webapp/login.jsp, kie-wb/kie-wb-distribution-wars/src/main/productized/webapp/logout.jsp, kie-wb/kie-wb-distribution-wars/src/main/productized/webapp/not_authorized.jsp, kie-wb/kie-wb-webapp/src/main/java/org/kie/workbench/client/KieWorkbenchEntryPoint.java, kie-wb/kie-wb-webapp/src/main/webapp/login.jsp, kie-wb/kie-wb-webapp/src/main/webapp/logout.jsp, kie-wb/kie-wb-webapp/src/main/webapp/not_authorized.jsp, kie-wb/kie-wb-webapp/src/test/java/org/kie/workbench/client/KieWorkbenchEntryPointTest.java
(cherry picked from commit d451fe27224a1d646af571486ebab21453fbce21)
This also incorporates kie-wb-common commit b91d8db65bfd8fc9667ee001c838444bdf8bd352.
This is the corollary of both https://github.com/droolsjbpm/kie-wb-common/pull/457 and https://github.com/droolsjbpm/kie-wb-distributions/pull/349 for 6.5.x.
=> [6.5.x] RHBPMS-4145: Language selection is not remembered on relogin in Chrome

kie-drools-wb/kie-drools-wb-distribution-wars/src/main/productized/webapp/login.jsp, kie-drools-wb/kie-drools-wb-distribution-wars/src/main/productized/webapp/logout.jsp, kie-drools-wb/kie-drools-wb-distribution-wars/src/main/productized/webapp/not_authorized.jsp, kie-drools-wb/kie-drools-wb-webapp/src/main/webapp/login.jsp, kie-drools-wb/kie-drools-wb-webapp/src/main/webapp/logout.jsp, kie-drools-wb/kie-drools-wb-webapp/src/main/webapp/not_authorized.jsp, kie-wb/kie-wb-distribution-wars/src/main/productized/webapp/login.jsp, kie-wb/kie-wb-distribution-wars/src/main/productized/webapp/logout.jsp, kie-wb/kie-wb-distribution-wars/src/main/productized/webapp/not_authorized.jsp, kie-wb/kie-wb-webapp/src/main/webapp/login.jsp, kie-wb/kie-wb-webapp/src/main/webapp/logout.jsp, kie-wb/kie-wb-webapp/src/main/webapp/not_authorized.jsp
See https://issues.jboss.org/browse/RHBPMS-631
(cherry picked from commit 31a05e15af7267a05618f2438d802ccb5b81056e)
This is the corollary of https://github.com/droolsjbpm/kie-wb-distributions/pull/351 for 6.5.x
=> [6.5.x] RHBPMS-631: Login page is not localized - problems with dialect support

kie-drools-wb/kie-drools-wb-distribution-wars/src/main/productized/webapp/login.jsp, kie-drools-wb/kie-drools-wb-distribution-wars/src/main/productized/webapp/logout.jsp, kie-drools-wb/kie-drools-wb-distribution-wars/src/main/productized/webapp/not_authorized.jsp, kie-drools-wb/kie-drools-wb-webapp/src/main/webapp/login.jsp, kie-drools-wb/kie-drools-wb-webapp/src/main/webapp/logout.jsp, kie-drools-wb/kie-drools-wb-webapp/src/main/webapp/not_authorized.jsp, kie-wb/kie-wb-distribution-wars/src/main/productized/webapp/login.jsp, kie-wb/kie-wb-distribution-wars/src/main/productized/webapp/logout.jsp, kie-wb/kie-wb-distribution-wars/src/main/productized/webapp/not_authorized.jsp, kie-wb/kie-wb-webapp/src/main/webapp/login.jsp, kie-wb/kie-wb-webapp/src/main/webapp/logout.jsp, kie-wb/kie-wb-webapp/src/main/webapp/not_authorized.jsp
See https://issues.jboss.org/browse/RHBPMS-631
=> RHBPMS-631: Login page is not localized - problems with dialect support

kie-drools-wb/kie-drools-wb-distribution-wars/src/main/assembly/tomcat7/WEB-INF/web.xml, kie-drools-wb/kie-drools-wb-distribution-wars/src/main/productized/webapp/kie-drools-wb.jsp, kie-drools-wb/kie-drools-wb-distribution-wars/src/main/productized/webapp/logout.jsp, kie-drools-wb/kie-drools-wb-distribution-wars/src/main/productized/webapp/not_authorized.jsp, kie-drools-wb/kie-drools-wb-webapp/pom.xml, kie-drools-wb/kie-drools-wb-webapp/src/main/resources/org/kie/workbench/drools/client/resources/i18n/LoginConstants.properties, kie-drools-wb/kie-drools-wb-webapp/src/main/webapp/WEB-INF/web.xml, kie-drools-wb/kie-drools-wb-webapp/src/main/webapp/kie-drools-wb.jsp, kie-drools-wb/kie-drools-wb-webapp/src/main/webapp/logout.jsp, kie-drools-wb/kie-drools-wb-webapp/src/main/webapp/not_authorized.jsp, kie-wb/kie-wb-distribution-wars/src/main/assembly/tomcat7/WEB-INF/web.xml, kie-wb/kie-wb-distribution-wars/src/main/productized/webapp/kie-wb.jsp, kie-wb/kie-wb-distribution-wars/src/main/productized/webapp/logout.jsp, kie-wb/kie-wb-distribution-wars/src/main/productized/webapp/not_authorized.jsp, kie-wb/kie-wb-webapp/pom.xml, kie-wb/kie-wb-webapp/src/main/resources/org/kie/workbench/client/resources/i18n/LoginConstants.properties, kie-wb/kie-wb-webapp/src/main/webapp/WEB-INF/web.xml, kie-wb/kie-wb-webapp/src/main/webapp/kie-wb.jsp, kie-wb/kie-wb-webapp/src/main/webapp/logout.jsp, kie-wb/kie-wb-webapp/src/main/webapp/not_authorized.jsp
(cherry picked from commit 755290935e9867115f0ab4c96c16bbd1f5d40284)
This is the corollary of https://github.com/droolsjbpm/kie-wb-distributions/pull/353 for 6.5.x
=> [6.5.x] RHBPMS-4129: Unlocalized 'Please wait. Loading application...' spinner

kie-drools-wb/kie-drools-wb-webapp/src/main/java/org/kie/workbench/drools/backend/server/AppSetup.java, kie-wb/kie-wb-webapp/src/main/java/org/kie/workbench/backend/AppSetup.java
Depends on:
- https://github.com/uberfire/uberfire/pull/509
- https://github.com/uberfire/uberfire-extensions/pull/301.
=> RHBPMS-4220: Added RoleRegistry and registered principals that come from Keycloak remote logins as roles.

kie-wb-tests/kie-wb-tests-gui/src/main/java/org/kie/wb/selenium/model/persps/AdministrationPerspective.java
See https://kie-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/kie-wb-distributions/1402/testReport/
Looks like a Selenium test started failing following some i18n changes.
=> Fix Selenium integration test following i18n changes

droolsjbpm-uber-distribution/pom.xml, droolsjbpm-uber-distribution/src/main/assembly/assembly-droolsjbpm-uber.xml
Ensemble:
https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/284
https://github.com/droolsjbpm/optaplanner/pull/224
https://github.com/droolsjbpm/kie-wb-distributions/pull/360
=> PLANNER-657 optaplanner-docs migration from DocBook to AsciiDoc

kie-drools-wb/kie-drools-wb-distribution-wars/src/main/assembly/was8/WEB-INF/web.xml, kie-drools-wb/kie-drools-wb-distribution-wars/src/main/assembly/weblogic12/WEB-INF/web.xml, kie-wb/kie-wb-distribution-wars/src/main/assembly/eap6_4/WEB-INF/web-ui-server.xml, kie-wb/kie-wb-distribution-wars/src/main/assembly/tomcat7/WEB-INF/web-ui-server.xml, kie-wb/kie-wb-distribution-wars/src/main/assembly/was8/WEB-INF/web-ui-server.xml, kie-wb/kie-wb-distribution-wars/src/main/assembly/was8/WEB-INF/web.xml, kie-wb/kie-wb-distribution-wars/src/main/assembly/weblogic12/WEB-INF/web-ui-server.xml, kie-wb/kie-wb-distribution-wars/src/main/assembly/weblogic12/WEB-INF/web.xml, kie-wb/kie-wb-distribution-wars/src/main/assembly/wildfly10-eap7/WEB-INF/web-ui-server.xml
See https://issues.jboss.org/browse/RHBPMS-4358
@jhrcek Hi Jan.. just need the relevant ACKs... Thank-you for spotting (or thank your tests!)
=> [6.5.x] RHBPMS-4358: web.xml of WAS/WLS ditributions contain invalid references to kie-wb.html

kie-wb/kie-wb-distribution-wars/src/main/productized/webapp/logout.jsp, kie-wb/kie-wb-webapp/src/main/java/org/kie/workbench/backend/LogoutHelper.java, kie-wb/kie-wb-webapp/src/main/webapp/logout.jsp, kie-wb/kie-wb-webapp/src/test/java/org/kie/workbench/backend/LogoutHelperTest.java
Fix + tests.
https://issues.jboss.org/browse/JBPM-5378
I've verified on EAP 7.0.2.  The fix can be considered a workaround until we figure out along the EAP guys what's the root cause.
@manstis Can you please review it?
=> JBPM-5378: SSO between workbench and dashbuilder does not work

kie-drools-wb/kie-drools-wb-webapp/src/main/java/org/kie/workbench/drools/client/KieDroolsWorkbenchEntryPoint.java, kie-drools-wb/kie-drools-wb-webapp/src/test/java/org/kie/workbench/drools/client/KieDroolsWorkbenchEntryPointTest.java, kie-wb/kie-wb-webapp/src/main/java/org/kie/workbench/client/KieWorkbenchEntryPoint.java, kie-wb/kie-wb-webapp/src/test/java/org/kie/workbench/client/KieWorkbenchEntryPointTest.java
* Removed "Admin" menu item from the top level menu bar.
=> UF-320: Improvements on admin page and preferences view

kie-drools-wb/kie-drools-wb-webapp/pom.xml, kie-wb/kie-wb-webapp/pom.xml
@manstis @psiroky same as https://github.com/droolsjbpm/drools-wb/pull/320
please merge any time after: droolsjbpm/droolsjbpm-build-bootstrap#304
=> Do not delete GWT unitCache during clean

kie-drools-wb/kie-drools-wb-distribution-wars/src/main/assembly/component-kie-drools-wb-tomcat-7-common.xml, kie-drools-wb/kie-drools-wb-distribution-wars/src/main/assembly/tomcat7/WEB-INF/classes/datasource-management.properties, kie-drools-wb/kie-drools-wb-webapp/pom.xml, kie-drools-wb/kie-drools-wb-webapp/src/main/resources/datasource-management.properties, kie-drools-wb/kie-drools-wb-webapp/src/main/resources/org/kie/workbench/drools/KIEDroolsWebapp.gwt.xml, kie-wb/kie-wb-distribution-wars/src/main/assembly/component-kie-wb-tomcat-7-common.xml, kie-wb/kie-wb-distribution-wars/src/main/assembly/tomcat7/WEB-INF/classes/datasource-management.properties, kie-wb/kie-wb-webapp/pom.xml, kie-wb/kie-wb-webapp/src/main/resources/datasource-management.properties, kie-wb/kie-wb-webapp/src/main/resources/org/kie/workbench/KIEWebapp.gwt.xml
- adds the data sources management feature to kie-wb and kie-drools-wb
=> JBPM-5233: Data source management

kie-drools-wb/kie-drools-wb-webapp/pom.xml, kie-wb/kie-wb-webapp/pom.xml, pom.xml
This is the corollary of https://github.com/droolsjbpm/kie-wb-distributions/pull/397 for master.
(cherry picked from commit 1d2cee3251789bfa41c09281a2f6198ff41aca1d)
=> RHBPMS-4129: Unlocalized 'Please wait. Loading application...' spinner.

kie-drools-wb/kie-drools-wb-webapp/pom.xml, kie-wb/kie-wb-webapp/pom.xml, pom.xml
This adds an additional i18n procedure step; that renames files from Zanata.
=> [6.5.x] RHBPMS-4129: Unlocalized 'Please wait. Loading application...' spinner.

kie-wb/kie-wb-webapp/pom.xml, kie-wb/kie-wb-webapp/src/main/resources/org/kie/workbench/KIEWebapp.gwt.xml
=> KIE forms jBPM integration

kie-drools-wb/kie-drools-wb-webapp/src/main/resources/org/kie/workbench/drools/KIEDroolsWebapp.gwt.xml, kie-wb/kie-wb-webapp/src/main/resources/org/kie/workbench/KIEWebapp.gwt.xml
Thanks to @csadilek for suggesting this. I believe the decreased build time is a great improvement!
=> Don't build separate permutation for every locale

kie-drools-wb/kie-drools-wb-distribution-wars/src/main/assembly/component-kie-drools-wb-websphere-as-8-common.xml, kie-wb/kie-wb-distribution-wars/src/main/assembly/component-kie-wb-websphere-as-8-common.xml
See https://issues.jboss.org/browse/RHBPMS-4275?focusedCommentId=13307622&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-13307622
The upload of XLSX files fails on WAS due to missing ```XMLBeans``` JAR.
=> [6.5.x] RHBPMS-4275: Guided Decision Table: XLS cannot be validated

kie-drools-wb/kie-drools-wb-webapp/pom.xml, kie-wb/kie-wb-webapp/pom.xml
- Support for BeanValidation for dynamic models
=> KIE forms jBPM integration:

kie-drools-wb/kie-drools-wb-distribution-wars/src/main/assembly/tomcat7/WEB-INF/web.xml, kie-drools-wb/kie-drools-wb-webapp/pom.xml, kie-drools-wb/kie-drools-wb-webapp/src/main/webapp/WEB-INF/web.xml, kie-wb/kie-wb-distribution-wars/src/main/assembly/tomcat7/WEB-INF/web.xml, kie-wb/kie-wb-webapp/pom.xml, kie-wb/kie-wb-webapp/src/main/webapp/WEB-INF/web.xml
https://issues.jboss.org/browse/GUVNOR-2710
All the PRs:
https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/321
https://github.com/droolsjbpm/kie-wb-common/pull/581
https://github.com/droolsjbpm/drools-wb/pull/352
https://github.com/droolsjbpm/optaplanner-wb/pull/123
https://github.com/droolsjbpm/kie-wb-distributions/pull/421
=> GUVNOR-2710 : Make client side Verifier a web worker.

kie-drools-wb/kie-drools-wb-distribution-wars/src/main/assembly/tomcat7/WEB-INF/web.xml, kie-drools-wb/kie-drools-wb-webapp/pom.xml, kie-wb/kie-wb-distribution-wars/src/main/assembly/tomcat7/WEB-INF/web.xml, kie-wb/kie-wb-webapp/pom.xml
Should this have a ticket and where?
=> Fixes Tomcat deployment

kie-drools-wb/kie-drools-wb-distribution-wars/src/main/assembly/was8/WEB-INF/web.xml, kie-wb/kie-wb-distribution-wars/src/main/assembly/was8/WEB-INF/web-ui-server.xml, kie-wb/kie-wb-distribution-wars/src/main/assembly/was8/WEB-INF/web.xml
See https://issues.jboss.org/browse/RHBPMS-4571
=> [6.5.x] RHBPMS-4571: It is not possible to deploy business central on IBM WebSphere

kie-drools-wb/kie-drools-wb-webapp/pom.xml, kie-wb/kie-wb-webapp/pom.xml
Depends on https://github.com/uberfire/uberfire/pull/603
=> Moving Social Activities Framework from kie-uberfire-extensions to uberfire-extensions

kie-drools-wb/kie-drools-wb-webapp/src/main/resources/workbench-policy.properties, kie-wb/kie-wb-webapp/src/main/resources/workbench-policy.properties
See https://issues.jboss.org/browse/RHBRMS-2736
This is the corollary of https://github.com/droolsjbpm/kie-wb-distributions/pull/447 for 6.5.x
=> [6.5.x] RHBRMS-2736: [GSS] (6.4.z) Unable to download JAR by Users without admin role

kie-drools-wb/kie-drools-wb-webapp/pom.xml, kie-wb/kie-wb-webapp/pom.xml
Preference API changed, so I needed to make some minor changes here.
Dependes on: https://github.com/uberfire/uberfire/pull/605
=> UF-459: Preferences API Refactor

kie-drools-wb/kie-drools-wb-webapp/pom.xml, kie-wb/kie-wb-webapp/pom.xml
- Added new Forms Annotation Driven Forms dependencies
These PR's should be merged together:
https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/364
https://github.com/droolsjbpm/kie-wb-common/pull/640
https://github.com/droolsjbpm/jbpm-console-ng/pull/609
https://github.com/droolsjbpm/jbpm-designer/pull/533
https://github.com/droolsjbpm/appformer/pull/66
https://github.com/droolsjbpm/kie-wb-distributions/pull/446
=> JBPM-5573: Stunner - Integration of latest KIE Forms API & implementations

kie-drools-wb/kie-drools-wb-webapp/src/main/java/org/kie/workbench/drools/client/navbar/AppNavBar.html, kie-drools-wb/kie-drools-wb-webapp/src/main/java/org/kie/workbench/drools/client/navbar/AppNavBar.java, kie-drools-wb/kie-drools-wb-webapp/src/main/java/org/kie/workbench/drools/client/navbar/LogoNavBar.html, kie-drools-wb/kie-drools-wb-webapp/src/main/java/org/kie/workbench/drools/client/navbar/LogoNavBar.java, kie-drools-wb/kie-drools-wb-webapp/src/main/java/org/kie/workbench/drools/client/navbar/LogoWidgetView.java, kie-wb/kie-wb-webapp/src/main/java/org/kie/workbench/client/navbar/AppNavBar.html, kie-wb/kie-wb-webapp/src/main/java/org/kie/workbench/client/navbar/AppNavBar.java, kie-wb/kie-wb-webapp/src/main/java/org/kie/workbench/client/navbar/LogoNavBar.html, kie-wb/kie-wb-webapp/src/main/java/org/kie/workbench/client/navbar/LogoNavBar.java, kie-wb/kie-wb-webapp/src/main/java/org/kie/workbench/client/navbar/LogoWidgetView.java
Depends on uberfire/uberfire#573
=> [UF-443] - Header and Footer should support Errai UI

kie-wb-tests/kie-wb-tests-gui/src/main/java/org/kie/wb/selenium/model/LoginPage.java, kie-wb-tests/kie-wb-tests-gui/src/main/java/org/kie/wb/selenium/model/Persp.java, kie-wb-tests/kie-wb-tests-gui/src/main/java/org/kie/wb/selenium/model/PrimaryNavbar.java, kie-wb-tests/kie-wb-tests-gui/src/main/java/org/kie/wb/selenium/model/persps/ProjectAuthoringPerspective.java, kie-wb-tests/kie-wb-tests-gui/src/main/java/org/kie/wb/selenium/model/persps/ProjectLibraryPerspective.java, kie-wb-tests/kie-wb-tests-gui/src/main/java/org/kie/wb/selenium/model/persps/authoring/ProjectExplorer.java, kie-wb-tests/kie-wb-tests-gui/src/main/java/org/kie/wb/selenium/model/widgets/ContextNavbar.java, kie-wb-tests/kie-wb-tests-gui/src/main/java/org/kie/wb/selenium/util/BusyPopup.java, kie-wb-tests/kie-wb-tests-gui/src/test/java/org/kie/wb/selenium/ui/LoadAllPerspectivesIntegrationTest.java, kie-wb-tests/kie-wb-tests-gui/src/test/java/org/kie/wb/selenium/ui/LoginIntegrationTest.java, kie-wb-tests/kie-wb-tests-gui/src/test/java/org/kie/wb/selenium/ui/ProjectAuthoringIntegrationTest.java
Commit contains the following changes:
- Divide user logging process in two methods:
1. Just navigate to login page
2. Submit user credentials and login
- Add Library perspective to the list of perspectives being navigated to in test
- Re-factor logic of navigating to Project Editor
- Re-factor ProjectLibraryPerspective
- Re-factor handling of "pop up" panel with a "glass" element behind it
- Fix false positive scenario in LoadAllPerspectivesIntegrationTest
- Introduce @Before and @After methods in ProjectAuthoringIntegrationTest
- Re-factor deployAndCheckArtifact method in ProjectAuthoringIntegrationTest
=> Re-factor kie-wb UI integration tests

pom.xml
See https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/387
=> Plugin version information moved to kie-parent

kie-wb/kie-wb-home-page-community/src/main/java/org/kie/workbench/client/home/HomeProducer.java, kie-wb/kie-wb-home-page-product/src/main/java/org/kie/workbench/client/home/HomeProducer.java, kie-wb/kie-wb-webapp/src/main/java/org/kie/workbench/client/KieWorkbenchEntryPoint.java, kie-wb/kie-wb-webapp/src/main/resources/security-module-user.properties, kie-wb/kie-wb-webapp/src/test/java/org/kie/workbench/security/WorkbenchACLTest.java
depends on https://github.com/droolsjbpm/jbpm-wb/pull/629 and https://github.com/droolsjbpm/kie-wb-common/pull/688 merging
=> JBPM perspectives ids renaming

kie-drools-wb-parent/kie-drools-wb-webapp/pom.xml, kie-wb-parent/kie-wb-webapp/pom.xml
@psiroky can you review this please?
=> JBPM-5857: Missing parser on forms serialization

kie-drools-wb-parent/kie-drools-wb-webapp/pom.xml, kie-drools-wb-parent/kie-drools-wb-webapp/src/main/resources/org/kie/workbench/drools/KIEDroolsWebapp.gwt.xml, kie-wb-parent/kie-wb-webapp/pom.xml, kie-wb-parent/kie-wb-webapp/src/main/resources/org/kie/workbench/KIEWebapp.gwt.xml
- Add definitions of optaplanner-wb-guided-rule-editor modules
Backporting changes from master branch.
Part of:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/431
- https://github.com/kiegroup/drools/pull/1202
- https://github.com/kiegroup/drools-wb/pull/452
- https://github.com/kiegroup/optaplanner-wb/pull/148
- https://github.com/kiegroup/kie-wb-distributions/pull/487
=> [7.0.x] PLANNER-350: Workbench: scoreHolder support in Guided Rule Editor

kie-drools-wb-parent/kie-drools-wb-webapp/src/main/webapp/META-INF/jboss-deployment-structure.xml, kie-wb-parent/kie-wb-webapp/src/main/webapp/META-INF/jboss-deployment-structure.xml
=> [GUVNOR-2997] jms-api required by the kie-server-client

kie-drools-wb-parent/kie-drools-wb-distribution-wars/pom.xml, kie-drools-wb-parent/kie-drools-wb-webapp/pom.xml, kie-drools-wb-parent/kie-drools-wb-webapp/src/main/resources/org/kie/workbench/drools/KIEDroolsWebapp.gwt.xml, kie-wb-parent/kie-wb-home-page-community/pom.xml, kie-wb-parent/kie-wb-webapp/pom.xml, kie-wb-parent/kie-wb-webapp/src/main/resources/org/kie/workbench/KIEWebapp.gwt.xml
@mbiarnes Keep an eye on this.. when this PR is green you can try the same changes for product.
=> [7.0.x] Fix duplicate class build validation failure

kie-drools-wb-parent/kie-drools-wb-webapp/pom.xml, kie-drools-wb-parent/kie-drools-wb-webapp/src/main/resources/org/kie/workbench/drools/KIEDroolsWebapp.gwt.xml, kie-wb-parent/kie-wb-webapp/pom.xml, kie-wb-parent/kie-wb-webapp/src/main/resources/org/kie/workbench/KIEWebapp.gwt.xml
- Add definitions of optaplanner-wb-guided-rule-editor modules
Part of:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/425
https://github.com/kiegroup/drools/pull/1178
https://github.com/kiegroup/drools-wb/pull/433
https://github.com/kiegroup/optaplanner-wb/pull/143
https://github.com/kiegroup/kie-wb-distributions/pull/486
=> PLANNER-350: Workbench: scoreHolder support in Guided Rule Editor

kie-drools-wb-parent/kie-drools-wb-distribution-wars/pom.xml, kie-drools-wb-parent/kie-drools-wb-webapp/pom.xml, kie-drools-wb-parent/kie-drools-wb-webapp/src/main/resources/org/kie/workbench/drools/KIEDroolsWebapp.gwt.xml, kie-wb-parent/kie-wb-home-page-community/pom.xml, kie-wb-parent/kie-wb-webapp/pom.xml, kie-wb-parent/kie-wb-webapp/src/main/resources/org/kie/workbench/KIEWebapp.gwt.xml
Corollary of https://github.com/kiegroup/kie-wb-distributions/pull/491 for master.
=> Fix productization duplicate classes

kie-drools-wb-parent/kie-drools-wb-webapp/src/main/java/org/kie/workbench/drools/client/KieDroolsWorkbenchEntryPoint.java, kie-drools-wb-parent/kie-drools-wb-webapp/src/test/java/org/kie/workbench/drools/client/KieDroolsWorkbenchEntryPointTest.java, kie-wb-parent/kie-wb-webapp/src/main/java/org/kie/workbench/client/KieWorkbenchEntryPoint.java, kie-wb-parent/kie-wb-webapp/src/test/java/org/kie/workbench/client/KieWorkbenchEntryPointTest.java, kie-wb-tests/kie-wb-tests-gui/src/main/java/org/kie/wb/selenium/model/persps/ProjectLibraryPerspective.java, kie-wb-tests/kie-wb-tests-gui/src/test/java/org/kie/wb/selenium/ui/ProjectLibraryIntegrationTest.java
Cherry picked from master (https://github.com/kiegroup/kie-wb-distributions/pull/493).
=> [7.0.x] GUVNOR-3005: Remove search textbox from the menu header

kie-drools-wb-parent/kie-drools-wb-webapp/pom.xml
=> JBPM-5738: Add default configuration for fields that nest forms (added missing deps)

kie-wb-tests/pom.xml
@manstis or @mbiarnes please take a look. This is far from ideal, but at least should fix the build for now.
=> Disable the WB tests (by default) for the productized profile

kie-drools-wb-parent/kie-drools-wb-webapp/src/main/java/org/kie/workbench/drools/client/perspectives/AdministrationPerspective.java, kie-drools-wb-parent/kie-drools-wb-webapp/src/test/java/org/kie/workbench/drools/client/perspectives/AdministrationPerspectiveTest.java, kie-wb-parent/kie-wb-webapp/src/main/java/org/kie/workbench/client/perspectives/AdministrationPerspective.java, kie-wb-parent/kie-wb-webapp/src/test/java/org/kie/workbench/client/perspectives/AdministrationPerspectiveTest.java
Fix + test.
@manstis Can you review it please?
=> JBPM-5660: Cloning repositories is allowed even if create repositories permission is disabled (7.0.x)

kie-drools-wb-parent/kie-drools-wb-webapp/src/main/java/org/kie/workbench/drools/client/perspectives/AdministrationPerspective.java, kie-drools-wb-parent/kie-drools-wb-webapp/src/test/java/org/kie/workbench/drools/client/perspectives/AdministrationPerspectiveTest.java, kie-wb-parent/kie-wb-webapp/src/main/java/org/kie/workbench/client/perspectives/AdministrationPerspective.java, kie-wb-parent/kie-wb-webapp/src/test/java/org/kie/workbench/client/perspectives/AdministrationPerspectiveTest.java
Fix + test.
@manstis Can you review it please?
=> JBPM-5660: Cloning repositories is allowed even if create repositories permission is disabled

kie-drools-wb-parent/kie-drools-wb-webapp/pom.xml, kie-wb-parent/kie-wb-webapp/pom.xml, pom.xml
@etirelli @tarilabs here are the changes to allow DMN assets to be built and deployed from within workbench.
=> JBPM-5963 - DMN assets fails to build in workbench

kie-drools-wb-parent/kie-drools-wb-webapp/src/main/resources/security-module-analyst.properties, kie-drools-wb-parent/kie-drools-wb-webapp/src/test/java/org/kie/workbench/drools/security/WorkbenchACLTest.java, kie-wb-parent/kie-wb-webapp/src/main/resources/security-module-analyst.properties, kie-wb-parent/kie-wb-webapp/src/main/resources/security-module-developer.properties, kie-wb-parent/kie-wb-webapp/src/test/java/org/kie/workbench/security/WorkbenchACLTest.java
@dgutierr Hi David, if you could take a look. Thanks.
=> GUVNOR-3057: Only admins should be able to manage teams

kie-drools-wb-parent/kie-drools-wb-webapp/src/main/resources/security-module-analyst.properties, kie-drools-wb-parent/kie-drools-wb-webapp/src/test/java/org/kie/workbench/drools/security/WorkbenchACLTest.java, kie-wb-parent/kie-wb-webapp/src/main/resources/security-module-analyst.properties, kie-wb-parent/kie-wb-webapp/src/main/resources/security-module-developer.properties, kie-wb-parent/kie-wb-webapp/src/test/java/org/kie/workbench/security/WorkbenchACLTest.java
@dgutierr Hi David, if you could take a look. Thanks.
=> [7.0.x] GUVNOR-3057: Only admins should be able to manage teams

kie-wb-tests/pom.xml
This will allow us to configure deployable artifact version when running tests with QE automation using Maven Invoker Plugin.
=> kie-wb-tests: Enable deployable version config

kie-drools-wb-parent/kie-drools-wb-home-page-product/src/main/resources/org/kie/workbench/drools/client/resources/i18n/HomePageProductConstants.properties, kie-drools-wb-parent/kie-drools-wb-home-page-product/src/main/resources/org/kie/workbench/drools/client/resources/i18n/HomePageProductConstants_de.properties, kie-drools-wb-parent/kie-drools-wb-home-page-product/src/main/resources/org/kie/workbench/drools/client/resources/i18n/HomePageProductConstants_es.properties, kie-drools-wb-parent/kie-drools-wb-home-page-product/src/main/resources/org/kie/workbench/drools/client/resources/i18n/HomePageProductConstants_fr.properties, kie-drools-wb-parent/kie-drools-wb-home-page-product/src/main/resources/org/kie/workbench/drools/client/resources/i18n/HomePageProductConstants_ja.properties, kie-drools-wb-parent/kie-drools-wb-home-page-product/src/main/resources/org/kie/workbench/drools/client/resources/i18n/HomePageProductConstants_pt_BR.properties, kie-drools-wb-parent/kie-drools-wb-home-page-product/src/main/resources/org/kie/workbench/drools/client/resources/i18n/HomePageProductConstants_zh_CN.properties, kie-wb-parent/kie-wb-home-page-product/src/main/resources/org/kie/workbench/client/resources/i18n/HomePageProductConstants.properties, kie-wb-parent/kie-wb-home-page-product/src/main/resources/org/kie/workbench/client/resources/i18n/HomePageProductConstants_de.properties, kie-wb-parent/kie-wb-home-page-product/src/main/resources/org/kie/workbench/client/resources/i18n/HomePageProductConstants_es.properties, kie-wb-parent/kie-wb-home-page-product/src/main/resources/org/kie/workbench/client/resources/i18n/HomePageProductConstants_fr.properties, kie-wb-parent/kie-wb-home-page-product/src/main/resources/org/kie/workbench/client/resources/i18n/HomePageProductConstants_ja.properties, kie-wb-parent/kie-wb-home-page-product/src/main/resources/org/kie/workbench/client/resources/i18n/HomePageProductConstants_pt_BR.properties, kie-wb-parent/kie-wb-home-page-product/src/main/resources/org/kie/workbench/client/resources/i18n/HomePageProductConstants_zh_CN.properties
=> Updated product home page title to v7

kie-drools-wb/kie-drools-wb-webapp/src/main/java/org/kie/workbench/drools/client/perspectives/DroolsAuthoringPerspective.java, kie-drools-wb/kie-drools-wb-webapp/src/test/java/org/kie/workbench/drools/client/perspectives/DroolsAuthoringPerspectiveTest.java, kie-wb/kie-wb-webapp/src/main/java/org/kie/workbench/client/perspectives/DroolsAuthoringPerspective.java, kie-wb/kie-wb-webapp/src/test/java/org/kie/workbench/client/perspectives/DroolsAuthoringPerspectiveTest.java
https://issues.jboss.org/browse/GUVNOR-3095
https://github.com/kiegroup/guvnor/pull/454
https://github.com/kiegroup/kie-wb-distributions/pull/530
=> GUVNOR-3095 : Make 6.4.x Inbox optional

kie-drools-wb-parent/kie-drools-wb-distribution-wars/src/main/productized/WEB-INF/classes/security-management.properties, kie-wb-parent/kie-wb-distribution-wars/src/main/productized/WEB-INF/classes/security-management.properties
Some comments changed in the users & groups management configuration files for the productized profile.
=> Fixied comments in the user and group management configuration files.

kie-wb/kie-wb-webapp/src/main/webapp/rest-api.jsp
See: https://github.com/kiegroup/droolsjbpm-integration/pull/991
=> [6.5.x] RHBPMS-4687: Update the REST API documentation to fix the 'RestApiJspTest'

kie-drools-wb-parent/kie-drools-wb-webapp/pom.xml, kie-wb-parent/kie-wb-webapp/pom.xml
depends on AppFormer/uberfire#740
=> AF-527: aded new appformer maven support artifact for gwt build

kie-wb-parent/kie-wb-distribution-wars/src/main/productized/assembly-kie-wb-eap-7-redhat.xml, kie-wb-tests/README.md, kie-wb-tests/kie-wb-tests-gui/pom.xml, kie-wb-tests/kie-wb-tests-rest/pom.xml, kie-wb-tests/pom.xml
=> Make it possible to execute tests on productized *-redhat.wars

kie-drools-wb-parent/kie-drools-wb-home-page-community/src/main/java/org/kie/workbench/drools/client/home/HomeProducer.java, kie-drools-wb-parent/kie-drools-wb-home-page-product/src/main/java/org/kie/workbench/drools/client/home/HomeProducer.java, kie-drools-wb-parent/kie-drools-wb-webapp/src/main/java/org/kie/workbench/drools/client/KieDroolsWorkbenchEntryPoint.java, kie-drools-wb-parent/kie-drools-wb-webapp/src/test/java/org/kie/workbench/drools/client/KieDroolsWorkbenchEntryPointTest.java, kie-wb-parent/kie-wb-webapp/src/main/java/org/kie/workbench/client/KieWorkbenchEntryPoint.java, kie-wb-parent/kie-wb-webapp/src/test/java/org/kie/workbench/client/KieWorkbenchEntryPointTest.java
* Make HomeModel producer lazy
* Remove PlaceManagerActivityService
=> AF-546: Reduce startup time of AppFormer apps and workbenches

kie-drools-wb-parent/kie-drools-wb-distribution-wars/src/main/assembly/tomcat8/WEB-INF/web.xml, kie-drools-wb-parent/kie-drools-wb-webapp/src/main/resources/ErraiApp.properties, kie-drools-wb-parent/kie-drools-wb-webapp/src/main/webapp/WEB-INF/web.xml, kie-wb-parent/kie-wb-distribution-wars/src/main/assembly/tomcat8/WEB-INF/web.xml, kie-wb-parent/kie-wb-webapp/src/main/resources/ErraiApp.properties, kie-wb-parent/kie-wb-webapp/src/main/webapp/WEB-INF/web.xml
@mbarkley could you please confirm this is all we need?
=> [GUVNOR-3280] enable Errai bus CSRF protection

kie-wb-distribution-home/kie-wb-distribution-home-api/src/main/java/org/kie/workbench/common/screens/home/model/HomeModel.java
@manstis Could you please review/merge this?
=> GUVNOR-3321: Fix unproxiable HomeModel in productized build

kie-drools-wb-parent/kie-drools-wb-webapp/src/main/resources/ErraiApp.properties, kie-drools-wb-parent/kie-drools-wb-webapp/src/main/resources/ErraiService.properties, kie-wb-parent/kie-wb-webapp/src/main/resources/ErraiApp.properties, kie-wb-parent/kie-wb-webapp/src/main/resources/ErraiService.properties
=> [GUVNOR-3280] move CSRF property to ErraiService.properties

kie-wb-tests/kie-wb-tests-rest/src/main/java/org/kie/wb/test/rest/client/RestWorkbenchClient.java, kie-wb-tests/kie-wb-tests-rest/src/main/java/org/kie/wb/test/rest/client/WorkbenchClient.java
Cherrypick of https://github.com/kiegroup/kie-wb-distributions/pull/562
=> [7.2.x] Extend workbench client creation methods

kie-drools-wb-parent/kie-drools-wb-webapp/pom.xml, kie-drools-wb-parent/kie-drools-wb-webapp/src/main/resources/org/kie/workbench/drools/KIEDroolsWebapp.gwt.xml, kie-wb-parent/kie-wb-webapp/pom.xml, kie-wb-parent/kie-wb-webapp/src/main/resources/org/kie/workbench/KIEWebapp.gwt.xml
This changes are introduced by: kiegroup/kie-wb-common#1009
@manstis @jsoltes  could you review?
This PR is part of an ensemble, please merge with:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/490
https://github.com/kiegroup/kie-wb-common/pull/1009
https://github.com/kiegroup/drools-wb/pull/561
https://github.com/kiegroup/optaplanner-wb/pull/192
https://github.com/kiegroup/kie-wb-distributions/pull/563
https://github.com/kiegroup/jbpm-wb/pull/817
https://github.com/kiegroup/jbpm-form-modeler/pull/128
=> [7.2.x] JBPM-5531: Problems after deleting a form that is used as a subform in other form.

kie-drools-wb-parent/kie-drools-wb-webapp/pom.xml, kie-drools-wb-parent/kie-drools-wb-webapp/src/main/resources/org/kie/workbench/drools/KIEDroolsWebapp.gwt.xml, kie-wb-parent/kie-wb-webapp/pom.xml, kie-wb-parent/kie-wb-webapp/src/main/resources/org/kie/workbench/KIEWebapp.gwt.xml
Copy of https://github.com/kiegroup/kie-wb-distributions/pull/563
@manstis @jsoltes could you review?
This PR is part of an ensemble, please merge with:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/508
https://github.com/kiegroup/kie-wb-common/pull/1069
https://github.com/kiegroup/drools-wb/pull/576
https://github.com/kiegroup/optaplanner-wb/pull/201
https://github.com/kiegroup/jbpm-wb/pull/844
https://github.com/kiegroup/kie-wb-distributions/pull/581
https://github.com/kiegroup/jbpm-form-modeler/pull/132
=> [7.3.x] JBPM-5531: Problems after deleting a form that is used as a subform in other form.

kie-drools-wb-parent/kie-drools-wb-distribution-wars/src/main/assembly/tomcat8/WEB-INF/web.xml, kie-drools-wb-parent/kie-drools-wb-webapp/src/main/webapp/WEB-INF/web.xml, kie-wb-parent/kie-wb-distribution-wars/src/main/assembly/tomcat8/WEB-INF/web.xml, kie-wb-parent/kie-wb-webapp/src/main/webapp/WEB-INF/web.xml
@manstis I'm fairly certain this will fix the build issue with Tomcat caused by my previous PR.
@psiroky Is there a quick way to test this? I don't have Tomcat setup locally.
=> Remove double '*' pattern (doesn't work in Tomcat).

kie-drools-wb-parent/kie-drools-wb-webapp/pom.xml, kie-wb-parent/kie-wb-webapp/pom.xml
related prs:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/510
https://github.com/kiegroup/jbpm/pull/945
=> JBPM-6310 - update to jbpm-workitems module

kie-drools-wb-parent/kie-drools-wb-webapp/pom.xml, kie-wb-parent/kie-wb-webapp/pom.xml
@mswiderski: port to 7.3.x (with fixed branch name :) )
=> [7.3.x] JBPM-6310 - update to jbpm-workitems module (#586)

kie-wb-tests/kie-wb-tests-gui/src/main/java/org/kie/wb/selenium/model/Persp.java
* Apps is now only accessible through the "Track > Business Dashboards" menu.
=> Mega Menu adjusts

kie-drools-wb-parent/kie-drools-wb-webapp/pom.xml, kie-wb-parent/kie-wb-webapp/pom.xml
(cherry picked from commit 6af38c18e58ae1cbc441b666a25fdc22e95abdd3)
=> GUVNOR-3404: Openshift Provider Integration + UI integration (#606)

kie-drools-wb-parent/kie-drools-wb-webapp/pom.xml, kie-drools-wb-parent/kie-drools-wb-webapp/src/main/resources/org/kie/workbench/drools/KIEDroolsWebapp.gwt.xml, kie-wb-parent/kie-wb-webapp/pom.xml, kie-wb-parent/kie-wb-webapp/src/main/resources/org/kie/workbench/KIEWebapp.gwt.xml
Copy of https://github.com/kiegroup/kie-wb-distributions/pull/563
@manstis @jsoltes could you review?
This PR is part of an ensemble, please merge with:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/493
https://github.com/kiegroup/kie-wb-common/pull/1011
https://github.com/kiegroup/drools-wb/pull/564
https://github.com/kiegroup/optaplanner-wb/pull/193
https://github.com/kiegroup/jbpm-wb/pull/819
https://github.com/kiegroup/kie-wb-distributions/pull/565
https://github.com/kiegroup/jbpm-form-modeler/pull/126
=> [8.0.x] JBPM-5531: Problems after deleting a form that is used as a subform in other form.

kie-wb-tests/kie-wb-tests-gui/src/main/java/org/kie/wb/selenium/model/persps/ProjectLibraryPerspective.java, kie-wb-tests/kie-wb-tests-gui/src/main/java/org/kie/wb/selenium/model/persps/authoring/ImportExampleModal.java, kie-wb-tests/kie-wb-tests-gui/src/test/java/org/kie/wb/selenium/ui/ProjectLibraryIntegrationTest.java
7.3.x equivalent of https://github.com/kiegroup/kie-wb-distributions/pull/616
=> [7.3.x] Fix tests after org unit input removal (Examples modal)

kie-wb-tests/kie-wb-tests-gui/src/main/java/org/kie/wb/selenium/model/persps/ProjectLibraryPerspective.java, kie-wb-tests/kie-wb-tests-gui/src/main/java/org/kie/wb/selenium/model/persps/authoring/ImportExampleModal.java, kie-wb-tests/kie-wb-tests-gui/src/test/java/org/kie/wb/selenium/ui/ProjectLibraryIntegrationTest.java
Fix selenium tests after recent Example modal refactoring 
@mcimbora @manstis check and be aware
=> Fix tests after org unit input removal (Examples modal)

kie-wb-parent/kie-wb-runtime-webapp/pom.xml, kie-wb-parent/kie-wb-runtime-webapp/sample-swarm-config.yml, kie-wb-parent/kie-wb-webapp/pom.xml, kie-wb-parent/pom.xml
Adding https://github.com/kiegroup/kie-wb-distributions/pull/608 into master
=> JBPM-6148 - Add swarm profile to runtime war

kie-drools-wb-parent/kie-drools-wb-webapp/src/main/resources/security-policy.properties, kie-wb-parent/kie-wb-webapp/src/main/resources/security-policy.properties
See https://issues.jboss.org/browse/GUVNOR-3200
---
---
- https://github.com/AppFormer/uberfire/pull/861
- https://github.com/kiegroup/kie-wb-common/pull/1190
- https://github.com/kiegroup/drools-wb/pull/636
- https://github.com/kiegroup/kie-wb-distributions/pull/628
- https://github.com/kiegroup/kie-docs/pull/402
=> GUVNOR-3200: [Guided Decision Table] Access control to prohibit business users from modifying columns

kie-drools-wb-parent/kie-drools-wb-webapp/src/main/resources/security-policy.properties, kie-wb-parent/kie-wb-webapp/src/main/resources/security-policy.properties
See https://issues.jboss.org/browse/GUVNOR-3200
---
Cherry-picked from https://github.com/kiegroup/kie-wb-distributions/pull/628
---
- https://github.com/AppFormer/uberfire/pull/863
- https://github.com/kiegroup/kie-docs/pull/407
- https://github.com/kiegroup/kie-wb-distributions/pull/634
- https://github.com/kiegroup/drools-wb/pull/644
- https://github.com/kiegroup/kie-wb-common/pull/1222
=> [7.3.x] GUVNOR-3200: [Guided Decision Table] Access control to prohibit business users from modifying columns

kie-drools-wb-parent/kie-drools-wb-webapp/pom.xml, kie-wb-parent/kie-wb-webapp/pom.xml
See https://issues.jboss.org/browse/DROOLS-2076
=> DROOLS-2076: [DataModelOracle] DSL Sentences are not loaded

kie-drools-wb-parent/kie-drools-wb-webapp/src/test/java/org/kie/workbench/drools/client/KieDroolsWorkbenchEntryPointTest.java, kie-wb-parent/kie-wb-webapp/src/test/java/org/kie/workbench/client/KieWorkbenchEntryPointTest.java
See: https://issues.jboss.org/browse/RHDM-219
---
- https://github.com/kiegroup/appformer/pull/134
- https://github.com/kiegroup/kie-wb-distributions/pull/668
=> [7.5.x] [Content Management] HTML panel causes errors when saving & when adding page to navigation tree

kie-drools-wb-parent/kie-drools-wb-webapp/src/test/java/org/kie/workbench/drools/client/KieDroolsWorkbenchEntryPointTest.java, kie-wb-parent/kie-wb-webapp/src/test/java/org/kie/workbench/client/KieWorkbenchEntryPointTest.java
Cherry picked from https://github.com/kiegroup/kie-wb-distributions/pull/668
---
- https://github.com/kiegroup/appformer/pull/140
- https://github.com/kiegroup/kie-wb-distributions/pull/669
=> RHDM-219: [Content Management] HTML panel causes errors when saving & when adding page to navigation tree

kie-drools-wb-parent/kie-drools-wb-home-page-community/src/main/java/org/kie/workbench/drools/client/home/HomeProducer.java, kie-drools-wb-parent/kie-drools-wb-home-page-community/src/main/java/org/kie/workbench/drools/client/resources/i18n/Constants.java, kie-drools-wb-parent/kie-drools-wb-home-page-community/src/main/resources/org/kie/workbench/drools/client/resources/i18n/Constants.properties, kie-drools-wb-parent/kie-drools-wb-home-page-community/src/test/java/org/kie/workbench/drools/client/home/HomeProducerTest.java, kie-drools-wb-parent/kie-drools-wb-home-page-product/src/main/java/org/kie/workbench/drools/client/home/HomeProducer.java, kie-drools-wb-parent/kie-drools-wb-home-page-product/src/main/java/org/kie/workbench/drools/client/resources/i18n/Constants.java, kie-drools-wb-parent/kie-drools-wb-home-page-product/src/main/resources/org/kie/workbench/drools/client/resources/i18n/Constants.properties, kie-drools-wb-parent/kie-drools-wb-home-page-product/src/test/java/org/kie/workbench/drools/client/home/HomeProducerTest.java, kie-drools-wb-parent/kie-drools-wb-webapp/src/main/java/org/kie/workbench/drools/client/KieDroolsWorkbenchEntryPoint.java, kie-drools-wb-parent/kie-drools-wb-webapp/src/main/java/org/kie/workbench/drools/client/navigation/NavTreeDefinitions.java, kie-drools-wb-parent/kie-drools-wb-webapp/src/main/java/org/kie/workbench/drools/client/resources/i18n/NavigationConstants.java, kie-drools-wb-parent/kie-drools-wb-webapp/src/main/resources/org/kie/workbench/drools/client/resources/i18n/NavigationConstants.properties, kie-drools-wb-parent/kie-drools-wb-webapp/src/test/java/org/kie/workbench/drools/client/KieDroolsWorkbenchEntryPointTest.java, kie-drools-wb-parent/kie-drools-wb-webapp/src/test/java/org/kie/workbench/drools/client/navigation/NavTreeDefinitionsTest.java
Fix + tests.
@manstis Can you review please?
=> RHDM-271: Disable CMS perspective in RHDM

kie-drools-wb-parent/kie-drools-wb-home-page-product/src/test/java/org/kie/workbench/drools/client/home/HomeProducerTest.java, kie-wb-parent/kie-wb-home-page-community/src/test/java/org/kie/workbench/client/home/HomeProducerTest.java, kie-wb-parent/kie-wb-home-page-community/src/test/java/org/kie/workbench/client/home/HomeRuntimeProducerTest.java, kie-wb-parent/kie-wb-home-page-product/src/main/java/org/kie/workbench/client/home/HomeRuntimeProducer.java, kie-wb-parent/kie-wb-home-page-product/src/test/java/org/kie/workbench/client/home/HomeProducerTest.java, kie-wb-parent/kie-wb-home-page-product/src/test/java/org/kie/workbench/client/home/HomeRuntimeProducerTest.java
Fixed the tests for the productized profile.
@pszubiak Can you verify please?
=> RHDM-271: Disable CMS perspective in RHDM (fix productized profile)

kie-drools-wb-parent/kie-drools-wb-webapp/src/main/java/org/kie/workbench/drools/client/KieDroolsWorkbenchEntryPoint.java, kie-drools-wb-parent/kie-drools-wb-webapp/src/test/java/org/kie/workbench/drools/client/KieDroolsWorkbenchEntryPointTest.java, kie-wb-parent/kie-wb-monitoring-webapp/src/main/java/org/kie/workbench/client/KieWorkbenchEntryPoint.java, kie-wb-parent/kie-wb-monitoring-webapp/src/test/java/org/kie/workbench/client/KieWorkbenchEntryPointTest.java, kie-wb-parent/kie-wb-webapp/pom.xml, kie-wb-parent/kie-wb-webapp/src/main/java/org/kie/workbench/client/KieWorkbenchEntryPoint.java, kie-wb-parent/kie-wb-webapp/src/test/java/org/kie/workbench/client/KieWorkbenchEntryPointTest.java
Changes required by kiegroup/appformer#125
Do not merge yet.
=> AF-930: [Layout Editor] Use dock panels to increase the editor content area

kie-drools-wb-parent/kie-drools-wb-distribution-wars/pom.xml, kie-drools-wb-parent/kie-drools-wb-distribution-wars/src/main/assembly/component-kie-drools-wb-swarm-common.xml, kie-drools-wb-parent/kie-drools-wb-distribution-wars/src/main/productized/assembly-kie-drools-wb-swarm-redhat.xml, kie-wb-parent/kie-wb-distribution-wars/kie-wb/pom.xml, kie-wb-parent/kie-wb-distribution-wars/src/main/assembly/component-kie-wb-swarm-common.xml, kie-wb-parent/kie-wb-distribution-wars/src/main/productized/assembly-kie-wb-swarm-redhat.xml
https://issues.jboss.org/browse/RHDM-344
https://issues.jboss.org/browse/DROOLS-2314
Bundle:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/707
https://github.com/kiegroup/kie-wb-distributions/pull/688
=> DROOLS-2314 : Standalone decision central is not branded 

kie-drools-wb/kie-drools-wb-distribution-wars/src/main/assembly/tomcat7/WEB-INF/web.xml, kie-drools-wb/kie-drools-wb-distribution-wars/src/main/assembly/was8/WEB-INF/web.xml, kie-drools-wb/kie-drools-wb-distribution-wars/src/main/assembly/weblogic12/WEB-INF/web.xml, kie-drools-wb/kie-drools-wb-webapp/src/main/webapp/WEB-INF/web.xml, kie-wb/kie-wb-distribution-wars/src/main/assembly/eap6_4/WEB-INF/web-ui-server.xml, kie-wb/kie-wb-distribution-wars/src/main/assembly/tomcat7/WEB-INF/web-ui-server.xml, kie-wb/kie-wb-distribution-wars/src/main/assembly/tomcat7/WEB-INF/web.xml, kie-wb/kie-wb-distribution-wars/src/main/assembly/was8/WEB-INF/web-ui-server.xml, kie-wb/kie-wb-distribution-wars/src/main/assembly/was8/WEB-INF/web.xml, kie-wb/kie-wb-distribution-wars/src/main/assembly/weblogic12/WEB-INF/web-ui-server.xml, kie-wb/kie-wb-distribution-wars/src/main/assembly/weblogic12/WEB-INF/web.xml, kie-wb/kie-wb-distribution-wars/src/main/assembly/wildfly10-eap7/WEB-INF/web-ui-server.xml, kie-wb/kie-wb-webapp/src/main/webapp/WEB-INF/web.xml
https://issues.jboss.org/browse/AF-1037
https://github.com/kiegroup/guvnor/pull/535
https://github.com/kiegroup/drools-wb/pull/816
https://github.com/kiegroup/optaplanner-wb/pull/257
https://github.com/kiegroup/kie-tests/pull/17
https://github.com/kiegroup/kie-wb-distributions/pull/694
=> [6.5.x] AF-1037 : Business-central maven artifacts available at maven2wb without authorization

kie-wb-tests/kie-wb-tests-gui/src/main/java/org/kie/wb/selenium/model/persps/ProjectLibraryPerspective.java
Related to:
https://github.com/kiegroup/appformer/pull/116
https://github.com/kiegroup/kie-wb-common/pull/1317
https://github.com/kiegroup/drools-wb/pull/727
https://github.com/kiegroup/jbpm-designer/pull/728
https://github.com/kiegroup/kie-wb-distributions/pull/664
=> WIP [AF-913]: Modified selenium tests to accept the new screen

kie-drools-wb-parent/kie-drools-wb-distribution-wars/src/main/assembly/tomcat8/WEB-INF/web.xml, kie-drools-wb-parent/kie-drools-wb-webapp/src/main/webapp/WEB-INF/web.xml, kie-wb-parent/kie-wb-distribution-wars/src/main/assembly/tomcat8/WEB-INF/web.xml, kie-wb-parent/kie-wb-monitoring-webapp/src/main/webapp/WEB-INF/web.xml, kie-wb-parent/kie-wb-webapp/src/main/webapp/WEB-INF/web.xml
https://issues.jboss.org/browse/AF-1037
https://github.com/kiegroup/appformer/pull/199
https://github.com/kiegroup/kie-docs/pull/694
https://github.com/kiegroup/optaplanner-wb/pull/258
https://github.com/kiegroup/drools-wb/pull/817
https://github.com/kiegroup/kie-tests/pull/18
https://github.com/kiegroup/kie-wb-distributions/pull/695
=> AF-1037 : Business-central maven artifacts available at maven2wb without authorization

kie-drools-wb-parent/kie-drools-wb-distribution-wars/src/main/assembly/tomcat8/WEB-INF/web.xml, kie-drools-wb-parent/kie-drools-wb-webapp/src/main/webapp/WEB-INF/web.xml, kie-wb-parent/kie-wb-distribution-wars/src/main/assembly/tomcat8/WEB-INF/web.xml, kie-wb-parent/kie-wb-monitoring-webapp/src/main/webapp/WEB-INF/web.xml, kie-wb-parent/kie-wb-webapp/src/main/webapp/WEB-INF/web.xml
https://issues.jboss.org/browse/AF-1037
https://github.com/kiegroup/appformer/pull/200
https://github.com/kiegroup/kie-docs/pull/695
https://github.com/kiegroup/optaplanner-wb/pull/259
https://github.com/kiegroup/drools-wb/pull/818
https://github.com/kiegroup/kie-wb-distributions/pull/696
(cherry picked from commit c7628befb8019d7dc4d814e35b5f17212ccf2a52)
=> [7.5.x] AF-1037 : Business-central maven artifacts available at maven2wb without authorization

kie-wb-parent/kie-wb-home-page-community/src/main/java/org/kie/workbench/client/home/AbstractHomeProducer.java, kie-wb-parent/kie-wb-home-page-community/src/main/java/org/kie/workbench/client/resources/i18n/Constants.java, kie-wb-parent/kie-wb-home-page-community/src/main/resources/org/kie/workbench/client/resources/i18n/Constants.properties, kie-wb-parent/kie-wb-home-page-community/src/test/java/org/kie/workbench/client/home/HomeProducerTest.java, kie-wb-parent/kie-wb-home-page-product/src/main/java/org/kie/workbench/client/home/AbstractHomeProducer.java, kie-wb-parent/kie-wb-home-page-product/src/main/java/org/kie/workbench/client/resources/i18n/Constants.java, kie-wb-parent/kie-wb-home-page-product/src/main/resources/org/kie/workbench/client/resources/i18n/Constants.properties, kie-wb-parent/kie-wb-home-page-product/src/test/java/org/kie/workbench/client/home/HomeProducerTest.java, kie-wb-parent/kie-wb-monitoring-webapp/src/main/java/org/kie/workbench/client/navigation/NavTreeDefinitions.java, kie-wb-parent/kie-wb-monitoring-webapp/src/main/java/org/kie/workbench/client/resources/i18n/NavigationConstants.java, kie-wb-parent/kie-wb-monitoring-webapp/src/main/resources/org/kie/workbench/client/resources/i18n/NavigationConstants.properties, kie-wb-parent/kie-wb-webapp/src/main/java/org/kie/workbench/client/navigation/NavTreeDefinitions.java, kie-wb-parent/kie-wb-webapp/src/main/java/org/kie/workbench/client/resources/i18n/NavigationConstants.java, kie-wb-parent/kie-wb-webapp/src/main/resources/org/kie/workbench/client/resources/i18n/NavigationConstants.properties
Depends on:
- https://github.com/kiegroup/jbpm-wb/pull/986
- https://github.com/kiegroup/kie-wb-common/pull/1452
=> JBPM-6887 - Rename Task Lists to Task Inbox

kie-wb-parent/kie-wb-home-page-community/src/main/java/org/kie/workbench/client/home/AbstractHomeProducer.java, kie-wb-parent/kie-wb-home-page-community/src/main/java/org/kie/workbench/client/resources/i18n/Constants.java, kie-wb-parent/kie-wb-home-page-community/src/main/resources/org/kie/workbench/client/resources/i18n/Constants.properties, kie-wb-parent/kie-wb-home-page-community/src/test/java/org/kie/workbench/client/home/HomeProducerTest.java, kie-wb-parent/kie-wb-home-page-product/src/main/java/org/kie/workbench/client/home/AbstractHomeProducer.java, kie-wb-parent/kie-wb-home-page-product/src/main/java/org/kie/workbench/client/resources/i18n/Constants.java, kie-wb-parent/kie-wb-home-page-product/src/main/resources/org/kie/workbench/client/resources/i18n/Constants.properties, kie-wb-parent/kie-wb-home-page-product/src/test/java/org/kie/workbench/client/home/HomeProducerTest.java, kie-wb-parent/kie-wb-monitoring-webapp/src/main/java/org/kie/workbench/client/navigation/NavTreeDefinitions.java, kie-wb-parent/kie-wb-monitoring-webapp/src/main/java/org/kie/workbench/client/resources/i18n/NavigationConstants.java, kie-wb-parent/kie-wb-monitoring-webapp/src/main/resources/org/kie/workbench/client/resources/i18n/NavigationConstants.properties, kie-wb-parent/kie-wb-monitoring-webapp/src/main/resources/security-module-manager.properties, kie-wb-parent/kie-wb-monitoring-webapp/src/main/resources/security-module-process-admin.properties, kie-wb-parent/kie-wb-monitoring-webapp/src/main/resources/security-module-user.properties, kie-wb-parent/kie-wb-monitoring-webapp/src/test/java/org/kie/workbench/client/KieWorkbenchEntryPointTest.java, kie-wb-parent/kie-wb-monitoring-webapp/src/test/java/org/kie/workbench/security/WorkbenchACLTest.java, kie-wb-parent/kie-wb-webapp/src/main/java/org/kie/workbench/client/navigation/NavTreeDefinitions.java, kie-wb-parent/kie-wb-webapp/src/main/java/org/kie/workbench/client/resources/i18n/NavigationConstants.java, kie-wb-parent/kie-wb-webapp/src/main/resources/org/kie/workbench/client/resources/i18n/NavigationConstants.properties, kie-wb-parent/kie-wb-webapp/src/main/resources/security-module-manager.properties, kie-wb-parent/kie-wb-webapp/src/main/resources/security-module-process-admin.properties, kie-wb-parent/kie-wb-webapp/src/main/resources/security-module-user.properties, kie-wb-parent/kie-wb-webapp/src/test/java/org/kie/workbench/client/KieWorkbenchEntryPointTest.java, kie-wb-parent/kie-wb-webapp/src/test/java/org/kie/workbench/security/WorkbenchACLTest.java, kie-wb-tests/kie-wb-tests-gui/src/main/java/org/kie/wb/selenium/model/Persp.java, kie-wb-tests/kie-wb-tests-gui/src/main/java/org/kie/wb/selenium/model/persps/ProcessDashboardPerspective.java, kie-wb-tests/kie-wb-tests-gui/src/main/java/org/kie/wb/selenium/model/persps/TaskDashboardPerspective.java
Depends on:
- https://github.com/kiegroup/kie-wb-common/pull/1451
- https://github.com/kiegroup/jbpm-wb/pull/987
=> JBPM-6885 - Split Task & Process Dashboard tabs into separated screens

kie-drools-wb-parent/kie-drools-wb-webapp/pom.xml, kie-wb-parent/kie-wb-webapp/pom.xml
Hello @romartin @hasys would you mind review this PR?
Thanks.
depends on:
https://github.com/kiegroup/appformer/pull/241
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/721
https://github.com/kiegroup/kie-wb-common/pull/1504
https://github.com/kiegroup/jbpm-wb/pull/995
=> JBPM-6876: Stunner - easy way to migrate from Stunner to current Designer

kie-wb-parent/kie-wb-monitoring-webapp/pom.xml, kie-wb-parent/kie-wb-webapp/pom.xml
Fixed dependencies.
@Rikkola @kkufova could you please take a look?
This PR is part of an ensemble, merge with:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/720
https://github.com/kiegroup/kie-wb-common/pull/1492
https://github.com/kiegroup/jbpm-designer/pull/754
https://github.com/kiegroup/jbpm-wb/pull/993
https://github.com/kiegroup/kie-wb-distributions/pull/704
=> BAPL-764-migration-tool: Provide migration path from old Form Modeler to the new one

kie-drools-wb-parent/kie-drools-wb-webapp/pom.xml, kie-drools-wb-parent/kie-drools-wb-webapp/src/main/resources/org/kie/workbench/drools/KIEDroolsWebapp.gwt.xml, kie-wb-parent/kie-wb-webapp/pom.xml, kie-wb-parent/kie-wb-webapp/src/main/resources/org/kie/workbench/KIEWebapp.gwt.xml
https://github.com/kiegroup/appformer/pull/247
https://github.com/kiegroup/kie-wb-common/pull/1511
https://github.com/kiegroup/kie-wb-distributions/pull/709
https://github.com/kiegroup/drools-wb/pull/832
=> [AF-1074]: Removed unused OrganizationalUnitManager View that made connected clients crash.

kie-drools-wb-parent/kie-drools-wb-webapp/src/main/java/org/kie/workbench/drools/client/KieDroolsWorkbenchEntryPoint.java, kie-drools-wb-parent/kie-drools-wb-webapp/src/test/java/org/kie/workbench/drools/client/KieDroolsWorkbenchEntryPointTest.java, kie-wb-parent/kie-wb-monitoring-webapp/src/main/java/org/kie/workbench/client/KieWorkbenchEntryPoint.java, kie-wb-parent/kie-wb-monitoring-webapp/src/test/java/org/kie/workbench/client/KieWorkbenchEntryPointTest.java, kie-wb-parent/kie-wb-webapp/src/main/java/org/kie/workbench/client/KieWorkbenchEntryPoint.java, kie-wb-parent/kie-wb-webapp/src/test/java/org/kie/workbench/client/KieWorkbenchEntryPointTest.java
=> [7.7.x] JBPM-7003 - Update page size selector style to match PatternFly dropdown

kie-wb-parent/kie-wb-monitoring-webapp/src/main/java/org/kie/workbench/client/navigation/NavTreeDefinitions.java, kie-wb-parent/kie-wb-monitoring-webapp/src/test/java/org/kie/workbench/client/KieWorkbenchEntryPointTest.java, kie-wb-parent/kie-wb-webapp/src/main/java/org/kie/workbench/client/navigation/NavTreeDefinitions.java, kie-wb-parent/kie-wb-webapp/src/test/java/org/kie/workbench/client/KieWorkbenchEntryPointTest.java
@manstis @kkufova Backport from master of https://github.com/kiegroup/kie-wb-distributions/pull/713
=> [7.7.x] JBPM-7034: deleting Pages perspective -> unable to return it back

kie-wb-parent/kie-wb-monitoring-webapp/src/main/java/org/kie/workbench/client/KieWorkbenchEntryPoint.java
This is ensemble together with:
- #728 
- https://github.com/kiegroup/kie-wb-common/pull/1572
=> RHBA-524: Rename Library to Projects

kie-wb-parent/kie-wb-monitoring-webapp/src/main/java/org/kie/workbench/client/KieWorkbenchEntryPoint.java
This is cherry-pick of #728 
@paulovmr please, wold you mind have a look?
=> [7.7.x] RHBA-524: Rename Library to Projects

kie-wb-parent/kie-wb-monitoring-webapp/src/main/java/org/kie/workbench/client/navigation/NavTreeDefinitions.java, kie-wb-parent/kie-wb-monitoring-webapp/src/test/java/org/kie/workbench/client/KieWorkbenchEntryPointTest.java, kie-wb-parent/kie-wb-webapp/src/main/java/org/kie/workbench/client/navigation/NavTreeDefinitions.java, kie-wb-parent/kie-wb-webapp/src/test/java/org/kie/workbench/client/KieWorkbenchEntryPointTest.java
@kkufova  Can you review please?
=> JBPM-7034: deleting Pages perspective -> unable to return it back

kie-wb-tests/kie-wb-tests-gui/src/main/java/org/kie/wb/selenium/model/Persp.java
@manstis could you please merge? Same reason as in https://github.com/kiegroup/kie-wb-distributions/commit/5e5e278109d303de9bc29f6cf47089fde486a60e
=> [7.7.x] Disable Pages persp. in selenium tests of kie-drools-wb

kie-wb-tests/kie-wb-tests-gui/src/main/java/org/kie/wb/selenium/model/Persp.java
@manstis could you please merge? Same reason as in https://github.com/kiegroup/kie-wb-distributions/commit/5e5e278109d303de9bc29f6cf47089fde486a60e
=> Disable Pages persp. in selenium tests of kie-drools-wb

kie-wb-parent/kie-wb-monitoring-webapp/src/main/resources/security-module-user.properties, kie-wb-parent/kie-wb-webapp/src/main/resources/security-module-user.properties
See https://issues.jboss.org/browse/AF-1136
I couldn't reproduce the exact error from the JIRA but this PR fixes the blank screen that appears when logging in as role 'user'.
=> AF-1136: Error after logging in as role user

kie-drools-wb-parent/kie-drools-wb-distribution-wars/src/main/productized/resources/security-policy.properties, kie-wb-parent/kie-wb-distribution-wars/kie-wb/src/main/productized/resources/security-policy.properties
@manstis @romartin could you please take a look?
https://github.com/kiegroup/kie-wb-common/pull/1759
https://github.com/kiegroup/jbpm-designer/pull/781
https://github.com/kiegroup/kie-wb-distributions/pull/746
=> [7.7.x] JBPM-7148: [Workbench] Enable and make Stunner the default process editor

kie-drools-wb-parent/kie-drools-wb-distribution-wars/src/main/productized/resources/security-policy.properties, kie-wb-parent/kie-wb-distribution-wars/kie-wb/src/main/productized/resources/security-policy.properties
@manstis @romartin could you please take a look?
https://github.com/kiegroup/kie-wb-common/pull/1758
https://github.com/kiegroup/jbpm-designer/pull/780
https://github.com/kiegroup/kie-wb-distributions/pull/747
=> JBPM-7148: [Workbench] Enable and make Stunner the default process editor

kie-wb-parent/kie-wb-monitoring-webapp/src/main/java/org/kie/workbench/client/KieWorkbenchEntryPoint.java, kie-wb-parent/kie-wb-monitoring-webapp/src/test/java/org/kie/workbench/client/KieWorkbenchEntryPointTest.java
Assembly:
- https://github.com/kiegroup/kie-wb-common/pull/1875
- https://github.com/kiegroup/kie-wb-distributions/pull/768
=> JBPM-7322 - Remove form settings from KIE Workbench Runtime

kie-wb-parent/kie-wb-monitoring-webapp/src/main/java/org/kie/workbench/client/KieWorkbenchEntryPoint.java, kie-wb-parent/kie-wb-monitoring-webapp/src/test/java/org/kie/workbench/client/KieWorkbenchEntryPointTest.java
Assembly:
- https://github.com/kiegroup/kie-wb-common/pull/1897
- https://github.com/kiegroup/kie-wb-distributions/pull/769
=> RHPAM-1129 - Remove form settings from KIE Workbench Runtime

kie-server-distributions/.gitignore, kie-server-distributions/jbpm-server-distribution/.gitignore, kie-server-distributions/jbpm-server-distribution/README.txt, kie-server-distributions/jbpm-server-distribution/pom.xml, kie-server-distributions/jbpm-server-distribution/src/main/assembly/assembly-server-dist.xml, kie-server-distributions/jbpm-server-distribution/src/main/deployment/jbpm-console.war.deployed, kie-server-distributions/jbpm-server-distribution/src/main/deployment/kie-server.war.deployed, kie-server-distributions/jbpm-server-distribution/src/main/scripts/jbpm-h2-config.cli, kie-server-distributions/jbpm-server-distribution/src/main/scripts/jbpm-mysql-config.cli, kie-server-distributions/jbpm-server-distribution/src/main/scripts/jbpm-postgres-config.cli, kie-server-distributions/jbpm-server-distribution/src/main/scripts/standalone.conf, kie-server-distributions/jbpm-server-distribution/src/main/server/roles.properties, kie-server-distributions/jbpm-server-distribution/src/main/server/standalone.xml, kie-server-distributions/jbpm-server-distribution/src/main/server/users.properties, kie-server-distributions/pom.xml, pom.xml
@krisv @tsurdilo @mbiarnes actual distribution content
depends on https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/767
=> JBPM-7372 - single zip distribution for jBPM

kie-drools-wb-parent/kie-drools-wb-webapp/src/main/java/org/kie/workbench/drools/client/KieDroolsWorkbenchEntryPoint.java, kie-drools-wb-parent/kie-drools-wb-webapp/src/test/java/org/kie/workbench/drools/client/KieDroolsWorkbenchEntryPointTest.java, kie-wb-parent/kie-wb-monitoring-webapp/src/main/java/org/kie/workbench/client/KieWorkbenchEntryPoint.java, kie-wb-parent/kie-wb-monitoring-webapp/src/test/java/org/kie/workbench/client/KieWorkbenchEntryPointTest.java, kie-wb-parent/kie-wb-webapp/src/main/java/org/kie/workbench/client/KieWorkbenchEntryPoint.java, kie-wb-parent/kie-wb-webapp/src/test/java/org/kie/workbench/client/KieWorkbenchEntryPointTest.java
Related:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/770
https://github.com/errai/errai/pull/350
https://github.com/kiegroup/appformer/pull/404
https://github.com/kiegroup/kie-wb-common/pull/1925
https://github.com/kiegroup/drools-wb/pull/878
https://github.com/kiegroup/jbpm-wb/pull/1162
https://github.com/kiegroup/optaplanner-wb/pull/288
https://github.com/kiegroup/kie-wb-distributions/pull/773
=> AF-1226: Improve error handling displaying additional info to the GenericErrorPopup

kie-wb-tests/kie-wb-tests-rest/src/test/java/org/kie/wb/test/rest/functional/JobIntegrationTest.java, kie-wb-tests/kie-wb-tests-rest/src/test/java/org/kie/wb/test/rest/functional/ProjectIntegrationTest.java, kie-wb-tests/kie-wb-tests-rest/src/test/java/org/kie/wb/test/rest/functional/SpaceIntegrationTest.java, kie-wb-tests/kie-wb-tests-rest/src/test/java/org/kie/wb/test/rest/security/ProjectAccessIntegrationTest.java
See https://issues.jboss.org/browse/DROOLS-2803
=> @Ignore failing tests. See https://issues.jboss.org/browse/DROOLS-2803

kie-server-distributions/jbpm-server-distribution/README.txt, kie-server-distributions/jbpm-server-distribution/src/main/scripts/jbpm-mysql-config.cli, kie-server-distributions/jbpm-server-distribution/src/main/server/roles.properties, kie-server-distributions/jbpm-server-distribution/src/main/server/users.properties
- Use wbadmin user instead of admin to avoid issues with admin group in human task assignments
- Review user roles
- Add MySQL port number parameter to cli script
=> JBPM-7477 - Updates to better align with Docker image

kie-drools-wb-parent/kie-drools-wb-distribution-wars/src/main/productized/resources/security-policy.properties, kie-drools-wb-parent/kie-drools-wb-webapp/pom.xml, kie-drools-wb-parent/kie-drools-wb-webapp/src/main/resources/org/kie/workbench/drools/KIEDroolsWebapp.gwt.xml, kie-drools-wb-parent/kie-drools-wb-webapp/src/main/resources/security-policy.properties, kie-wb-parent/kie-wb-distribution-wars/kie-wb/src/main/productized/resources/security-policy.properties, kie-wb-parent/kie-wb-webapp/pom.xml, kie-wb-parent/kie-wb-webapp/src/main/resources/org/kie/workbench/KIEWebapp.gwt.xml, kie-wb-parent/kie-wb-webapp/src/main/resources/security-policy.properties, kie-wb-parent/pom.xml
See https://issues.jboss.org/browse/DROOLS-2566
This also incorporates https://issues.jboss.org/browse/DROOLS-2748
=> DROOLS-2566: [DMN Editor] Integrate Editor into Workbench

kie-wb-tests/kie-wb-tests-rest/src/main/java/org/kie/wb/test/rest/client/RestWorkbenchClient.java
(cherry picked from commit 0e815bd1519fb665d8e58f3ddcbbb991c44aeae3)
https://issues.jboss.org/browse/AF-1412
@jakubschwan Here you are
=> [7.7.x] AF-1412 : Kie WB REST getJob randomly return 410 Gone after previous REST call

kie-wb-webapp-common/src/main/webapp/WEB-INF/jboss-web.xml
https://issues.jboss.org/browse/DROOLS-2863
@domhanak Hi you were marked as a tester for this.
=> DROOLS-2863 : Unable to start standalone business central without internet access

kie-server-distributions/jbpm-server-distribution/src/main/assembly/assembly-server-dist.xml, kie-server-distributions/jbpm-server-distribution/src/main/scripts/standalone.conf.bat
@cristianonicolai could you please have look?
=> JBPM-7690 - java MAX heap size in jbpm-server-7.10.0.Final-dist.zip

kie-drools-wb-parent/kie-drools-wb-webapp/pom.xml, kie-wb-parent/kie-wb-monitoring-webapp/pom.xml, kie-wb-parent/kie-wb-webapp/pom.xml
This reverts commit 39c5f37d9f6ff24c3c7d6d8af77bd14750337ef3.
=> Revert "Fix for ECJ - GWT conflict (#808)"

kie-drools-wb-parent/kie-drools-wb-webapp/src/main/java/org/kie/workbench/drools/client/perspectives/DroolsAuthoringPerspective.java, kie-wb-parent/kie-wb-webapp/src/main/java/org/kie/workbench/client/perspectives/DroolsAuthoringPerspective.java
https://issues.jboss.org/browse/DROOLS-2535
=> DROOLS-2535 : Standalone Authoring - Project Explorer should not showup with StandaloneAuthoringPerspective

kie-drools-wb-parent/kie-drools-wb-webapp/pom.xml, kie-wb-parent/kie-wb-distribution-wars/kie-wb/pom.xml, kie-wb-parent/kie-wb-monitoring-webapp/pom.xml, kie-wb-parent/kie-wb-webapp/pom.xml
Workbench offline 7.11.x
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/829
https://github.com/kiegroup/kie-soup/pull/57
https://github.com/kiegroup/appformer/pull/459
https://github.com/kiegroup/kie-wb-common/pull/2117
https://github.com/kiegroup/kie-wb-distributions/pull/811
@porcelli @domhanak @jhrcek
=> [AF-1528] 7.11.x Workbench offline 

kie-drools-wb-parent/kie-drools-wb-webapp/pom.xml, kie-wb-parent/kie-wb-distribution-wars/kie-wb/pom.xml, kie-wb-parent/kie-wb-monitoring-webapp/pom.xml, kie-wb-parent/kie-wb-webapp/pom.xml
https://github.com/kiegroup/kie-wb-common/pull/2103 
https://github.com/kiegroup/appformer/pull/450
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/826
https://github.com/kiegroup/kie-soup/pull/55
@porcelli @domhanak @jhrcek
=> [AF-1528 ] Workbench offline

kie-drools-wb-parent/kie-drools-wb-distribution-wars/src/main/productized/resources/security-policy.properties, kie-drools-wb-parent/kie-drools-wb-webapp/pom.xml, kie-drools-wb-parent/kie-drools-wb-webapp/src/main/resources/org/kie/workbench/drools/KIEDroolsWebapp.gwt.xml, kie-drools-wb-parent/kie-drools-wb-webapp/src/main/resources/security-policy.properties, kie-wb-parent/kie-wb-distribution-wars/kie-wb/src/main/productized/resources/security-policy.properties, kie-wb-parent/kie-wb-webapp/pom.xml, kie-wb-parent/kie-wb-webapp/src/main/resources/org/kie/workbench/KIEWebapp.gwt.xml, kie-wb-parent/kie-wb-webapp/src/main/resources/security-policy.properties
https://issues.jboss.org/browse/DROOLS-2689
https://issues.jboss.org/browse/DROOLS-2960
@kkufova Ok so so I bundled the two tickets together so it is easier to test. You can use the war created from here for testing.
=> DROOLS-2960 : User should be able to use Scenario Simulation asset with the distribution war

kie-drools-wb-parent/kie-drools-wb-distribution-wars/src/main/productized/resources/security-policy.properties, kie-drools-wb-parent/kie-drools-wb-webapp/pom.xml, kie-drools-wb-parent/kie-drools-wb-webapp/src/main/resources/org/kie/workbench/drools/KIEDroolsWebapp.gwt.xml, kie-drools-wb-parent/kie-drools-wb-webapp/src/main/resources/security-policy.properties, kie-wb-parent/kie-wb-distribution-wars/kie-wb/src/main/productized/resources/security-policy.properties, kie-wb-parent/kie-wb-webapp/pom.xml, kie-wb-parent/kie-wb-webapp/src/main/resources/org/kie/workbench/KIEWebapp.gwt.xml, kie-wb-parent/kie-wb-webapp/src/main/resources/security-policy.properties
Second attempt of kie-wb-distributions PR for integrating CM into workbench, now with matching kie-wb-common PR that's also been pushed out for review.
=> JBPM-7609: integrate Case Mgmt into Workbench

kie-drools-wb-parent/kie-drools-wb-distribution-wars/src/main/productized/resources/security-module-admin.properties, kie-drools-wb-parent/kie-drools-wb-distribution-wars/src/main/productized/resources/security-policy.properties, kie-drools-wb-parent/kie-drools-wb-webapp/pom.xml, kie-drools-wb-parent/kie-drools-wb-webapp/src/main/resources/org/kie/workbench/drools/KIEDroolsWebapp.gwt.xml, kie-drools-wb-parent/kie-drools-wb-webapp/src/main/resources/security-module-admin.properties, kie-drools-wb-parent/kie-drools-wb-webapp/src/main/resources/security-policy.properties, kie-wb-parent/kie-wb-distribution-wars/kie-wb-monitoring/src/main/productized/resources/security-module-admin.properties, kie-wb-parent/kie-wb-distribution-wars/kie-wb-monitoring/src/main/productized/resources/security-policy.properties, kie-wb-parent/kie-wb-distribution-wars/kie-wb/src/main/productized/resources/security-module-admin.properties, kie-wb-parent/kie-wb-distribution-wars/kie-wb/src/main/productized/resources/security-policy.properties, kie-wb-parent/kie-wb-monitoring-webapp/pom.xml, kie-wb-parent/kie-wb-monitoring-webapp/src/main/resources/org/kie/workbench/KIEWebapp.gwt.xml, kie-wb-parent/kie-wb-monitoring-webapp/src/main/resources/security-module-admin.properties, kie-wb-parent/kie-wb-monitoring-webapp/src/main/resources/security-policy.properties, kie-wb-parent/kie-wb-webapp/pom.xml, kie-wb-parent/kie-wb-webapp/src/main/resources/org/kie/workbench/KIEWebapp.gwt.xml, kie-wb-parent/kie-wb-webapp/src/main/resources/security-module-admin.properties, kie-wb-parent/kie-wb-webapp/src/main/resources/security-policy.properties, kie-wb-parent/pom.xml
AF-1445: Experimental Feature Core API
AF-1538: Experimental Features Editor Screen
AF-1443: Global Experimental Features
@ederign @tomasdavidorg  could you please take a look?
This is a part of an ensemble, please merge with:
https://github.com/kiegroup/appformer/pull/475
https://github.com/kiegroup/kie-wb-common/pull/2138
https://github.com/kiegroup/kie-wb-distributions/pull/819
https://github.com/kiegroup/drools-wb/pull/940
https://github.com/kiegroup/optaplanner-wb/pull/303
https://github.com/kiegroup/kie-docs/pull/1131
=> AF-1251: Support to experimental features

kie-drools-wb-parent/kie-drools-wb-webapp/pom.xml, kie-wb-parent/kie-wb-monitoring-webapp/pom.xml, kie-wb-parent/kie-wb-webapp/pom.xml, kie-wb-webapp-common/src/main/resources/logback.xml
Related PRs:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/798
* https://github.com/kiegroup/appformer/pull/434
* https://github.com/kiegroup/kie-wb-common/pull/2037
* https://github.com/kiegroup/drools-wb/pull/910
* https://github.com/kiegroup/jbpm-wb/pull/1187
* https://github.com/kiegroup/optaplanner-wb/pull/294
* https://github.com/kiegroup/kie-wb-distributions/pull/792
=> [AF-1220]: Added infinispan dependencies

kie-drools-wb-parent/kie-drools-wb-distribution-wars/src/main/productized/resources/security-policy.properties, kie-drools-wb-parent/kie-drools-wb-webapp/pom.xml, kie-drools-wb-parent/kie-drools-wb-webapp/src/main/resources/org/kie/workbench/drools/KIEDroolsWebapp.gwt.xml, kie-drools-wb-parent/kie-drools-wb-webapp/src/main/resources/security-policy.properties, kie-wb-parent/kie-wb-distribution-wars/kie-wb-monitoring/src/main/productized/resources/security-policy.properties, kie-wb-parent/kie-wb-distribution-wars/kie-wb/src/main/productized/resources/security-policy.properties, kie-wb-parent/kie-wb-monitoring-webapp/pom.xml, kie-wb-parent/kie-wb-monitoring-webapp/src/main/resources/org/kie/workbench/KIEWebapp.gwt.xml, kie-wb-parent/kie-wb-monitoring-webapp/src/main/resources/security-policy.properties, kie-wb-parent/kie-wb-webapp/pom.xml, kie-wb-parent/kie-wb-webapp/src/main/resources/org/kie/workbench/KIEWebapp.gwt.xml, kie-wb-parent/kie-wb-webapp/src/main/resources/security-policy.properties, kie-wb-parent/pom.xml
AF-1275: SSH Keystore backend
AF-1274: SSH Keystore UI
AF-1277: Integrate SSH Keystore with VFS SSH
@ederign @domhanak could you please take a look?
https://github.com/kiegroup/appformer/pull/492
https://github.com/kiegroup/kie-wb-common/pull/2177
https://github.com/kiegroup/kie-wb-distributions/pull/829
https://github.com/kiegroup/drools-wb/pull/959
https://github.com/kiegroup/jbpm-wb/pull/1215
https://github.com/kiegroup/optaplanner-wb/pull/308
https://github.com/kiegroup/kie-docs/pull/1156
=> AF-1424: Support SSH keystore with workbench

kie-server-distributions/jbpm-server-distribution/src/main/server/standalone.xml
@cristianonicolai could you please have a look?
=> Make the file based H2 database to be used by default

kie-wb-tests/README.md, kie-wb-tests/kie-wb-tests-gui/README.md, kie-wb-tests/kie-wb-tests-gui/pom.xml, kie-wb-tests/kie-wb-tests-rest/pom.xml, kie-wb-tests/pom.xml
Should be merged with:
https://github.com/kiegroup/kie-jenkins-scripts/pull/365
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/875
https://github.com/kiegroup/jbpm/pull/1366
https://github.com/kiegroup/droolsjbpm-integration/pull/1627
https://github.com/kiegroup/kie-wb-distributions/pull/841
=> Update profile names wildfly14 upgrade

kie-wb-tests/pom.xml
also reuse `version.org.wildfly` coming from kie-parent
=> Don't use wildfly version in property names

business-central-parent/business-central-webapp/src/main/java/org/kie/bc/client/KieWorkbenchEntryPoint.java, business-central-parent/business-central-webapp/src/test/java/org/kie/bc/client/KieWorkbenchEntryPointTest.java
Depends on https://github.com/kiegroup/appformer/pull/551
=> AF-1725: Firing WorkbenchProfileCssClass event when menu changes

business-central-parent/business-central-webapp/pom.xml, business-central-parent/business-monitoring-webapp/pom.xml
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/892
https://github.com/kiegroup/kie-wb-common/pull/2304
https://github.com/kiegroup/kie-wb-distributions/pull/849
=> AF-1709: Adding Profile Backend dependency

business-central-parent/business-central-webapp/pom.xml
Adding the new chart implementation based on C3 as a dependency.
=> AF-1655: Adding C3 dependency

business-central-parent/business-central-webapp/.gitignore, business-central-parent/business-central-webapp/pom.xml
Complete set of PRs 
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/907
https://github.com/kiegroup/appformer/pull/591
https://github.com/kiegroup/kie-wb-common/pull/2374
https://github.com/kiegroup/jbpm-work-items/pull/88
https://github.com/kiegroup/jbpm-wb/pull/1268
https://github.com/kiegroup/kie-wb-distributions/pull/860
=> JBPM-8000 - Work item repository administration in business central

business-central-parent/business-central-distribution-wars/pom.xml, business-central-parent/business-central-webapp/pom.xml, business-central-parent/business-monitoring-webapp/pom.xml
PR set:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/900 (Please comment on this PR if you have any questions)
* https://github.com/kiegroup/droolsjbpm-knowledge/pull/352
* https://github.com/kiegroup/drools/pull/2191
* https://github.com/kiegroup/jbpm/pull/1394
* https://github.com/kiegroup/optaplanner/pull/469
* https://github.com/kiegroup/droolsjbpm-integration/pull/1667
* https://github.com/kiegroup/appformer/pull/574
* https://github.com/kiegroup/optaplanner-wb/pull/319
* https://github.com/kiegroup/jbpm-wb/pull/1257
* https://github.com/kiegroup/kie-wb-distributions/pull/858
* https://github.com/kiegroup/optaweb-employee-rostering/pull/215
=> Align JAXB and JAXWS APIs with Wildfly

business-central-parent/business-central-home-page-product/src/main/java/org/kie/bc/client/navbar/MegaMenuConfig.java, business-central-parent/business-central-home-page-product/src/main/java/org/kie/bc/client/resources/i18n/Constants.java, business-central-parent/business-central-home-page-product/src/main/resources/org/kie/bc/client/resources/i18n/Constants.properties
AF-1724: Fixing Brand Image alt text
=> AF-1724: Fixing Brand Image alt text

business-central-parent/business-central-webapp/src/main/resources/security-policy.properties
Assembly:
https://github.com/kiegroup/kie-wb-common/pull/2432
https://github.com/kiegroup/kie-wb-distributions/pull/870
=> JBPM-8164: expose the editor as tech preview on the workbench

business-central-parent/jbpm-server-distribution/pom.xml, business-central-parent/jbpm-server-distribution/src/main/assembly/assembly-server-dist.xml
depends on 
https://github.com/kiegroup/droolsjbpm-integration/pull/1705 
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/917
upgraded to ee8 and removed the standalone work item repo since we have now one embedded in Business Central
=> JBPM-8088 - Create separate Kie Server war files for ee7 and ee8

business-central-parent/business-central-distribution-wars/business-central/pom.xml, business-central-parent/business-central-distribution-wars/src/main/assembly/component-kie-wb-swarm-zip.xml, business-central-parent/business-central-distribution-wars/src/main/productized/assembly-kie-wb-swarm-zip-redhat.xml, business-central-parent/business-central-distribution-wars/src/main/shared/swarm/README.txt, business-central-parent/business-central-distribution-wars/src/main/shared/swarm/application-roles.properties, business-central-parent/business-central-distribution-wars/src/main/shared/swarm/application-users.properties, business-central-parent/business-central-distribution-wars/src/main/shared/swarm/sample-swarm-config.yml
https://issues.jboss.org/browse/AF-1798
=> AF-1798 : Standalone Decision Central package should provide better default configuration

business-central-parent/business-central-distribution-wars/src/main/productized/webapp/login.jsp, business-central-parent/business-central-distribution-wars/src/main/productized/webapp/logout.jsp, business-central-parent/business-central-distribution-wars/src/main/productized/webapp/not_authorized.jsp
See Also: https://github.com/kiegroup/appformer/pull/657
=> RHPAM-1948: IE does not support unset

business-central-parent/business-central-distribution-wars/business-central/pom.xml, business-central-parent/business-central-distribution-wars/src/main/assembly/component-kie-wb-swarm-common-RHDM.xml, business-central-parent/business-central-distribution-wars/src/main/productized/assembly-kie-wb-swarm-redhat-RHDM.xml, business-central-parent/business-central-distribution-wars/src/main/productized/swarm/project-defaults.yml
(cherry picked from commit f32ab185256709eee29b050189d212db1aeb4a80)
https://issues.jboss.org/browse/AF-1876
@tomasdavidorg @mareknovotny if you two could please take a look.
=> [7.18.x] AF-1876 : Full profile is the default profile in Swarm RHDM distribution

business-central-parent/business-central-distribution-wars/business-central/pom.xml, business-central-parent/business-central-distribution-wars/src/main/assembly/component-kie-wb-swarm-common-RHDM.xml, business-central-parent/business-central-distribution-wars/src/main/productized/assembly-kie-wb-swarm-redhat-RHDM.xml, business-central-parent/business-central-distribution-wars/src/main/productized/swarm/project-defaults.yml
https://issues.jboss.org/browse/AF-1876
@tomasdavidorg @mareknovotny if you two could please take a look.
=> AF-1876 : Full profile is the default profile in Swarm RHDM distribution

business-central-parent/business-central-distribution-wars/pom.xml, business-central-parent/business-central-webapp/pom.xml, business-central-parent/business-monitoring-webapp/pom.xml
upgraded to jboss-jaxrs-api_2.1_spec
added exclusion of duplicated class brought in by resteasy
=> BAPL-1148: updated to org.dom4j

business-central-parent/business-central-distribution-wars/src/main/productized/swarm/project-defaults.yml
https://issues.jboss.org/browse/RHDM-538
=> [7.18.x] RHDM-538: adding ruleflow perspective by default for RHDM standalone

business-central-parent/business-central-distribution-wars/src/main/productized/swarm/project-defaults.yml
version for master like at https://github.com/kiegroup/kie-wb-distributions/pull/904
=> RHDM-538: adding ruleflow perspective by default for RHDM standalone

business-central-parent/business-central-distribution-wars/src/main/productized/swarm/project-defaults.yml
https://issues.jboss.org/browse/AF-1876
@mareknovotny @tomasdavidorg Could you two review please.
=> [7.18.x]AF-1876 : Full profile is the default profile in Swarm RHDM distribution

business-central-parent/jbpm-server-distribution/src/main/server/standalone.xml
@krisv @mbiarnes this needs to be included in the next community release
=> adjusted keystore path so it works on unix and windows

business-central-parent/business-central-webapp/pom.xml
@manstis @gitgabrio @danielezonca guys, I had that dependency because I couldn't compile business-central-webapp without it.
Would you mind to review it?
=> [DROOLS-3389]: Added missing dependency

business-central-parent/business-central-webapp/pom.xml, business-central-parent/business-central-webapp/src/main/resources/org/kie/bc/KIEWebapp.gwt.xml, business-central-parent/business-monitoring-webapp/pom.xml, business-central-parent/business-monitoring-webapp/src/main/resources/org/kie/bc/KIEWebapp.gwt.xml
Related PRs:
kiegroup/drools-wb#1101
kiegroup/optaplanner-wb#332
kiegroup/jbpm-wb#1325
https://github.com/kiegroup/kie-wb-common/pull/2549
kiegroup/appformer#670
=> AF-1774: Removing GChartsRenderer (Google Charts)

business-central-parent/business-central-webapp/pom.xml, business-central-parent/business-central-webapp/src/main/webapp/WEB-INF/web.xml, business-central-parent/business-monitoring-webapp/pom.xml
related PRs:
https://github.com/kiegroup/appformer/pull/669
https://github.com/kiegroup/kie-wb-distributions/pull/902
https://github.com/kiegroup/kie-wb-common/pull/2551
https://github.com/kiegroup/kie-docs/pull/1487
=> AF-1908: add security filter to git access over http

business-central-parent/business-central-webapp/pom.xml
Assembly:
https://github.com/kiegroup/appformer/pull/709
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/958
https://github.com/kiegroup/kie-wb-common/pull/2650
https://github.com/kiegroup/kie-wb-distributions/pull/927
=> JBPM-8168: switch between case and process

business-central-parent/business-central-webapp/pom.xml, business-central-parent/business-central-webapp/src/main/resources/org/kie/bc/KIEWebapp.gwt.xml
@gitgabrio @danielezonca @kkufova
Required for PRs:
- kiegroup/drools-wb#1167
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/972
=> Drools 4141 - Split scesim client module in core and business central modules 

business-central-tests/business-central-tests-gui/pom.xml
See https://issues.jboss.org/browse/BAQE-982 for more details.
=> BAQE-982: Increase homepage loading timeout

business-central-parent/business-central-distribution-wars/business-central/src/main/productized/resources/security-module-admin.properties, business-central-parent/business-central-distribution-wars/business-central/src/main/productized/resources/security-policy.properties, business-central-parent/business-central-webapp/src/main/java/org/kie/bc/client/KieWorkbenchEntryPoint.java, business-central-parent/business-central-webapp/src/main/resources/security-module-admin.properties, business-central-parent/business-central-webapp/src/main/resources/security-policy.properties, business-central-parent/business-monitoring-webapp/src/main/java/org/kie/bc/client/KieWorkbenchEntryPoint.java
Pull Request for [AF-2036](https://issues.jboss.org/browse/AF-2036)
This is part of [PR 750 for Appformer](https://github.com/kiegroup/appformer/pull/750)
=> AF-2036 - Import/Export Dashbuilder Data via UI

business-central-tests/business-central-tests-gui/src/main/java/org/kie/wb/selenium/model/persps/ProjectLibraryPerspective.java, business-central-tests/business-central-tests-gui/src/test/java/org/kie/wb/selenium/ui/ProjectLibraryIntegrationTest.java, business-central-tests/business-central-tests-rest/src/test/java/org/kie/wb/test/rest/functional/SpacesScreenServiceIntegrationTest.java
* https://github.com/kiegroup/kie-wb-common/pull/2808
* https://github.com/kiegroup/kie-wb-distributions/pull/954
Removed Library preferences that saved the last opened space, last opened branches and last project explorer dock state to improve performance.
=> AF-2127: Stateless Library

business-central-parent/business-central-webapp/pom.xml
Keycloak deps brought resteasy and then broke all REST services. This PR excludes the unwanted deps.
=> JBPM-8750: Excluding unwanted dependencies

business-central-tests/business-central-tests-gui/src/main/java/org/kie/wb/selenium/model/persps/ProjectLibraryPerspective.java
- updated selenium test cases to accomodate the changes done as part of the PR https://github.com/kiegroup/kie-wb-common/pull/2900
- Replaced  kebab menu with Add project combo button.
=> AF-2177 :Add Project button should also allow importing

business-central-parent/business-central-webapp/pom.xml
=> RHPAM-2443 io.netty:netty-handler and io.netty:netty-codec-http excluded from org.jboss.errai:errai-bus

business-central-parent/business-central-webapp/pom.xml, business-central-parent/business-central-webapp/src/main/resources/org/kie/bc/KIEWebapp.gwt.xml
@manstis now opening the PR from the kiegroup repository.
Allow initial kogito branch on kie-wb-common to be merged on master, adding some needed dependencies.
Related PR's
kiegroup/kie-wb-common#2923
kiegroup/droolsjbpm-build-bootstrap#1071
=> DROOLS-3727 [upstream]  - Adding kogito compileSourcesArtifact to business-central pom.xml 

business-central-tests/business-central-tests-gui/src/main/java/org/kie/wb/selenium/model/persps/ProjectLibraryPerspective.java
- updated selenium test cases to accomodate the add project button
Backport of AF-2177 ,[#966 ]
=> Backport of AF-2177 :Add Project button should also allow importing

business-central-parent/business-central-webapp/pom.xml, business-central-parent/business-central-webapp/src/main/resources/org/kie/bc/KIEWebapp.gwt.xml
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1066
kiegroup/appformer#807
kiegroup/kie-wb-common#2917
kiegroup/drools-wb#1235
kiegroup/jbpm-wb#1393
https://github.com/kiegroup/optaplanner-wb/pull/347
=> AF-2125: Adding  dependencies removed from widgets core

pom.xml
https://issues.jboss.org/browse/DROOLS-4563
Parent PR:
-  kiegroup/droolsjbpm-build-bootstrap#1075
=> DROOLS-4563: managing validation-api due GWT components

business-central-tests/business-central-tests-gui/src/main/java/org/kie/wb/selenium/model/persps/ProjectLibraryPerspective.java, business-central-tests/business-central-tests-gui/src/main/java/org/kie/wb/selenium/util/Waits.java
Cherry-pick of https://github.com/kiegroup/kie-wb-distributions/pull/982
=> [7.26.x] Stabilize ProjectLibraryPerspective test

business-central-tests/business-central-tests-gui/src/test/filtered-resources/arquillian.xml
=> [7.26.x] Update Gecko driver version to 0.26.0 (#972)

business-central-tests/business-central-tests-gui/src/main/java/org/kie/wb/selenium/model/persps/ProjectLibraryPerspective.java, business-central-tests/business-central-tests-gui/src/main/java/org/kie/wb/selenium/util/Waits.java
Cherry-pick of #985 
@mareknovotny this is my another attempt to fix the failing `LoadAllPerspectivesIntegrationTest` test.
=> [7.26.x] Handle properly projects loading popup

business-central-parent/business-central-webapp/pom.xml, business-central-parent/business-central-webapp/src/main/resources/org/kie/bc/KIEWebapp.gwt.xml
Main PR: https://github.com/kiegroup/kie-wb-common/pull/2991
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1092
* https://github.com/kiegroup/kie-wb-common/pull/2991
* https://github.com/kiegroup/jbpm-wb/pull/1401
* https://github.com/kiegroup/drools-wb/pull/1256
* https://github.com/kiegroup/kie-wb-distributions/pull/986
* https://github.com/kiegroup/optaplanner-wb/pull/349
=> Removed deprecated samples project

business-central-parent/business-central-webapp/pom.xml
=> [7.30.x] RHPAM-2529: scope provided added to org.jboss.errai:errai-bus dependency from business-central-webapp project

business-central-tests/business-central-tests-rest/src/main/java/org/kie/wb/test/rest/client/RestWorkbenchClient.java, business-central-tests/business-central-tests-rest/src/main/java/org/kie/wb/test/rest/client/WorkbenchClient.java, business-central-tests/business-central-tests-rest/src/test/java/org/kie/wb/test/rest/functional/ProjectIntegrationTest.java
[AF-2339 Add support for branch management in the rest API](https://issues.jboss.org/browse/AF-2339)
Depends on:
* https://github.com/kiegroup/appformer/pull/861
* https://github.com/kiegroup/kie-wb-common/pull/3049
=> [AF-2339] Add support for branch management in the rest API

business-central-tests/business-central-tests-gui/src/test/java/org/kie/wb/selenium/ui/StandalonePerspectivesIntegrationTest.java
There is a mechanism which reruns Selenium tests when some failure
occurs. Sometimes it happens that the first run of first test fails
because of the loading pop-up dialog is still on the screen after login.
Then the second run of the the whole test class fails because of the
space is already created.
This fix creates unique space name for every test run. It could be
possible to just remove the space after the test class but then there
have to be a minute pause before the space is physically deleted.
=> Make StandalonePerspectivesIntegrationTest independent of other runs

business-central-parent/business-monitoring-webapp/pom.xml, business-central-parent/business-monitoring-webapp/src/main/resources/META-INF/services/org.uberfire.java.nio.file.spi.FileSystemProvider
For Business Central Monitoring cloud image distribution
Signed-off-by: Evan Zhang <evan.zhang@redhat.com>
Prerequisite PRs:
https://github.com/kiegroup/appformer/pull/799
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1152
=> KIECLOUD-256: Default to ocp/k8s backed uberfire java nio2 file system implementation 

business-central-parent/add-ons-distribution/pom.xml, business-central-parent/add-ons-distribution/src/main/assembly/add-ons.zip.xml, business-central-parent/business-central-distribution-wars/src/main/assembly/component-kie-wb-standalone-zip.xml, business-central-parent/pom.xml
https://issues.redhat.com/browse/RHDM-405
We need to follow up with RHBA PR to get this zip into addons assembly.
=> RHDM-405: creating standalone zip with easy startup configurations

business-central-parent/business-central-distribution-wars/business-central/src/main/productized/resources/security-module-developer.properties, business-central-parent/business-central-distribution-wars/business-monitoring/src/main/productized/resources/security-module-developer.properties, business-central-parent/business-central-webapp/pom.xml, business-central-parent/business-central-webapp/src/main/resources/org/kie/bc/KIEWebapp.gwt.xml, business-central-parent/business-central-webapp/src/main/resources/security-module-analyst.properties, business-central-parent/business-central-webapp/src/main/resources/security-module-developer.properties, business-central-parent/business-monitoring-webapp/pom.xml, business-central-parent/business-monitoring-webapp/src/main/resources/org/kie/bc/KIEWebapp.gwt.xml, business-central-parent/business-monitoring-webapp/src/main/resources/security-module-analyst.properties, business-central-parent/business-monitoring-webapp/src/main/resources/security-module-developer.properties
**Task**: [AF-2366](https://issues.redhat.com/browse/AF-2366)
**Related PRs**:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1151
- https://github.com/kiegroup/kie-soup/pull/124
- https://github.com/kiegroup/appformer/pull/872
- https://github.com/kiegroup/kie-wb-common/pull/3098
- https://github.com/kiegroup/jbpm-wb/pull/1406
- https://github.com/kiegroup/drools-wb/pull/1278
- https://github.com/kiegroup/optaplanner-wb/pull/352
- https://github.com/kiegroup/kie-wb-distributions/pull/1005
=> [AF-2366] BC Maven Archetype Support

business-central-parent/business-central-webapp/pom.xml, business-central-parent/business-monitoring-webapp/pom.xml
**Task**: [AF-2363](https://issues.redhat.com/browse/AF-2363)
**Related PRs**:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1171
- https://github.com/kiegroup/appformer/pull/881
- https://github.com/kiegroup/kie-wb-common/pull/3126
- https://github.com/kiegroup/drools-wb/pull/1293
- https://github.com/kiegroup/optaplanner-wb/pull/353
- https://github.com/kiegroup/jbpm-wb/pull/1410
- https://github.com/kiegroup/kie-wb-distributions/pull/1009
=> [AF-2363] Be able to create projects from empty repositories

business-central-parent/business-central-webapp/pom.xml
Adding missing deps to webapp
@tiagobento would you mind take a look?
https://github.com/kiegroup/kogito-tooling/pull/66
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1195
https://github.com/kiegroup/appformer/pull/894
https://github.com/kiegroup/kie-wb-common/pull/3156
https://github.com/kiegroup/jbpm-wb/pull/1414
https://github.com/kiegroup/drools-wb/pull/1310
https://github.com/kiegroup/kie-wb-distributions/pull/1013
=> KOGITO-879 KOGITO-880 KOGITO-881: State Control API (undo/redo)

business-central-parent/business-central-webapp/src/main/resources/org/kie/bc/KIEWebapp.gwt.xml, business-central-parent/business-monitoring-webapp/src/main/resources/org/kie/bc/KIEWebapp.gwt.xml
- Commented the code that includes non-translated locales
- language dropdown to show only supported locales (English, Japanese,Spanish, French )
- https://github.com/kiegroup/kie-wb-common/pull/3191
- https://github.com/kiegroup/kie-wb-distributions/pull/1018
=> RHPAM-2748 :Update locale selection drop down to include only the supported languages for RHDM and RHPAM

business-central-parent/business-central-webapp/src/main/resources/org/kie/bc/KIEWebapp.gwt.xml, business-central-parent/business-monitoring-webapp/src/main/resources/org/kie/bc/KIEWebapp.gwt.xml
- Commented the code that includes non-translated locales
- language dropdown to show only supported locales
Merge with : https://github.com/kiegroup/kie-wb-common/pull/3197
(cherry picked from commit 094b5adcc1e6a99a5d726f55065f1dd9c00fd182)
=> [7.33.x] RHPAM-2748 :Update locale selection drop down to include only the supported languages for RHDM and RHPAM

business-central-parent/business-central-webapp/src/main/webapp/WEB-INF/web.xml, business-central-parent/business-monitoring-webapp/src/main/webapp/WEB-INF/web.xml
Signed-off-by: Karel Suta <ksuta@redhat.com>
Follows up https://github.com/kiegroup/kie-wb-distributions/pull/1020.
Intention is to have public accessible Swagger page for embedded controller operations.
@gmunozfe Can you please review?
=> Exclude swagger.json from basic authorization

business-central-parent/business-central-distribution-wars/src/main/productized/assembly-kie-wb-eap-7-redhat.xml
https://issues.redhat.com/browse/BXMSPROD-784
fixes https://github.com/kiegroup/kie-wb-distributions/pull/1022
=> BXMSPROD-784 assembly-kie-wb-eap-7-redhat.xml wildfly-14 error fixed

business-central-parent/business-central-home-page-community/src/main/java/org/kie/bc/client/home/AbstractHomeProducer.java, business-central-parent/business-central-home-page-community/src/main/java/org/kie/bc/client/home/FileSystemConfiguration.java, business-central-parent/business-central-home-page-community/src/main/java/org/kie/bc/client/home/HomeProducer.java, business-central-parent/business-central-home-page-community/src/main/java/org/kie/bc/client/home/HomeRuntimeProducer.java, business-central-parent/business-central-home-page-community/src/test/java/org/kie/bc/client/home/HomeProducerDroolsPlannerProfileTest.java, business-central-parent/business-central-home-page-community/src/test/java/org/kie/bc/client/home/HomeProducerFullProfileTest.java, business-central-parent/business-central-home-page-product/src/main/java/org/kie/bc/client/home/AbstractHomeProducer.java, business-central-parent/business-central-home-page-product/src/main/java/org/kie/bc/client/home/FileSystemConfiguration.java, business-central-parent/business-central-home-page-product/src/main/java/org/kie/bc/client/home/HomeProducer.java, business-central-parent/business-central-home-page-product/src/main/java/org/kie/bc/client/home/HomeRuntimeProducer.java, business-central-parent/business-monitoring-webapp/src/main/java/org/kie/bc/client/KieWorkbenchEntryPoint.java, business-central-parent/business-monitoring-webapp/src/main/java/org/kie/bc/client/navigation/NavTreeDefinitions.java, business-central-parent/business-monitoring-webapp/src/main/resources/META-INF/services/org.uberfire.java.nio.file.spi.FileSystemProvider, business-central-parent/business-monitoring-webapp/src/test/java/org/kie/bc/client/KieWorkbenchEntryPointTest.java
Related to:
* https://github.com/kiegroup/appformer/pull/895
* https://github.com/kiegroup/kie-wb-common/pull/3314
* https://github.com/kiegroup/drools-wb/pull/1379
* https://github.com/kiegroup/jbpm-wb/pull/1436
* https://github.com/kiegroup/optaplanner-wb/pull/371
* https://github.com/kiegroup/kie-wb-distributions/pull/1010
=> AF-2411: Removing pages from Monitoring app

business-central-parent/business-central-home-page-community/src/main/java/org/kie/bc/client/home/AbstractHomeProducer.java, business-central-parent/business-central-home-page-community/src/main/java/org/kie/bc/client/home/HomeProducer.java, business-central-parent/business-central-home-page-community/src/main/java/org/kie/bc/client/home/HomeRuntimeProducer.java, business-central-parent/business-central-home-page-community/src/test/java/org/kie/bc/client/home/HomeProducerDroolsPlannerProfileTest.java, business-central-parent/business-central-home-page-community/src/test/java/org/kie/bc/client/home/HomeProducerFullProfileTest.java, business-central-parent/business-central-home-page-product/src/main/java/org/kie/bc/client/home/AbstractHomeProducer.java, business-central-parent/business-central-home-page-product/src/main/java/org/kie/bc/client/home/HomeProducer.java, business-central-parent/business-central-home-page-product/src/main/java/org/kie/bc/client/home/HomeRuntimeProducer.java, business-central-parent/business-central-home-page-product/src/test/java/org/kie/bc/client/home/HomeProducerDroolsPlannerProfileTest.java, business-central-parent/business-central-home-page-product/src/test/java/org/kie/bc/client/home/HomeProducerFullProfileTest.java, business-central-parent/business-central-webapp/src/main/java/org/kie/bc/client/navigation/NavTreeDefinitions.java, business-central-parent/business-central-webapp/src/main/java/org/kie/bc/client/perspectives/M2RepoPerspective.java, business-central-parent/business-monitoring-webapp/src/main/java/org/kie/bc/client/navigation/NavTreeDefinitions.java, business-central-parent/business-monitoring-webapp/src/main/java/org/kie/bc/client/perspectives/M2RepoPerspective.java
Refactoring imports based on PR https://github.com/kiegroup/kie-wb-common/pull/3315
Related PR's : 
https://github.com/kiegroup/appformer/pull/976
https://github.com/kiegroup/kie-wb-common/pull/3315 
https://github.com/kiegroup/kie-wb-distributions/pull/1033
https://github.com/kiegroup/drools-wb/pull/1378
https://github.com/kiegroup/jbpm-wb/pull/1435
https://github.com/kiegroup/optaplanner-wb/pull/370
=> BAPL-1547 :Improvement the REST API in Business-Central adding the groups/roles operations available in the UI

business-central-parent/jbpm-server-distribution/pom.xml
Merge with: https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1350
=> Manage postgresql version with kie-parent

business-central-parent/business-monitoring-webapp/pom.xml
https://issues.redhat.com/browse/JBPM-9189
parent PR kiegroup/droolsjbpm-build-bootstrap#1364
=> JBPM-9189: changed Errai wildfly distro version

business-central-parent/business-central-webapp/pom.xml
https://issues.redhat.com/browse/BXMSPROD-830
You can see the result here https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/PROD/job/nightly/view/change-requests/job/PR-1367/20/console
=> BXMSPROD-830 add scopes to missing backend dependencies

business-central-parent/business-central-distribution-wars/src/main/community/assembly-kie-wb-wildfly.xml, business-central-parent/business-central-distribution-wars/src/main/community/assembly-kie-wb-wildfly.zip.xml, pom.xml
https://issues.redhat.com/browse/JBPM-9201
Parent PR: https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1371
=> JBPM-9201: fixed deployable classifier to wildfly19

business-central-tests/pom.xml
https://issues.redhat.com/browse/JBPM-9227
Parent PR kiegroup/droolsjbpm-build-bootstrap#1390
=> JBPM-9227: updated wildfly 19x cargo container

business-central-parent/business-central-distribution-wars/src/main/community/assembly-kie-wb-wildfly.xml, business-central-parent/business-central-distribution-wars/src/main/community/assembly-kie-wb-wildfly.zip.xml, business-central-tests/pom.xml, pom.xml
[link](https://www.example.com)
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1437
* https://github.com/kiegroup/jbpm/pull/1728
* https://github.com/kiegroup/droolsjbpm-integration/pull/2195
* https://github.com/kiegroup/jbpm-wb/pull/1453
* https://github.com/kiegroup/kie-wb-distributions/pull/1051
**How to retest or run**:
* a pull request please add comment: regex **[.\*[j|J]enkins,?.\*(retest|test) this.\*]**
* a full downstream build please add comment: regex **[.*\[j|J]enkins,?.\*(execute|run|trigger|start|do) fdb.\*]**
* a compile downstream build please  add comment: regex …
=> Wildfly19 7.39.x

business-central-parent/business-central-webapp/pom.xml, business-central-parent/business-central-webapp/src/main/webapp/WEB-INF/web.xml, business-central-parent/business-monitoring-webapp/pom.xml
Add components servlet and dependency to Business Central
Part of an ensemble, merge with:
kiegroup/droolsjbpm-build-bootstrap#1419
https://github.com/kiegroup/appformer/pull/1016
=> AF-2577: Adding External Component Servlet

business-central-parent/business-central-distribution-wars/src/main/productized/webapp/kie-wb.jsp
**JIRA**: [RHDM-1451](https://issues.redhat.com/browse/RHDM-1451): DMN models opened as invalid in productized builds of BC
**Artifacts**
- **Business Central (without this PR)**: [WAR file](https://www.dropbox.com/s/byiijz8jcejizya/before.war?dl=0)
- **Business Central (with this PR)**: [WAR file](https://www.dropbox.com/s/lf5xpgebox3lxth/after.war?dl=0)
---
<pre>
To retest a PR or trigger a specific build please add a comment:
* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</pre>
=> RHDM-1451: DMN models opened as invalid in productized builds of BC

.github/workflows/pull_request.yml
**JIRA**: https://issues.redhat.com/browse/BXMSPROD-1006
<details>
<summary>
</summary>
* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>
=> BXMSPROD-1006 GA runner hard disk clean

business-central-parent/business-central-home-page-community/src/main/java/org/kie/bc/client/home/HomeConfiguration.java, business-central-parent/business-central-home-page-community/src/main/java/org/kie/bc/client/home/HomeRuntimeProducer.java, business-central-parent/business-central-home-page-product/src/main/java/org/kie/bc/client/home/HomeConfiguration.java, business-central-parent/business-central-home-page-product/src/main/java/org/kie/bc/client/home/HomeRuntimeProducer.java, business-central-parent/business-monitoring-webapp/pom.xml, business-central-parent/business-monitoring-webapp/src/main/java/org/kie/bc/client/KieWorkbenchEntryPoint.java, business-central-parent/business-monitoring-webapp/src/main/java/org/kie/bc/client/navigation/NavTreeDefinitions.java, business-central-parent/business-monitoring-webapp/src/test/java/org/kie/bc/client/KieWorkbenchEntryPointTest.java
Error when creating page in Monitoring console
[RHPAM-3066](https://issues.redhat.com/browse/RHPAM-3066)
=> RHPAM-3066: Error when creating page in Monitoring console

.gitignore, business-central-parent/business-central-distribution-wars/pom.xml
https://issues.redhat.com/browse/BXMSPROD-685
parent PR kiegroup/droolsjbpm-build-bootstrap#1320
=> BXMSPROD-685: added exclusions due Weld upgrade

business-central-parent/business-central-webapp/pom.xml, business-central-parent/business-central-webapp/src/main/resources/org/kie/bc/KIEWebapp.gwt.xml
Hey @LuboTerifaj 
Please see https://issues.redhat.com/browse/BAPL-1742
Assembly with:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1541
- https://github.com/kiegroup/kie-wb-common/pull/3504
- https://github.com/kiegroup/kie-wb-distributions/pull/1072
Thanks!
=> BAPL-1742: Drop Case Management (Tech Preview) editor

business-central-tests/business-central-tests-rest/src/test/java/org/kie/wb/test/rest/functional/ProjectIntegrationTest.java, business-central-tests/business-central-tests-rest/src/test/java/org/kie/wb/test/rest/functional/RepositoryIntegrationTest.java, business-central-tests/business-central-tests-rest/src/test/java/org/kie/wb/test/rest/functional/SpaceIntegrationTest.java
[JBPM-9542](https://issues.redhat.com/browse/JBPM-9542)
<details>
<summary>
</summary>
* <b>an upstream build</b> please add comment: <b>Jenkins run upstream</b>
</details>
=> [7.44.x]JBPM-9542  Ignore 4 unit tests of business-central-tests that related to Jira

business-central-parent/business-monitoring-webapp/pom.xml
**Upgrade JDK 11 + GWT 2.9**
Feel free to comment and/or raise any concerns.
This PR continues the work done in 
- https://github.com/kiegroup/appformer/pull/1030
- https://github.com/kiegroup/appformer/pull/1039
Thanks guys for that!
**JIRA**:
[AF-1799](https://issues.redhat.com/browse/AF-1799)
**Parent Pull Request**:
- https://github.com/kiegroup/lienzo-core/pull/134
<details>
<summary>
</summary>
* <b>an upstream …
=> AF-1799: Upgrade JDK 11 + GWT 2.9

.github/workflows/pull_request.yml
https://issues.redhat.com/browse/BXMSPROD-1202
- https://github.com/kiegroup/optaweb-employee-rostering/pull/560
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/421
- https://github.com/kiegroup/kie-wb-distributions/pull/1083
- https://github.com/kiegroup/droolsjbpm-integration/pull/2392
- https://github.com/kiegroup/optaweb-employee-rostering/pull/561
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/422
<details>
<summary>
</summary>
* <b>a full production downstream build</b> please add …
=> BXMSPROD-1202 ubuntu-latest to ubuntu-18.04

business-central-parent/business-central-webapp-common/src/main/webapp/META-INF/kie.conf, business-central-parent/business-central-webapp/pom.xml
@danielezonca @mariofusco @jiripetrlik
see https://issues.redhat.com/browse/DROOLS-5860
This PR 
1) add org.kie:kie-pmml-dependencies (trusty-pmml) to business-central
2) remove old (unused) legacy-pmml kie.conf
=> [DROOLS-5860] Updating pom

business-central-parent/business-central-webapp-common/src/main/webapp/META-INF/jboss-deployment-structure.xml
https://issues.redhat.com/browse/AF-2767
Adds a dependency to JMX subsystem to make possible for Kafka dataset invokes MBeans on Kafka
https://github.com/kiegroup/kie-soup/pull/177
kiegroup/droolsjbpm-build-bootstrap#1592
kiegroup/appformer#1104
=> AF-2767: Kafka dataset provider

business-central-parent/business-central-webapp/pom.xml
**JIRA**: [KOGITO-4233](https://issues.redhat.com/browse/KOGITO-4233): [DMN Designer] IntelliSense service
**Part of an ensemble**:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1611
- https://github.com/kiegroup/drools/pull/3435
- https://github.com/kiegroup/appformer/pull/1115
- https://github.com/kiegroup/kie-wb-common/pull/3590
- https://github.com/kiegroup/drools-wb/pull/1471
- https://github.com/kiegroup/kie-wb-distributions/pull/1091
**Artifacts**:
- **Business Central**: [WAR file](https://www.dropbox.com/s/fu3ra76qhptzprr/KOGITO-4233-bc.war?dl=0)
- **VS Code**: [plugin](https://www.dropbox.com/s/jaxmlnilmexk1zw/KOGITO-4233-plugin.vsix?dl=0)
<details>
<summary>
</summary>
* <b>a pull request</b> please add comment: …
=> KOGITO-4233: [DMN Designer] IntelliSense service

business-central-parent/business-central-webapp/pom.xml, business-central-parent/business-central-webapp/src/main/resources/org/kie/bc/KIEWebapp.gwt.xml
It **DEPENDS ON**:
- https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1537
- https://github.com/kiegroup/kie-wb-common/pull/3498
- https://github.com/kiegroup/drools-wb/pull/1445
- https://github.com/kiegroup/jbpm-wb/pull/1472
Thanks!
=> KOGITO-3891: Stunner - Editors refactoring

business-central-parent/business-central-webapp-common/src/main/webapp/META-INF/jboss-deployment-structure.xml
JIRA: https://issues.redhat.com/browse/JBPM-9678
Merge with:
https://github.com/kiegroup/kie-soup/pull/188
https://github.com/kiegroup/appformer/pull/1122
=> JBPM-9678: Standalone workbench does not start

business-central-parent/business-central-webapp/pom.xml
Signed-off-by: Alberto Morales Perez <almorale@redhat.com>
https://issues.redhat.com/browse/BXMSPROD-1259
Backport for: https://github.com/kiegroup/kie-wb-distributions/pull/1095
=> [7.52.x] BXMSPROD-1272 - reduce GWT Maven plugin compilation classpath

business-central-parent/business-central-webapp/pom.xml
Signed-off-by: Alberto Morales Perez <almorale@redhat.com>
https://issues.redhat.com/browse/BXMSPROD-1259
=> BXMSPROD-1272 - reduce GWT Maven plugin compilation classpath

business-central-parent/business-central-webapp/pom.xml
**JIRA**: [KOGITO-4919](https://issues.redhat.com/browse/KOGITO-4919): [DMN Designer] SDM is broken on -kogito-webapp-runtime
--
**Part of an ensemble:**
- https://github.com/kiegroup/kie-wb-common/pull/3611
- https://github.com/kiegroup/drools-wb/pull/1484
- https://github.com/kiegroup/kie-wb-distributions/pull/1097
--
<details>
<summary>
</summary>
* Retest PR: <b>jenkins retest this</b>
* A full downstream build: <b>jenkins do fdb</b>
* A compile downstream build: <b>jenkins do cdb</b>
* A full production downstream build: <b>jenkins do product fdb</b>
* An upstream build: <b>jenkins do upstream</b>
</details>
=> KOGITO-4919: [DMN Designer] SDM is broken on -kogito-webapp-runtime

.github/workflows/pull_request.yml
**JIRA**: https://issues.redhat.com/browse/BXMSPROD-1333
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1647
* https://github.com/kiegroup/kie-wb-distributions/pull/1104
* https://gitlab.cee.redhat.com/business-automation/eng-jenkins/-/merge_requests/54
<details>
<summary>
</summary>
* <b>a full production downstream build</b> please add comment: <b>Jenkins …
=> [BXMSPROD-1333] kie-wb-distributions test failures fixed

business-central-parent/business-central-webapp/src/main/java/org/kie/bc/client/KieWorkbenchEntryPoint.java, business-central-parent/business-central-webapp/src/test/java/org/kie/bc/client/perspectives/standalone/AuthoringPerspectiveTest.java, business-central-parent/business-monitoring-webapp/src/main/resources/META-INF/ErraiApp.properties, business-central-tests/business-central-tests-gui/README.md, business-central-tests/business-central-tests-gui/src/main/java/org/kie/wb/selenium/model/persps/HomePerspective.java, business-central-tests/business-central-tests-gui/src/test/java/org/kie/wb/selenium/ui/StandalonePerspectivesIntegrationTest.java, business-central-tests/business-central-tests-rest/src/test/java/org/kie/wb/test/rest/functional/ProjectIntegrationTest.java
* Changed restrictive terms with low impact
**JIRA**: 
[AF-2839](https://issues.redhat.com/browse/AF-2839)
[AF-2829](https://issues.redhat.com/browse/AF-2829)
* https://github.com/kiegroup/kie-soup/pull/219
* https://github.com/kiegroup/appformer/pull/1178
* https://github.com/kiegroup/kie-wb-common/pull/3665
* https://github.com/kiegroup/drools-wb/pull/1509
* https://github.com/kiegroup/jbpm-designer/pull/914
* https://github.com/kiegroup/jbpm-wb/pull/1509
* https://github.com/kiegroup/kie-wb-playground/pull/117
* https://github.com/kiegroup/optaplanner-wb/pull/401
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1708
<details>
<summary>
</summary>
* <b>a pull request</b> please add comment: …
=> [DO NOT MERGE] AF-2839 : Conscious language initiative kie-wb-distributions

business-central-parent/business-central-deployment-validation/pom.xml, business-central-parent/business-central-distribution-wars/pom.xml, business-central-parent/business-central-distribution-wars/src/main/community/assembly-kie-wb-wildfly.xml, business-central-parent/business-central-distribution-wars/src/main/community/assembly-kie-wb-wildfly.zip.xml, business-central-parent/business-central-webapp/pom.xml, business-central-parent/business-monitoring-webapp/pom.xml, business-central-parent/business-monitoring-webapp/src/main/config/standalone.xml, business-central-parent/jbpm-server-distribution/src/main/server/standalone.xml, business-central-tests/business-central-tests-gui/README.md, business-central-tests/business-central-tests-gui/pom.xml, business-central-tests/business-central-tests-rest/pom.xml, business-central-tests/pom.xml, pom.xml
**JIRA**: 
[JBPM-9659](https://issues.redhat.com/browse/JBPM-9659)
**Related PRs*: 
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1693
https://github.com/kiegroup/kie-soup/pull/216
https://github.com/kiegroup/droolsjbpm-knowledge/pull/543
https://github.com/kiegroup/drools/pull/3757
https://github.com/kiegroup/optaplanner/pull/1463
https://github.com/kiegroup/lienzo-tests/pull/124
https://github.com/kiegroup/appformer/pull/1163
https://github.com/kiegroup/kie-uberfire-extensions/pull/122
https://github.com/kiegroup/jbpm/pull/1974
https://github.com/kiegroup/kie-jpmml-integration/pull/62
https://github.com/kiegroup/droolsjbpm-integration/pull/2539
https://github.com/kiegroup/kie-wb-playground/pull/115
https://github.com/kiegroup/kie-wb-common/pull/3660 …
=> JBPM-9659: Upgrade deployments to WildFly 23

business-central-parent/business-central-webapp/pom.xml
Part of the encible:
* https://github.com/kiegroup/kie-wb-common/pull/3682
* https://github.com/kiegroup/jbpm-wb/pull/1513
* https://github.com/kiegroup/kie-wb-distributions/pull/1127
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1766
<details>
<summary>
</summary>
* <b>an upstream build</b> please add …
=> JBPM-9896 - fix for Enforcer plugin

.github/workflows/pull_request.yml
Signed-off-by: Alberto Morales Perez <almorale@redhat.com>
=> BXMSPROD-1467 - Sonarcloud reports zero issues

business-central-parent/business-central-webapp/src/main/webapp/WEB-INF/web.xml
[https://issues.redhat.com/browse/JBPM-9959](JBPM-9959)
* paste the link(s) from GitHub here
* link 2
* link 3 etc.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of the …
=> [7.59.x]JBPM-9959 business-central/docs/ do not required to login

business-central-parent/business-central-webapp/src/main/webapp/WEB-INF/web.xml
**JIRA**: 
https://issues.redhat.com/browse/JBPM-9959
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to …
=> JBPM-9959 business-central/docs/ do not required to login

business-central-parent/business-central-distribution-wars/business-central/pom.xml, business-central-parent/pom.xml, pom.xml
**JIRA**: https://issues.redhat.com/browse/RHPAM-4163
**referenced Pull Requests**: https://github.com/kiegroup/kie-wb-distributions/pull/1152
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github …
=> [RHPAM-4163] parametrize the bootable jar GAV used by wildfly-jar-maven-plugin

business-central-parent/business-central-distribution-wars/pom.xml
**JIRA**: https://issues.redhat.com/browse/DROOLS-6853
Related PRs:
https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1912
https://github.com/kiegroup/drools/pull/4261
https://github.com/kiegroup/jbpm/pull/2122
https://github.com/kiegroup/droolsjbpm-integration/pull/2736
https://github.com/kiegroup/drools-wb/pull/1541
https://github.com/kiegroup/jbpm-designer/pull/929
https://github.com/kiegroup/jbpm-wb/pull/1546
https://github.com/kiegroup/kie-wb-distributions/pull/1158
=> [DROOLS-6853] jdk17 compatibility

business-central-parent/business-central-distribution-wars/business-central/pom.xml, business-central-parent/business-central-distribution-wars/src/main/shared/standalone/README.txt, business-central-parent/business-central-webapp-common/src/main/webapp/login.jsp, business-central-parent/business-central-webapp/src/main/webapp/WEB-INF/web.xml, pom.xml
[DROOLS-6859](https://issues.redhat.com/browse/DROOLS-6859)
* https://github.com/kiegroup/kie-wb-distributions/pull/1156
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1908
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can …
=> [DROOLS-6859] Update bootable jar 

business-central-parent/business-central-distribution-wars/business-central/pom.xml, business-central-parent/business-central-distribution-wars/src/main/shared/standalone/README.txt, business-central-parent/business-central-webapp-common/src/main/webapp/login.jsp, business-central-parent/business-central-webapp/src/main/webapp/WEB-INF/web.xml, pom.xml
https://issues.redhat.com/browse/DROOLS-6859 backport
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1944
<details>
<summary>
</summary>
[build-chain …
=> [Drools-6859] backport of XP upgrade

business-central-parent/business-central-home-page-product/src/main/resources/org/kie/bc/client/resources/i18n/Constants_es.properties, business-central-parent/business-central-home-page-product/src/main/resources/org/kie/bc/client/resources/i18n/Constants_fr.properties, business-central-parent/business-central-home-page-product/src/main/resources/org/kie/bc/client/resources/i18n/Constants_ja.properties
[RHDM-1889](https://issues.redhat.com/browse/RHDM-1889)
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to …
=> RHDM-1889: added missing literals

pom.xml
https://issues.redhat.com/browse/DROOLS-6859
Related PRs:
- https://github.com/kiegroup/kie-wb-distributions/pull/1160
- https://github.com/kiegroup/kie-wb-distributions/pull/1161
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used …
=> [DROOLS-6859] set version of EAP XP to 4.0.0.GA-redhat-00004

pom.xml
https://issues.redhat.com/browse/DROOLS-6859
Related PRs:
- https://github.com/kiegroup/kie-wb-distributions/pull/1160
- https://github.com/kiegroup/kie-wb-distributions/pull/1161
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used …
=> [7.67.x][DROOLS-6859] set version of EAP XP to 4.0.0.GA-redhat-00004

business-central-tests/business-central-tests-gui/src/test/java/org/kie/wb/selenium/ui/ProjectLibraryIntegrationTest.java
https://issues.redhat.com/browse/BAPL-2291
- https://github.com/kiegroup/kie-wb-playground/pull/128
- https://github.com/kiegroup/kie-wb-distributions/pull/1162
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line …
=> BAPL-2291 Import Mortgages instead of OptaCloud

business-central-parent/business-central-webapp/pom.xml
**JIRA**: 
https://issues.redhat.com/browse/RHPAM-4387
**Referenced Pull Requests**:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1987
* https://github.com/kiegroup/kie-wb-common/pull/3742
* https://github.com/kiegroup/drools-wb/pull/1543
* https://github.com/kiegroup/jbpm-wb/pull/1550
* https://github.com/kiegroup/kie-wb-distributions/pull/1169
**Business Central**: [WAR file](https://donwnload.here/something)
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to …
=> RHPAM-4387 xml-apis:xml-apis excluded

business-central-parent/business-central-webapp/pom.xml
**JIRA**: 
https://issues.redhat.com/browse/RHPAM-4387
**Referenced Pull Requests**:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2012
* https://github.com/kiegroup/kie-wb-common/pull/3745
* https://github.com/kiegroup/drools-wb/pull/1545
* https://github.com/kiegroup/jbpm-wb/pull/1553
* https://github.com/kiegroup/kie-wb-distributions/pull/1172
* https://github.com/kiegroup/lienzo-tests/pull/138
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use …
=> [BLUE] RHPAM-4387 xml-apis:xml-apis excluded

business-central-parent/business-central-webapp/pom.xml
**JIRA**: 
https://issues.redhat.com/browse/RHPAM-4387
**Referenced Pull Requests**:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2011
* https://github.com/kiegroup/kie-wb-common/pull/3744
* https://github.com/kiegroup/drools-wb/pull/1544
* https://github.com/kiegroup/jbpm-wb/pull/1552
* https://github.com/kiegroup/kie-wb-distributions/pull/1171
* https://github.com/kiegroup/lienzo-tests/pull/137
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use …
=> [7.67.x] RHPAM-4387 xml-apis:xml-apis excluded (#1169)

business-central-parent/business-central-webapp/pom.xml, business-central-parent/business-central-webapp/src/main/resources/org/kie/bc/KIEWebapp.gwt.xml, business-central-parent/business-central-webapp/src/main/webapp/WEB-INF/web.xml
[link](https://issues.redhat.com/browse/JBPM-10083)
https://github.com/kiegroup/kie-wb-common/pull/3743
(Takes care of migration of bpmn2 files within Stunner)
https://drive.google.com/drive/folders/195afqwca3fw7Bg-48wK3XmSa7bxJCRtD?usp=sharing
(War file)
* paste the link(s) from GitHub here
* link 2
* link 3 etc.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of …
=> JBPM-10083 : Legacy (jBPM) Process Designer Removal

business-central-parent/business-central-webapp/pom.xml, business-central-parent/business-central-webapp/src/main/resources/org/kie/bc/KIEWebapp.gwt.xml, business-central-parent/business-central-webapp/src/main/webapp/WEB-INF/web.xml
Jira
[link](https://issues.redhat.com/browse/JBPM-10083)
https://github.com/kiegroup/kie-wb-common/pull/3752
War file can be found here
https://drive.google.com/drive/folders/1qI0ovyaSazgHS6QgcAmGXPlksSD7y5pn?usp=sharing
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain …
=> [7.67.x-blue] JBPM-10083: Legacy (jBPM) Process Designer Removal

.github/workflows/pull_request.yml
https://github.com/kiegroup/kie-wb-common/pull/3762
https://github.com/kiegroup/droolsjbpm-integration/pull/2840
https://github.com/kiegroup/kie-wb-distributions/pull/1180
and cherry-picked to
7.67.x:
https://github.com/kiegroup/droolsjbpm-integration/pull/2842
https://github.com/kiegroup/kie-wb-common/pull/3764
https://github.com/kiegroup/kie-wb-distributions/pull/1181
7.67.x-blue:
https://github.com/kiegroup/droolsjbpm-integration/pull/2843
https://github.com/kiegroup/kie-wb-common/pull/3765
https://github.com/kiegroup/kie-wb-distributions/pull/1182
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates …
=> skipped parallel checkouts for build chain

business-central-parent/business-central-webapp/pom.xml, business-central-parent/business-central-webapp/src/main/resources/org/kie/bc/KIEWebapp.gwt.xml, business-central-parent/business-central-webapp/src/main/webapp/WEB-INF/web.xml
[link](https://issues.redhat.com/browse/JBPM-10083)
https://github.com/kiegroup/kie-wb-common/pull/3759
* link 2
* link 3 etc.
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest …
=> [7.67.x] JBPMN-10083 : Legacy (jBPM) Process Designer Removal - Removing Legacy Designer from kie-wb-distributions

business-central-parent/business-central-distribution-wars/src/main/productized/webapp/index.jsp, business-central-parent/business-central-distribution-wars/src/main/productized/webapp/login.jsp, business-central-parent/business-central-distribution-wars/src/main/productized/webapp/logout.jsp, business-central-parent/business-central-distribution-wars/src/main/productized/webapp/not_authorized.jsp, business-central-parent/business-central-webapp-common/src/main/webapp/index.jsp, business-central-parent/business-central-webapp-common/src/main/webapp/login.jsp, business-central-parent/business-central-webapp-common/src/main/webapp/logout.jsp, business-central-parent/business-central-webapp-common/src/main/webapp/not_authorized.jsp
[KOGITO-7179](https://issues.redhat.com/browse/KOGITO-7179)
[ZIP](https://drive.google.com/file/d/1zIhk_nHztSZqG6fOdSvbcB7TJUlrz9uL/view?usp=sharing)
[WAR](https://drive.google.com/file/d/1W9fr_1jPMoX6GURgnLpkUhmhk6QbGTQX/view?usp=sharing)
<details>
<summary>
</summary>
[build-chain …
=> KOGITO-7179 : Business Central usage of resource.getContextPath() is insecure

business-central-parent/business-central-distribution-wars/src/main/productized/webapp/index.jsp, business-central-parent/business-central-distribution-wars/src/main/productized/webapp/login.jsp, business-central-parent/business-central-distribution-wars/src/main/productized/webapp/logout.jsp, business-central-parent/business-central-distribution-wars/src/main/productized/webapp/not_authorized.jsp, business-central-parent/business-central-webapp-common/src/main/webapp/index.jsp, business-central-parent/business-central-webapp-common/src/main/webapp/login.jsp, business-central-parent/business-central-webapp-common/src/main/webapp/logout.jsp, business-central-parent/business-central-webapp-common/src/main/webapp/not_authorized.jsp
[KOGITO-7179](https://issues.redhat.com/browse/KOGITO-7179)
[ZIP](https://drive.google.com/file/d/172S0-z6yVE1i1CXFMVCKn4oT5gA-6iN-/view?usp=sharing)
[WAR](https://drive.google.com/file/d/1aYMMh92OVrdiBgQKrBhkqckbLNK-skfe/view?usp=sharing)
<details>
<summary>
</summary>
[build-chain …
=> [7.67.x-blue] KOGITO-7179 : Business Central usage of resource.getContextPath() is insecure

business-central-parent/business-central-distribution-wars/src/main/productized/webapp/index.jsp, business-central-parent/business-central-distribution-wars/src/main/productized/webapp/login.jsp, business-central-parent/business-central-distribution-wars/src/main/productized/webapp/logout.jsp, business-central-parent/business-central-distribution-wars/src/main/productized/webapp/not_authorized.jsp, business-central-parent/business-central-webapp-common/src/main/webapp/index.jsp, business-central-parent/business-central-webapp-common/src/main/webapp/login.jsp, business-central-parent/business-central-webapp-common/src/main/webapp/logout.jsp, business-central-parent/business-central-webapp-common/src/main/webapp/not_authorized.jsp
[KOGITO-7179](https://issues.redhat.com/browse/KOGITO-7179)
[ZIP](https://drive.google.com/file/d/12utuk97mNZf0_9qMRNg23Hn1dcy4s2tU/view?usp=sharing)
[WAR](https://drive.google.com/file/d/129LRYk5V2_0y0B3PQTaETux23pqPEfmm/view?usp=sharing)
<details>
<summary>
</summary>
[build-chain …
=> [7.67.x] KOGITO-7179 : Business Central usage of resource.getContextPath() is insecure

pom.xml
This prod version is the latest released version and it is EAP XP on top of EAP 7.4.7
**Jira** https://issues.redhat.com/browse/RHPAM-4564
- https://github.com/kiegroup/kie-wb-distributions/pull/1199
- https://github.com/kiegroup/kie-wb-distributions/pull/1200
- https://github.com/kiegroup/kie-wb-distributions/pull/1201
<details>
<summary>
</summary> …
=> [RHPAM-4564] update EAP XP to version 4.0.0.GA-redhat-00009

pom.xml
This prod version is the latest released version and it is EAP XP on top of EAP 7.4.7
**Jira** https://issues.redhat.com/browse/RHPAM-4564
- https://github.com/kiegroup/kie-wb-distributions/pull/1199
- https://github.com/kiegroup/kie-wb-distributions/pull/1200
- https://github.com/kiegroup/kie-wb-distributions/pull/1201
<details>
<summary>
</summary> …
=> [7.67.x][RHPAM-4564] update EAP XP to version 4.0.0.GA-redhat-00009

pom.xml
This prod version is the latest released version and it is EAP XP on top of EAP 7.4.7
**Jira** https://issues.redhat.com/browse/RHPAM-4564
- https://github.com/kiegroup/kie-wb-distributions/pull/1199
- https://github.com/kiegroup/kie-wb-distributions/pull/1200
- https://github.com/kiegroup/kie-wb-distributions/pull/1201
<details>
<summary>
</summary> …
=> [7.67.x-blue][RHPAM-4564] update EAP XP to version 4.0.0.GA-redhat-00009

pom.xml
This prod version is EAP XP on top of EAP 7.4.8
**JIRA**:  https://issues.redhat.com/browse/RHPAM-4618
- https://github.com/kiegroup/kie-wb-distributions/pull/1208
- https://github.com/kiegroup/kie-wb-distributions/pull/1206
- https://github.com/kiegroup/kie-wb-distributions/pull/1207
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those repositories there is a need to use [build-chain tool](https://github.com/kiegroup/github-action-build-chain) to handle cross repository builds and be sure that we always use latest version of …
=> [7.67.x][RHPAM-4618] update EAP XP to version 4.0.0.GA-redhat-00011

business-central-parent/business-central-webapp/pom.xml
https://issues.redhat.com/browse/BXMSPROD-1845
Related PRs:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2168
* https://github.com/kiegroup/kie-soup/pull/260
* https://github.com/kiegroup/appformer/pull/1368
* https://github.com/kiegroup/kie-wb-common/pull/3793
* https://github.com/kiegroup/drools-wb/pull/1562
* https://github.com/kiegroup/jbpm-wb/pull/1579
* https://github.com/kiegroup/optaplanner-wb/pull/421
* https://github.com/kiegroup/kie-wb-distributions/pull/1209
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method …
=> [7.67.x] [BXMSPROD-1845] elasticsearch removed from appformer (#1196)

business-central-parent/business-central-webapp/pom.xml
**JIRA**: https://issues.redhat.com/browse/DROOLS-7105
- (main) https://github.com/kiegroup/drools/pull/4614
- (7.x for alignment) https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2031
- (7.x for alignment) https://github.com/kiegroup/drools/pull/4632
- (7.x for alignment) https://github.com/kiegroup/kie-wb-common/pull/3769
- (7.x for alignment) https://github.com/kiegroup/drools-wb/pull/1552
- (7.x for alignment) https://github.com/kiegroup/kie-wb-distributions/pull/1187
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of …
=> DROOLS-7105 DMN upgrade to Antlr 4.10

business-central-parent/business-central-webapp/pom.xml
**JIRA**: Back port for
https://issues.redhat.com/browse/BXMSPROD-1845
Related PRs:
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2169
* https://github.com/kiegroup/kie-soup/pull/261
* https://github.com/kiegroup/appformer/pull/1369
* https://github.com/kiegroup/kie-wb-common/pull/3794
* https://github.com/kiegroup/drools-wb/pull/1563
* https://github.com/kiegroup/jbpm-wb/pull/1580
* https://github.com/kiegroup/kie-wb-distributions/pull/1210
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or class method could affect several of those …
=> [7.67.x-blue] [BXMSPROD-1845] elasticsearch removed from appformer (#1196)

business-central-parent/business-central-webapp/pom.xml
This reverts commit 25dfff39959380512cf099e4a99c2cf1013c1227.
Reverting on 7.x due to Antlr tooling (not runtime) incompatibility with Java 8.
**JIRA**: https://issues.redhat.com/browse/DROOLS-7105
* (revert) https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2189
* (revert) https://github.com/kiegroup/drools/pull/4911
* (revert) https://github.com/kiegroup/kie-wb-common/pull/3797
* (revert) https://github.com/kiegroup/drools-wb/pull/1566
* (revert) https://github.com/kiegroup/kie-wb-distributions/pull/1212
<details>
<summary>
</summary>
Build Chain tool does "simple" maven build(s), the builds are just Maven commands, but because the repositories relates and depends on each other and any change in API or …
=> DROOLS-7105 Revert "DROOLS-7105 DMN upgrade to Antlr 4.10 (#1187)"

business-central-parent/business-central-webapp/src/main/webapp/WEB-INF/web.xml, business-central-parent/business-monitoring-webapp/src/main/webapp/WEB-INF/web.xml
**RHPAM-4431**: https://issues.redhat.com/browse/RHPAM-4431
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you …
=> RHPAM-4431: Session Cookie Without Secure Attribute Set

business-central-parent/business-central-webapp/src/main/webapp/WEB-INF/web.xml, business-central-parent/business-monitoring-webapp/src/main/webapp/WEB-INF/web.xml
**RHPAM-4431**: https://issues.redhat.com/browse/RHPAM-4431
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you …
=> [7.67.x] RHPAM-4431: Session Cookie Without Secure Attribute Set

business-central-tests/business-central-tests-gui/src/test/filtered-resources/arquillian.xml
**JIRA**:  [AF-2948](https://issues.redhat.com/browse/AF-2948)
* [main] https://github.com/kiegroup/kie-wb-distributions/pull/1215
* [7.67.x] https://github.com/kiegroup/kie-wb-distributions/pull/1216
* [7.67.x-blue] https://github.com/kiegroup/kie-wb-distributions/pull/1217
<details>
<summary>
</summary> …
=> AF-2948: Update Firefox Gecko driver to version 0.33.0

business-central-tests/business-central-tests-gui/src/test/filtered-resources/arquillian.xml
**JIRA**:  [AF-2948](https://issues.redhat.com/browse/AF-2948)
* [main] https://github.com/kiegroup/kie-wb-distributions/pull/1215
* [7.67.x] https://github.com/kiegroup/kie-wb-distributions/pull/1216
* [7.67.x-blue] https://github.com/kiegroup/kie-wb-distributions/pull/1217
<details>
<summary>
</summary> …
=> [7.67.x] AF-2948: Update Firefox Gecko driver to version 0.33.0

business-central-tests/business-central-tests-gui/src/test/filtered-resources/arquillian.xml
**JIRA**:  [AF-2948](https://issues.redhat.com/browse/AF-2948)
* [main] https://github.com/kiegroup/kie-wb-distributions/pull/1215
* [7.67.x] https://github.com/kiegroup/kie-wb-distributions/pull/1216
* [7.67.x-blue] https://github.com/kiegroup/kie-wb-distributions/pull/1217
<details>
<summary>
</summary> …
=> [7.67.x-blue] AF-2948: Update Firefox Gecko driver to version 0.33.0

pom.xml
This prod version is EAP XP on top of EAP 7.4.10
**JIRA**: https://issues.redhat.com/browse/RHPAM-4656
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need to …
=> [RHPAM-4656] update EAP XP to version 4.0.0.GA-redhat-00017

business-central-parent/business-monitoring-webapp/pom.xml, business-central-tests/business-central-tests-gui/pom.xml
* https://github.com/kiegroup/kie-wb-distributions/pull/1223
* https://github.com/kiegroup/appformer/pull/1387
* https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/2310
<details>
<summary>
</summary>
[build-chain …
=> Bump xalan from 2.7.2 to 2.7.3

pom.xml
This prod version is EAP XP 4 on top of EAP 7.4.11
**JIRA**:  https://issues.redhat.com/browse/RHPAM-4726
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or in Github Actions workflow(s), in case you need …
=> [RHPAM-4726] update EAP XP to version 4.0.1.GA-redhat-00001

pom.xml
This prod version is EAP XP 4 on top of EAP 7.4.13 and already including fixes for CVE-2023-44487
**JIRA**: https://issues.redhat.com/browse/RHPAM-4821
<details>
<summary>
</summary>
[build-chain tool](https://github.com/kiegroup/github-action-build-chain) is a build tool which can be used on command line locally or …
=> [RHPAM-4821] update EAP XP to version 4.0.1.GA-redhat-00007
